{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"All Measure\",\"ServiceRiskAnalysisCombined\",\"All Summary Measures\",\"NewSummaryMeasure\",\"SnapshotRiskbytype\",\"Measure for Mnthly Dashboard\",\"VW_Risk_Level_Groups\",\"DimServiceLocationsMapping\",\"VW_Reporting_Calendar\",\"Table (2)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "f05509a6-530f-4890-9838-03ead314c00d",
        "fromColumn": "CalendarMonthNameYear_New",
        "fromTable": "ServiceRiskAnalysisCombined",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a6b79582-a5d1-43a0-ab76-c7f902d0d17b"
      },
      {
        "name": "d3bb4120-82b9-4e57-815d-ed429a83c6e7",
        "fromColumn": "SnapshotDate - Copy",
        "fromTable": "SnapshotRiskbytype",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a04394d1-20be-4d7a-8ced-363cd252879d"
      },
      {
        "name": "d11cd7de-afec-4eca-b92f-c00ac14cade2",
        "fromColumn": "CalendarMonthNameYear - Copy",
        "fromTable": "SnapshotRiskbytype",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0fa806a5-90a9-4072-a8a9-275e2ac65b3d"
      },
      {
        "name": "3e156957-5abc-4ad7-8be9-c1c19675e64d",
        "fromColumn": "WeekEnd Date",
        "fromTable": "SnapshotRiskbytype",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b4e98804-ed73-46c7-adef-0b320e68ac96"
      },
      {
        "name": "39df39e7-6019-42ee-8529-35e7370e226b",
        "fromColumn": "WeekDate",
        "fromTable": "SnapshotRiskbytype",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8c3691f2-59b0-4e87-ad93-2943ed2dc02b"
      },
      {
        "name": "35f507c6-97e2-46b5-b366-825656879983",
        "fromColumn": "CalendarMonthNameYear",
        "fromTable": "SnapshotRiskbytype",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ee449bc3-2cb8-4430-9c1f-d230ea3cc726"
      },
      {
        "name": "7f117174-c50c-49c7-a4e3-0303ab44ad3c",
        "fromColumn": "Date",
        "fromTable": "SnapshotRiskbytype",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e50f56d3-ada2-4687-886c-83e896ca9442"
      },
      {
        "name": "f6c3cfef-b643-4a44-9a30-7a45f3d0e96c",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "HASH KEY",
        "fromTable": "SnapshotRiskbytype",
        "toCardinality": "many",
        "toColumn": "Hashkey",
        "toTable": "ServiceRiskAnalysisCombined"
      },
      {
        "name": "b1ba1d15-dfce-43aa-8883-df7b1c5d26e5",
        "fromColumn": "MonthYear",
        "fromTable": "SnapshotRiskbytype",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_412af3c3-2343-4649-86dd-f10f833f1a4b"
      },
      {
        "name": "c828dc18-fb26-4f72-b72e-a69456eae6be",
        "fromColumn": "FacilityName",
        "fromTable": "ServiceRiskAnalysisCombined",
        "toColumn": "Title",
        "toTable": "DimServiceLocationsMapping"
      },
      {
        "name": "28cfc4fd-a8fb-44aa-8c1c-5ee045024b0c",
        "fromColumn": "FacilityName",
        "fromTable": "VW_Risk_Level_Groups",
        "isActive": false,
        "toColumn": "Title",
        "toTable": "DimServiceLocationsMapping"
      },
      {
        "name": "b3a87a1f-c91c-44d3-95d4-f0835da6e0d5",
        "fromColumn": "Date",
        "fromTable": "ServiceRiskAnalysisCombined",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_40459186-9a00-4d17-87f1-129b9e044325"
      },
      {
        "name": "94c80c57-ff62-4d58-9111-af218383f91b",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "CalendarMonth",
        "fromTable": "ServiceRiskAnalysisCombined",
        "toColumn": "CalendarYearMonth",
        "toTable": "VW_Reporting_Calendar"
      },
      {
        "name": "35a10911-f241-4015-a852-b6e3d428bae6",
        "fromColumn": "Source_RiskValue",
        "fromTable": "SnapshotRiskbytype",
        "toColumn": "Source_RiskValue",
        "toTable": "Table (2)"
      },
      {
        "name": "1d62ce91-1a07-4b19-9403-83c99dad26b2",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "HOA_FiscalMonth",
        "fromTable": "SnapshotRiskbytype",
        "toColumn": "HOA_FiscalMOnth",
        "toTable": "Head of Operations"
      },
      {
        "name": "b46455f2-78a0-444c-9c30-9e28d06f17da",
        "fromColumn": "Date",
        "fromTable": "VW_Reporting_Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_65c127da-c204-48fa-8138-59bcdfce17b8"
      },
      {
        "name": "a0ff4562-debf-4d9e-890c-b5c0691c32e8",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "Hashkey",
        "fromTable": "ServiceRiskAnalysisCombined",
        "toCardinality": "many",
        "toColumn": "HashKey",
        "toTable": "VW_Risk_Level_Groups"
      },
      {
        "name": "a4a8c1ff-235b-425b-98b3-bc278dba43ca",
        "fromColumn": "First_Date_of_Month",
        "fromTable": "VW_Reporting_Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9359371c-f6a8-4e93-a3c9-49bd5d0f4dd6"
      },
      {
        "name": "f6b10162-a512-41ad-8689-5d39f9bac5c7",
        "fromColumn": "Last_Date_of_Month",
        "fromTable": "VW_Reporting_Calendar",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_0623f1e2-e5a3-4be3-84ed-f2d9bcdb69e7"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "All Measure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "91a81d54-0eb4-4101-bcdb-0d4a8c6ade3f",
        "measures": [
          {
            "name": "CombinedRisk",
            "expression": "'All Measure'[ACP_MEASURE] +  'All Measure'[ManagerVacancies_MEASURE] + 'All Measure'[TrainingCompliance_MEASURE]  + 'All Measure'[TeamMemberAttri_MEASURE] + 'All Measure'[IRNYRated_Measure] + 'All Measure'[MRwithCQC_Measure] + 'All Measure'[LatestInternalAudit_MEASURE] + 'All Measure'[LatestCQCInspection]+'All Measure'[Recruitment]+'All Measure'[R3_Regnional Manager]+[R3_F2f]",
            "formatString": "0",
            "lineageTag": "45f96898-63a1-471d-a239-1a7e7e64d862"
          },
          {
            "name": "MRwithCQC_Measure",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]),ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] =3)",
            "formatString": "0",
            "lineageTag": "b20e51a0-82f9-4434-988e-d590ee733c04"
          },
          {
            "name": "IRNYRated_Measure",
            "expression": [
              "BLANK()",
              "--CALCULATE(COUNT(ServiceRiskAnalysisCombined[Regulator ID]),FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Inherited_Rating] = \"N\"))*0",
              ""
            ],
            "formatString": "0",
            "lineageTag": "91946908-c6ad-4d93-b096-e05b8bdec7e9"
          },
          {
            "name": "ACP_MEASURE",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] =3))",
            "formatString": "0",
            "lineageTag": "67e26610-4139-42d9-920f-0bc700f3218f"
          },
          {
            "name": "ManagerVacancies_MEASURE",
            "expression": "CALCULATE(distinctcount(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service] = 3))",
            "formatString": "0",
            "lineageTag": "b8b19750-6778-4bc9-be82-12e77c0dc775"
          },
          {
            "name": "TrainingCompliance_MEASURE",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] =3))",
            "formatString": "0",
            "lineageTag": "8031a3bf-1871-431f-a470-baee5734e311"
          },
          {
            "name": "TeamMemberAttri_MEASURE",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] =3))",
            "formatString": "0",
            "lineageTag": "047b2f39-2652-4d36-a858-a277bf3f89c3"
          },
          {
            "name": "LatestCQCInspection_MEASURE",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(COUNT('ServiceRiskAnalysisCombined'[CQCinspectionRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[CQCinspectionRisk] in {3,4}))",
              "--CALCULATE(COUNT('ServiceUnratedRiskAnalysis'[CQCinspectionRisk]),ServiceUnratedRiskAnalysis[FiscalMonth]=MAX(ServiceUnratedRiskAnalysis[FiscalMonth]))"
            ],
            "formatString": "0",
            "lineageTag": "e515b8cd-618e-46f6-91f3-725858c50296"
          },
          {
            "name": "LatestInternalAudit_MEASURE",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =3))",
            "formatString": "0",
            "lineageTag": "28261f82-31c0-4eb2-b5e6-72d18f9d1932"
          },
          {
            "name": "R1_LatestCQCInspection_MEASURE",
            "expression": [
              "CALCULATE(COUNT('ServiceRiskAnalysisCombined'[CQCinspectionRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[CQCinspectionRisk] =1))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "928fd8a1-37ad-4a29-8286-80a461a7a56e"
          },
          {
            "name": "R1_LatestInternalAudit_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =1))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "8741e964-3f8e-4d2b-a59a-b546050fadd9"
          },
          {
            "name": "R1_ACP_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] =1))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f91803c0-de3e-4360-b02c-2c7911088fd1"
          },
          {
            "name": "R1_ManagerVacanciesMEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service]= 1))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "8f4aa6ea-ae5c-45f9-b3ba-bd60c7c273d6"
          },
          {
            "name": "R1_MRwithCQC_Measure",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityName]),ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] =1)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fff830a1-6060-4cbd-842d-a5ce569cba11"
          },
          {
            "name": "R1_TeamMemberAttri_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 1))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "39f14b35-cfdf-418d-8c73-c1f20ec7dc6e"
          },
          {
            "name": "R1_TrainingCompliance_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] =1))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "2d503089-81b1-4e2f-b04f-8ba2e349c67b"
          },
          {
            "name": "R1_IRNYRated_Measure",
            "expression": [
              "BLANK()",
              " --CALCULATE(COUNT(ServiceRiskAnalysisCombined[Regulator ID]),FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Inherited_Rating] =\"N\"))*0",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9b9d5928-3d69-4978-8012-8d312b1b792f"
          },
          {
            "name": "R2_LatestCQCInspection_MEASURE",
            "expression": [
              "CALCULATE(COUNT('ServiceRiskAnalysisCombined'[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[CQCinspectionRisk] =2))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "3964368b-c514-494d-b189-6ed0cb864fe9"
          },
          {
            "name": "R2_LatestInternalAudit_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =2))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "95a27108-d9b4-44f4-919d-494572968eed"
          },
          {
            "name": "R2_ACP_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] =2))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0af47a4d-b51d-4d52-9eec-bde573a9fb35"
          },
          {
            "name": "R2_ManagerVacanciesMEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service]= 2))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "c6e63789-0052-4f4f-bf4e-8848378a6a62"
          },
          {
            "name": "R2_MRwithCQC_Measure",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityName]),ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] =2)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "661de2bc-2d75-4691-8739-2398044dcb94"
          },
          {
            "name": "R2_TeamMemberAttri_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 2))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "12cdc561-de10-4359-b2da-6aaf049001f4"
          },
          {
            "name": "R2_TrainingCompliance_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] =2))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "32988aec-4190-45ec-85d4-a1a82f843c21"
          },
          {
            "name": "R2_IRNYRated_Measure",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]),FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Inherited_Rating] in {\"NA\",\"Y\"}))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "dad30b2b-8135-4ddf-a69f-a483a5b2a933"
          },
          {
            "name": "CombinedRiskR1",
            "expression": "'All Measure'[R1_ACP_MEASURE] +  'All Measure'[R1_IRNYRated_Measure] + 'All Measure'[R1_LatestCQCInspection_MEASURE]  + 'All Measure'[R1_LatestInternalAudit_MEASURE] + 'All Measure'[R1_ManagerVacanciesMEASURE] + 'All Measure'[R1_MRwithCQC_Measure] + 'All Measure'[R1_TeamMemberAttri_MEASURE] + 'All Measure'[R1_TrainingCompliance_MEASURE]+'All Measure'[R1_Recruitment]",
            "formatString": "0",
            "lineageTag": "3ef90cf7-cdfb-46e4-8edb-bebcf9a31141"
          },
          {
            "name": "CombinedRiskR2",
            "expression": "'All Measure'[R2_ACP_MEASURE] +  'All Measure'[R2_IRNYRated_Measure] + 'All Measure'[R2_LatestCQCInspection_MEASURE]  + 'All Measure'[R2_LatestInternalAudit_MEASURE] + 'All Measure'[R2_ManagerVacanciesMEASURE] + 'All Measure'[R2_MRwithCQC_Measure] + 'All Measure'[R2_TeamMemberAttri_MEASURE] + 'All Measure'[R2_TrainingCompliance_MEASURE]+'All Measure'[R2_Recruitment]+[R2_F2f]",
            "formatString": "0",
            "lineageTag": "cbd63c38-5f71-4f69-8b2a-30f0fc1a92dc"
          },
          {
            "name": "R0_LatestCQCInspection_MEASURE",
            "expression": [
              "CALCULATE(COUNT('ServiceRiskAnalysisCombined'[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[CQCinspectionRisk] = 0))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9342ec52-b373-415f-8da7-55b16e1a904b"
          },
          {
            "name": "R0_LatestInternalAudit_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] = 0))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1fad83ae-fa8d-478a-ae85-214e78217402"
          },
          {
            "name": "R0_ManagerVacanciesMEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service]= 0))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "87381cfb-50b4-4eea-8ad3-3624400309ea"
          },
          {
            "name": "R0_MRwithCQC_Measure",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityName]),ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] =0)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "7bc34115-10dc-4e70-b122-62a14ec31611"
          },
          {
            "name": "R0_TeamMemberAttri_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 0))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "524cfefe-064e-4f2e-8318-7f4c2bdbea52"
          },
          {
            "name": "R0_TrainingCompliance_MEASURE",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] =0))",
            "formatString": "0",
            "lineageTag": "35893baa-eb3f-4b88-bd87-435d5a19bed9"
          },
          {
            "name": "R0_IRNYRated_Measure",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[Regulator ID]),",
              "FILTER(ServiceRiskAnalysisCombined, OR (ServiceRiskAnalysisCombined[Inherited_Rating] = \"NA\",ServiceRiskAnalysisCombined[Inherited_Rating] = \"Y\")))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "2d8c0a3f-434b-4b2f-b511-bd8bf5482ab1"
          },
          {
            "name": "R0_ACP_MEASURE",
            "expression": [
              "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] =0))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5b792740-afd4-4f2e-afad-d971f707a43a"
          },
          {
            "name": "CombinedRiskR0",
            "expression": "'All Measure'[R0_ACP_MEASURE] +  'All Measure'[R0_IRNYRated_Measure] + 'All Measure'[R0_LatestCQCInspection_MEASURE]  + 'All Measure'[R0_LatestInternalAudit_MEASURE] + 'All Measure'[R0_ManagerVacanciesMEASURE] + 'All Measure'[R0_MRwithCQC_Measure] + 'All Measure'[R0_TeamMemberAttri_MEASURE] + 'All Measure'[R0_TrainingCompliance_MEASURE]",
            "formatString": "0",
            "lineageTag": "dda6b2c4-53e9-406c-b37e-b7e1cb213211"
          },
          {
            "name": "differ",
            "expression": "CALCULATE([CombinedRisk]-[PreviousCombinedRisk_new])",
            "formatString": "0",
            "lineageTag": "160599e1-2681-4f2f-959d-5443e9c20015"
          },
          {
            "name": "Differ2",
            "expression": "SUM(ServiceRiskAnalysisCombined[TotalRisk])-[PrevoiousCombined HighRisk]",
            "formatString": "0",
            "lineageTag": "9e2e42a2-746c-4cef-8e23-2094a01677f7"
          },
          {
            "name": "PreviousCombinedRisk_new",
            "expression": [
              "",
              "CALCULATE([CombinedRisk],ALL(ServiceRiskAnalysisCombined[Current Month Slicer]),PREVIOUSMONTH(ServiceRiskAnalysisCombined[Date]))"
            ],
            "formatString": "0",
            "lineageTag": "c79ebac3-7c64-4fa9-bce9-20c39af6f6fb"
          },
          {
            "name": "PrevoiousCombined HighRisk",
            "expression": "CALCULATE([TotalRisk_Combined],ALL(ServiceRiskAnalysisCombined[Current Month Slicer]),PREVIOUSMONTH(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]))",
            "formatString": "0",
            "lineageTag": "28ab512a-14a5-40d1-8a39-ba14e62bf2b4"
          },
          {
            "name": "Previous CombinedRisk Moderate",
            "expression": "CALCULATE([CombinedRiskR2],ALL(ServiceRiskAnalysisCombined[Current Month Slicer]),PREVIOUSMONTH(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]))",
            "formatString": "0",
            "lineageTag": "3bc51e77-9837-40e9-bb3f-6650db43daa0"
          },
          {
            "name": "R1_PreviousCombinedRisk_new",
            "expression": "CALCULATE([CombinedRiskR1],PREVIOUSMONTH(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]))",
            "formatString": "0",
            "lineageTag": "271f6ce4-1c6e-4534-85c1-58ed0d6e5893"
          },
          {
            "name": "differ_3",
            "expression": "[CombinedRiskR1]-[R1_PreviousCombinedRisk_new]",
            "formatString": "0",
            "lineageTag": "eeb6735d-1b71-42f7-8145-8513269afd4f"
          },
          {
            "name": "differ_4",
            "expression": "[CombinedRiskR2]-[Previous CombinedRisk Moderate]",
            "formatString": "0",
            "lineageTag": "5515be22-0af2-41fa-8cc5-af8a676b1a83"
          },
          {
            "name": "Recruitment",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk] in {3,4}))",
            "formatString": "0",
            "lineageTag": "22a4b22f-2be0-4b24-8848-3486fb194af7"
          },
          {
            "name": "R2_Recruitment",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk] =2))",
            "formatString": "0",
            "lineageTag": "8adea2ac-5d99-4bf2-98f7-3c5e4f305f57"
          },
          {
            "name": "R1_Recruitment",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk] =1))",
            "formatString": "0",
            "lineageTag": "2b613f5b-2850-4aab-9aa0-9178ed488136"
          },
          {
            "name": "R1_Photography Risk",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[PhotographyRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[PhotographyRisk] =1))",
            "formatString": "0",
            "lineageTag": "ce4979a4-07fa-4043-9c29-6c53156814f0"
          },
          {
            "name": "R2_Photography Risk",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[PhotographyRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[PhotographyRisk] =1))",
            "formatString": "0",
            "lineageTag": "927819e6-115b-4283-90b3-ba898eb3e1b4"
          },
          {
            "name": "R4_Recruitment",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[RecruitmentRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk] =4))",
            "formatString": "0",
            "lineageTag": "87fd043b-d67f-499a-abb5-0163d7b35770"
          },
          {
            "name": "HighRiskDistinctCount",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityCode])",
              ",FILTER(ServiceRiskAnalysisCombined,ServiceRiskAnalysisCombined[Agency_cost_pct]=3||ServiceRiskAnalysisCombined[RecruitmentRisk]=3||ServiceRiskAnalysisCombined[RecruitmentRisk]=4||ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]=3||ServiceRiskAnalysisCombined[ElrngOverallComaliance]=3||ServiceRiskAnalysisCombined[InternalAuditRisk]=3||ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated]=3||ServiceRiskAnalysisCombined[Manager_present_at_service]=3||ServiceRiskAnalysisCombined[MGRTurnOver_Risk]=3||ServiceRiskAnalysisCombined[CQCinspectionRisk]=3))",
              "",
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "c9c4eabc-0085-468d-8839-a72569d2b6c2"
          },
          {
            "name": "ModerateRiskDistinctCount",
            "expression": [
              "",
              "",
              "",
              "",
              "VAR B = CALCULATETABLE( values(ServiceRiskAnalysisCombined[FacilityCode])",
              ",FILTER(ServiceRiskAnalysisCombined,ServiceRiskAnalysisCombined[Agency_cost_pct]=3||ServiceRiskAnalysisCombined[RecruitmentRisk]=3||ServiceRiskAnalysisCombined[RecruitmentRisk]=4||ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]=3||ServiceRiskAnalysisCombined[ElrngOverallComaliance]=3||ServiceRiskAnalysisCombined[InternalAuditRisk]=3||ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated]=3||ServiceRiskAnalysisCombined[Manager_present_at_service]=3||ServiceRiskAnalysisCombined[MGRTurnOver_Risk]=3||ServiceRiskAnalysisCombined[CQCinspectionRisk]=3))",
              "",
              "VAR A = CALCULATE(DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityCode])",
              ",FILTER(ServiceRiskAnalysisCombined,(ServiceRiskAnalysisCombined[Agency_cost_pct]=2||ServiceRiskAnalysisCombined[RecruitmentRisk]=2||ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]=2||ServiceRiskAnalysisCombined[ElrngOverallComaliance]=2||ServiceRiskAnalysisCombined[InternalAuditRisk]=2||ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated]=2||ServiceRiskAnalysisCombined[Manager_present_at_service]=2||ServiceRiskAnalysisCombined[MGRTurnOver_Risk]=2||ServiceRiskAnalysisCombined[CQCinspectionRisk]=2) &&",
              "NOT(ServiceRiskAnalysisCombined[FacilityCode]) IN B  ))",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1))",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0e6e7c99-e227-4491-bd82-a4c4a2762106"
          },
          {
            "name": "LowRiskDistinctCount",
            "expression": [
              "",
              "",
              "",
              "",
              "VAR B = CALCULATETABLE( values(ServiceRiskAnalysisCombined[FacilityCode])",
              ",FILTER(ServiceRiskAnalysisCombined,ServiceRiskAnalysisCombined[Agency_cost_pct]=3||ServiceRiskAnalysisCombined[RecruitmentRisk]=3||ServiceRiskAnalysisCombined[RecruitmentRisk]=4||ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]=3||ServiceRiskAnalysisCombined[ElrngOverallComaliance]=3||ServiceRiskAnalysisCombined[InternalAuditRisk]=3||ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated]=3||ServiceRiskAnalysisCombined[Manager_present_at_service]=3||ServiceRiskAnalysisCombined[MGRTurnOver_Risk]=3||ServiceRiskAnalysisCombined[CQCinspectionRisk]=3||ServiceRiskAnalysisCombined[Agency_cost_pct]=2||ServiceRiskAnalysisCombined[RecruitmentRisk]=2||ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]=2||ServiceRiskAnalysisCombined[ElrngOverallComaliance]=2||ServiceRiskAnalysisCombined[InternalAuditRisk]=2||ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated]=2||ServiceRiskAnalysisCombined[Manager_present_at_service]=2||ServiceRiskAnalysisCombined[MGRTurnOver_Risk]=2||ServiceRiskAnalysisCombined[CQCinspectionRisk]=2) )",
              "",
              "VAR A = CALCULATE(DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityCode])",
              ",FILTER(ServiceRiskAnalysisCombined,(ServiceRiskAnalysisCombined[Agency_cost_pct]=2||ServiceRiskAnalysisCombined[RecruitmentRisk]=1||ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]=1||ServiceRiskAnalysisCombined[ElrngOverallComaliance]=1||ServiceRiskAnalysisCombined[InternalAuditRisk]=1||ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated]=1||ServiceRiskAnalysisCombined[Manager_present_at_service]=1||ServiceRiskAnalysisCombined[MGRTurnOver_Risk]=1||ServiceRiskAnalysisCombined[CQCinspectionRisk]=1) &&",
              "NOT(ServiceRiskAnalysisCombined[FacilityCode]) IN B  ))",
              "",
              "",
              "",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1))",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d2b43534-af71-4a0e-965b-3533b7fe89d4"
          },
          {
            "name": "TotalRisk",
            "expression": "[HighRiskDistinctCount]+[LowRiskDistinctCount]+[ModerateRiskDistinctCount]",
            "formatString": "0",
            "lineageTag": "a9959cf3-b08f-422e-97f6-427175ee00d7"
          },
          {
            "name": "HighRisk_Percentage",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([HighRiskDistinctCount]/[TotalRisk])",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5bc7bade-fa3f-466b-b6fa-d2bd4de0196c"
          },
          {
            "name": "R3_Regnional Manager",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RegionalMGR_Risk] =3))",
            "formatString": "0",
            "lineageTag": "75f9b65b-d480-4a53-8401-05fd413dcf2e"
          },
          {
            "name": "R2_RegionaManagerRisk",
            "expression": "BLANK()",
            "formatString": "0",
            "lineageTag": "6a67339f-7a33-4d26-96d2-05320f8af480"
          },
          {
            "name": "CombinedRisk HighRisk Arrows",
            "expression": [
              "IF( FORMAT(SELECTEDVALUE(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]), \"MMMM YYYY\") = FORMAT(NOW(),\"MMMM YYYY\"), BLANK(),",
              "",
              "If([differ]>=0 , \"ColoredArrowUpRed\", \"ColoredArrowDownGreen\"))"
            ],
            "lineageTag": "a0e1249d-3040-472f-8709-3a56948eb5f2"
          },
          {
            "name": "CombinedRisk Moderate ARrows",
            "expression": [
              "IF( FORMAT(SELECTEDVALUE(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]), \"MMMM YYYY\") = FORMAT(NOW(),\"MMMM YYYY\"), BLANK(),",
              "",
              "If([Differ2]>=0 , \"ColoredArrowUpRed\", \"ColoredArrowDownGreen\"))"
            ],
            "lineageTag": "260c8a7d-ac4d-4beb-918d-756693d19653"
          },
          {
            "name": "Percentage_Agency",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"),SnapshotRiskbytype[RiskValue]=3,SnapshotRiskbytype[SOURCE]<>\"totalrisk\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))/[FacilityCount]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "a325ee07-e66c-412c-99e0-cb505c8e8f80"
          },
          {
            "name": "Percentage_ManagerRegistered",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Regd Mgr Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))/[FacilityCount]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "2c844dc4-ce64-4469-8c92-48ad9d117e68"
          },
          {
            "name": "Percentage_MGRVacncies",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"ManagerVacancies Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))/[FacilityCount]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "71f5918b-e157-4fd2-889b-40010f639624"
          },
          {
            "name": "Percentage_Regional",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Regional Manager Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SOURCE]<>\"totalrisk\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))/[FacilityCount]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0ecec132-65aa-4be6-8256-5b3bdfc6874c"
          },
          {
            "name": "Percentage_TeamMember",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Team Attrition Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))/[FacilityCount]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3347d0db-8c2b-4064-b320-8fb1f042906e"
          },
          {
            "name": "Percentage_InternalAudit",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                                                SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\",             SnapshotRiskbytype[RiskValue] = 3,",
              "snapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))/[FacilityCount]"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f0dcda94-a2db-42d7-b8d5-6296276ebfca"
          },
          {
            "name": "Percentage_CQCInspection",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                    FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"),                            SnapshotRiskbytype[RiskValue]in {3,4},SnapshotRiskbytype[SnapshotDate]=",
              "                                                        MAX(SnapshotRiskbytype[SnapshotDate]))/[FacilityCount]",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "52c48f27-09fb-4473-bb2f-d3bcda360a36"
          },
          {
            "name": "Percentage_Recruitment",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"),SnapshotRiskbytype[RiskValue]in {3,4},SnapshotRiskbytype[SOURCE]<>\"totalrisk\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))/[FacilityCount]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "6d61c839-b8d4-4ebe-9384-9011fff3267f"
          },
          {
            "name": "Percentage_Training",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Elearning Compliance Risk\"),SnapshotRiskbytype[RiskValue]in {3,4},SnapshotRiskbytype[SOURCE]<>\"totalrisk\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))/[FacilityCount]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f7fe8456-37f1-4619-9cf3-9f866effc7c2"
          },
          {
            "name": "Category_Colour",
            "expression": [
              "--IF([TotalCategory]>=[Category Selected Month Check],\"#FD625E\",\"#00B810\")",
              " ",
              " IF([TotalCategory]>=[PreviousweekCategory],\"#FD625E\",\"#00B810\")"
            ],
            "lineageTag": "9ab88271-c0a7-4f9c-b9fc-2b65a57eab69"
          },
          {
            "name": "LatestCQCInspection",
            "expression": [
              "CALCULATE(COUNT('ServiceRiskAnalysisCombined'[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[CQCinspectionRisk] in {3,4}))",
              "--CALCULATE(COUNT('ServiceUnratedRiskAnalysis'[CQCinspectionRisk]),ServiceUnratedRiskAnal"
            ],
            "formatString": "0",
            "lineageTag": "1703b437-fdc0-4794-b7b0-851d1573bde0"
          },
          {
            "name": "Date Test",
            "expression": [
              "-- FORMAT(SELECTEDVALUE(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]), \"MMMM YYYY\") = ",
              "",
              "FORMAT(NOW(),\"DD YYYY\",-7)",
              "",
              "--FORMAT(NOW(),\"MMMM YYYY\")"
            ],
            "lineageTag": "5e0e5ec8-f983-495f-b01e-2d495949098a"
          },
          {
            "name": "HopPercentagecolour",
            "expression": "CALCULATE(IF([HopPercentage]>=[Hop Percentage Last week],\"#FD625E\",\"#00B810\"))",
            "lineageTag": "e2f2ffb3-8d22-42ed-8c6f-4c22f293e8a4"
          },
          {
            "name": "TotalRisk_Combined",
            "expression": "SUM(ServiceRiskAnalysisCombined[TotalRisk])",
            "formatString": "0",
            "lineageTag": "7516901b-9476-40c3-8cb8-d9570a91482c"
          },
          {
            "name": "Weekly Combined Arrows",
            "expression": [
              "",
              "",
              " IF( FORMAT(SELECTEDVALUE(SnapshotRiskbytype[CalendarMonthNameYear]), \"MMMM YYYY\") = FORMAT(NOW(),\"MMMM YYYY\"), BLANK(),",
              "                If([Weekly CombinedScore]-[PreviousWeekServices]>=0 , \"ColoredArrowUpRed\", \"ColoredArrowDownGreen\"))",
              "",
              ""
            ],
            "lineageTag": "ee55f8aa-2cb3-4e0d-a1e3-0015a9c86c8a"
          },
          {
            "name": "Good Rating Services",
            "expression": [
              "var a= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[RecruitmentRisk] in {0,1,2}) --|| ServiceRiskAnalysisCombined[RecruitmentRisk] in{1,2})",
              "var b= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[Agency_cost_pct] in {0,1,2})",
              "var c= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[RegionalMGR_Risk] in {0,1,2})",
              "var d= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[InternalAuditRisk] in {0,1,2})",
              "var e= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[CQCinspectionRisk] in {0,1,2})",
              "var f= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] in {0,1,2})",
              "var g= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[Manager_present_at_service] in {0,1,2})",
              "var h= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[MGRTurnOver_Risk] in {0,1,2})",
              "var i= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated] in {0,2})",
              "return a+b+c+d+e+f+g+h+i",
              ""
            ],
            "formatString": "0",
            "lineageTag": "8c4490f7-2a9a-4679-85e6-4d3c6ea8323b"
          },
          {
            "name": "High Rating Services",
            "expression": [
              "var a= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[RecruitmentRisk] in {3,4}) --|| ServiceRiskAnalysisCombined[RecruitmentRisk] in{1,2})",
              "var b= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[Agency_cost_pct] in {3,4})",
              "var c= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[RegionalMGR_Risk] in {3,4})",
              "var d= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[InternalAuditRisk] in {3,4})",
              "var e= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[CQCinspectionRisk] in {3,4})",
              "var f= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] in {3,4})",
              "var g= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[Manager_present_at_service] in {3,4})",
              "var h= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[MGRTurnOver_Risk] in {3,4})",
              "var i= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]),ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated] in {3,4})",
              "return a+b+c+d+e+f+g+h+i"
            ],
            "formatString": "0",
            "lineageTag": "8c49e6ec-cc2a-42af-8605-adc34ddd32bd"
          },
          {
            "name": "Percentage_F2f",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"F2f Compliance Risk\"),SnapshotRiskbytype[RiskValue]in {3,4},SnapshotRiskbytype[SOURCE]<>\"totalrisk\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))/[FacilityCount]",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "64e25d00-6ba3-4bf3-8183-d11836b475b2"
          },
          {
            "name": "R3_F2f",
            "expression": "CALCULATE(COUNT('ServiceRiskAnalysisCombined'[FacilityName]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[F2FOverallComaliance] =3))",
            "formatString": "0",
            "lineageTag": "7fe2f49a-98b2-420b-beaa-b3bd6723e487"
          },
          {
            "name": "R2_F2f",
            "expression": "CALCULATE(COUNT('ServiceRiskAnalysisCombined'[FacilityCode]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[F2FOverallComaliance] =2))",
            "formatString": "0",
            "lineageTag": "d14e3a71-7dc9-40ed-85e5-eade53ddad67"
          },
          {
            "name": "R1_F2f",
            "expression": "CALCULATE(COUNT('ServiceRiskAnalysisCombined'[FacilityCode]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[F2FOverallComaliance] =1))",
            "formatString": "0",
            "lineageTag": "cd022874-3c71-4bbf-81bb-b3fd83aaf338"
          }
        ],
        "partitions": [
          {
            "name": "All Measure-ca59a036-3345-41cf-a196-d41f3525d7da",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WCkktLlGKjQUA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Test = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Test\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Test\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "ServiceRiskAnalysisCombined",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "UniqueRecord",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e191ea74-5042-4daa-be9b-12b79ba66acb",
            "sourceColumn": "UniqueRecord",
            "summarizeBy": "none"
          },
          {
            "name": "Regulator ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60e6be0b-260b-4630-9d68-4c3bf9a98203",
            "sourceColumn": "Regulator ID",
            "summarizeBy": "none"
          },
          {
            "name": "RegulatorName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7b53bd6d-d4e6-4076-b703-79883b6bb321",
            "sourceColumn": "RegulatorName",
            "summarizeBy": "none"
          },
          {
            "name": "Regulator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4b9a522-7454-4eb0-8755-3b6525934a92",
            "sourceColumn": "Regulator",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f8d0672-54dc-4578-a7ed-4c0cb4052a02",
            "sourceColumn": "FiscalMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5923f90f-b364-4f62-ac33-92a1b5647f38",
            "sourceColumn": "CalendarMonth",
            "summarizeBy": "none"
          },
          {
            "name": "FacilityCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5d90f160-f0af-4bb8-b2a6-7e7a2ce4e90e",
            "sourceColumn": "FacilityCode",
            "summarizeBy": "count"
          },
          {
            "name": "FacilityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c0cef466-019d-4f78-9b6c-1d207514a803",
            "sourceColumn": "FacilityName",
            "summarizeBy": "none"
          },
          {
            "name": "Facility Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d741c1a7-8fcf-4981-9a05-684e1a10f707",
            "sourceColumn": "Facility Status",
            "summarizeBy": "none"
          },
          {
            "name": "Service Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11cbb6a5-27e1-4d66-9fda-5ad7a91fe8ad",
            "sourceColumn": "Service Status",
            "summarizeBy": "none"
          },
          {
            "name": "Service Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69e0770b-f07d-477e-9e0f-b51221a4a98f",
            "sourceColumn": "Service Type",
            "summarizeBy": "none"
          },
          {
            "name": "Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3574a14b-4c7a-4d3f-8962-abc806cdb186",
            "sourceColumn": "Area",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfd7b5a7-b5d7-400a-9f76-7b3a200a8aea",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Operations Director",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8af6a043-4503-41a7-b3be-3ffac589fe3f",
            "sourceColumn": "Operations Director",
            "summarizeBy": "none"
          },
          {
            "name": "Regional Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7425d26-4beb-4c19-8038-f3a983d570dd",
            "sourceColumn": "Regional Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Senior Service Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d690f2ce-bbc5-40a5-b5b1-b6163163f926",
            "sourceColumn": "Senior Service Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3b6eb36-789d-4b2e-b95b-a2b0879e732f",
            "sourceColumn": "Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Deputy Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44e735b7-38e7-435b-a438-85fb61385291",
            "sourceColumn": "Deputy Manager",
            "summarizeBy": "none"
          },
          {
            "name": "R1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6faf59f2-3e06-4c00-8157-e3b33f410ce8",
            "sourceColumn": "R1",
            "summarizeBy": "none"
          },
          {
            "name": "Ac",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7896a846-e05a-42f5-9c1d-4c4315943db6",
            "sourceColumn": "Ac",
            "summarizeBy": "none"
          },
          {
            "name": "Inherited_Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7fbd405d-fa64-4d62-aa74-757e87ef0cfe",
            "sourceColumn": "Inherited_Rating",
            "summarizeBy": "none"
          },
          {
            "name": "Inherited_rating_or_not_yet_rated",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "41a0f76c-bd28-4759-a4f6-8e8163c8d8e9",
            "sourceColumn": "Inherited_rating_or_not_yet_rated",
            "summarizeBy": "sum"
          },
          {
            "name": "RegisteredManager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9f55a77b-f178-4f77-9e3f-d2b27622e358",
            "sourceColumn": "RegisteredManager",
            "summarizeBy": "none"
          },
          {
            "name": "Manager_Registered_with_CQC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b078904e-c7db-4c2a-b865-681bedefd6b1",
            "sourceColumn": "Manager_Registered_with_CQC",
            "summarizeBy": "sum"
          },
          {
            "name": "CQCRatingPubdate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "513a3ac0-16c8-482b-b891-b77a8e8586d4",
            "sourceColumn": "CQCRatingPubdate",
            "summarizeBy": "none"
          },
          {
            "name": "CQCinspectionRisk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "22821518-62f4-4141-ac50-396ba07607c4",
            "sourceColumn": "CQCinspectionRisk",
            "summarizeBy": "sum"
          },
          {
            "name": "Agency_cost_pct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8d1fb896-8910-4ec1-bdc8-a4b39015d5b6",
            "sourceColumn": "Agency_cost_pct",
            "summarizeBy": "sum"
          },
          {
            "name": "Manager_SIL",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b96d2054-51bc-4621-81d3-65131dd42c95",
            "sourceColumn": "Manager_SIL",
            "summarizeBy": "none"
          },
          {
            "name": "Manager_present_at_service",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f091aaf2-7411-4d8d-beff-34c7137d9ed4",
            "sourceColumn": "Manager_present_at_service",
            "summarizeBy": "none"
          },
          {
            "name": "MGRTurnOver_Risk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7e9d3080-8d7c-4086-be06-13a1cf01903b",
            "sourceColumn": "MGRTurnOver_Risk",
            "summarizeBy": "sum"
          },
          {
            "name": "ElrngOverallComaliance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d2e76f64-4540-47b5-9945-b2f0def3b089",
            "sourceColumn": "ElrngOverallComaliance",
            "summarizeBy": "sum"
          },
          {
            "name": "InternalAuditRisk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9d887748-2938-47b4-a70b-0e09e7780b87",
            "sourceColumn": "InternalAuditRisk",
            "summarizeBy": "sum"
          },
          {
            "name": "SRATotalRisk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bea203be-5db6-451d-8d6c-0ad1660676fb",
            "sourceColumn": "SRATotalRisk",
            "summarizeBy": "sum"
          },
          {
            "name": "SURATotalRisk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e5acb69-9dff-4661-9e49-89e5a53f97bf",
            "sourceColumn": "SURATotalRisk",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalRisk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fd78adde-f83e-4e80-96a2-0c538a2c45fc",
            "sourceColumn": "TotalRisk",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarMonthNameYear_New",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm yyyy",
            "lineageTag": "971c0fb6-6b36-4fbf-8e5a-b45effd242f6",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "CalendarMonthNameYear_New",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a6b79582-a5d1-43a0-ab76-c7f902d0d17b"
                },
                "isDefault": true,
                "relationship": "f05509a6-530f-4890-9838-03ead314c00d"
              }
            ]
          },
          {
            "name": "CalendarMonthNameYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "a7e36bca-b70d-493f-8cdd-14c064dd8bfe",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "CalendarMonthNameYear",
            "summarizeBy": "none"
          },
          {
            "name": "PhotographyRisk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27e806c1-64fc-4ac7-a235-dacbd19a6b9a",
            "sourceColumn": "PhotographyRisk",
            "summarizeBy": "sum"
          },
          {
            "name": "RecruitmentRisk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ef893522-ba39-462b-9a69-a0bc47a90e99",
            "sourceColumn": "RecruitmentRisk",
            "summarizeBy": "sum"
          },
          {
            "name": "New1_CalendarMonthNameYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "672e83c9-c447-4189-b5a0-03bccbdd4411",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "New1_CalendarMonthNameYear",
            "summarizeBy": "none"
          },
          {
            "name": "New3_CalendarMonthNameYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "8edbc614-48ad-43b3-932f-1b04305e81bc",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "New3_CalendarMonthNameYear",
            "summarizeBy": "none"
          },
          {
            "name": "New4_CalendarMonthNameYear - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "3cec890f-7b95-473f-a4b8-9bf7013f7f98",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "New4_CalendarMonthNameYear - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "New5_CalendarMonthNameYear - Copy.1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2bd8c22b-da4a-46aa-97a6-73f5ff8962ce",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "New5_CalendarMonthNameYear - Copy.1",
            "summarizeBy": "none"
          },
          {
            "name": "New6_CalendarMonthNameYear - Copy.2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "03922324-d9fc-4f79-90fb-0cf2955df89d",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "New6_CalendarMonthNameYear - Copy.2",
            "summarizeBy": "none"
          },
          {
            "name": "New7_CalendarMonthNameYear - Copy.3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "653834ae-7a23-4472-ba7d-645e56564815",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "New7_CalendarMonthNameYear - Copy.3",
            "summarizeBy": "none"
          },
          {
            "name": "New_8CalendarMonthNameYear - Copy.4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "c1c8f500-8a6c-4eb2-9824-076367dd88a9",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "New_8CalendarMonthNameYear - Copy.4",
            "summarizeBy": "none"
          },
          {
            "name": "Operations Director - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7bc0dbf0-bed8-4c07-ad9b-38e02b735bf6",
            "sourceColumn": "Operations Director - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "New_9CalendarMonthNameYear - Copy.4 - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4b6b018-91ae-4365-bde4-f85413495921",
            "sourceColumn": "New_9CalendarMonthNameYear - Copy.4 - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "New_10CalendarMonthNameYear - Copy.4 - Copy - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfc4151e-a9c5-4aff-8efe-d3ede4f60d4f",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "New_10CalendarMonthNameYear - Copy.4 - Copy - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fe5405f6-369c-41e7-953f-de19daddee99",
            "sourceColumn": "Head_Of_Operations",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d861a060-5171-4423-b730-5d2dedfbf693",
            "sourceColumn": "Head_Of_Operations - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "RegionalMGR_Risk",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78176813-7034-47e1-bc6e-c4d804d3b493",
            "sourceColumn": "RegionalMGR_Risk",
            "summarizeBy": "sum"
          },
          {
            "name": "New_11CalendarMonthNameYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60ad13b4-0a41-4c9c-b3b4-344eb7bad33f",
            "sourceColumn": "New_11CalendarMonthNameYear",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarMonthName_REgnional Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "6accd84b-586d-4cdc-84ad-7934287649be",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "CalendarMonthName_REgnional Manager",
            "summarizeBy": "none"
          },
          {
            "name": "CQC Inspection",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(ServiceRiskAnalysisCombined[CQCinspectionRisk]in{3,4},\"CQC Inspection\")",
            "isDataTypeInferred": true,
            "lineageTag": "7691a294-3b32-45de-b9e2-77f641f7f325",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Training Compliance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(ServiceRiskAnalysisCombined[ElrngOverallComaliance]=3,\"Training Compliance\")",
            "isDataTypeInferred": true,
            "lineageTag": "ffb03044-e7c9-4acc-889c-3d1958cf6041",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Internal Audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(ServiceRiskAnalysisCombined[InternalAuditRisk]=3,\"Internal Audit\")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "be40ac63-5980-439d-96fc-10ab89343a59",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Manger Vacancies",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(ServiceRiskAnalysisCombined[Manager_present_at_service]=3,\"Manager vacancies\")",
            "isDataTypeInferred": true,
            "lineageTag": "2a28bb53-2462-4e9f-89a3-3769b3380755",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CQC Manager Registered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]=3,\"CQC Manager Registered\")",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "f98da0a4-b4ef-4f1f-bc19-20a9ccd6677f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "TEam Member Attrition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(ServiceRiskAnalysisCombined[MGRTurnOver_Risk]=3,\"Team Member Attrition\")",
            "isDataTypeInferred": true,
            "lineageTag": "7f4a124d-b0cc-4753-b590-ecd81a154698",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Agency Cost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(ServiceRiskAnalysisCombined[Agency_cost_pct]=3,\"Agency Cost\")",
            "isDataTypeInferred": true,
            "lineageTag": "a5529bb2-d6dd-4e96-a756-d4f2fb671e81",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "CalendarMonthNameYear_Trend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbee1a2b-dcb5-4255-a59d-a11718663bcc",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "CalendarMonthNameYear_Trend",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations - CQCInspection",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "963259f3-8279-4c55-b44f-fcbe19936c9e",
            "sourceColumn": "Head_Of_Operations - CQCInspection",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations - Internal Audit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48f499ec-f2a9-4c97-8d0a-811ff85d1692",
            "sourceColumn": "Head_Of_Operations - Internal Audit",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations -Regional Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e0302ed-f59b-48a5-bd30-98f875c6b504",
            "sourceColumn": "Head_Of_Operations -Regional Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations - Recruitment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61da3189-a2ca-41c7-839b-7593bd0741d3",
            "sourceColumn": "Head_Of_Operations - Recruitment",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations -CQC Registered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "80bb594e-e0f1-46f2-bc0c-f2e9cb6d133e",
            "sourceColumn": "Head_Of_Operations -CQC Registered",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations -Manager Vacancies",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "006399d2-3fad-40bc-9cc4-7c34bd53d99b",
            "sourceColumn": "Head_Of_Operations -Manager Vacancies",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations -Training Compliance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f54b9fd7-b6be-460e-b3d1-dd8d02a29777",
            "sourceColumn": "Head_Of_Operations -Training Compliance",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations -Team Member",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d28a1d4-e619-44d1-a27a-ea903f2c60a1",
            "sourceColumn": "Head_Of_Operations -Team Member",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations -Agency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3d37c0e-ac7e-467c-9175-81dac940ebc3",
            "sourceColumn": "Head_Of_Operations -Agency",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarMonthNameYear-Trend",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ccf08ab-7f78-4c69-a630-fd785871bae9",
            "sortByColumn": "CalendarMonth",
            "sourceColumn": "CalendarMonthNameYear-Trend",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations -Previous",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f955628-a05e-4123-a78d-d2ae09a6d98e",
            "sourceColumn": "Head_Of_Operations -Previous",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "    VALUE(LEFT([CalendarMonth], 4)),",
              "    VALUE(RIGHT([CalendarMonth], 2)),",
              "    1",
              ")",
              ""
            ],
            "formatString": "mmmm yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "d655d2ef-4e0e-475b-9a0b-833997fcf387",
            "sortByColumn": "Calendar Year",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_40459186-9a00-4d17-87f1-129b9e044325"
                },
                "isDefault": true,
                "relationship": "b3a87a1f-c91c-44d3-95d4-f0835da6e0d5"
              }
            ]
          },
          {
            "name": "CalendarMonthNameYear_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(LEFT(ServiceRiskAnalysisCombined[CalendarMonthNameYear],3),\" \"),RIGHT(ServiceRiskAnalysisCombined[CalendarMonthNameYear],4))",
            "isDataTypeInferred": true,
            "lineageTag": "11d27c41-d08d-49d5-99bd-e853ae5e9a37",
            "sortByColumn": "CalendarMonth",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Hashkey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(ServiceRiskAnalysisCombined[FacilityCode],ServiceRiskAnalysisCombined[ServIceName]),ServiceRiskAnalysisCombined[FiscalMonth])",
            "isDataTypeInferred": true,
            "lineageTag": "accf96bd-733d-408a-bba0-7a424282bce1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Service Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "244c2c21-22b9-4546-9f92-f3d4c33fbb77",
            "sourceColumn": "Service Name",
            "summarizeBy": "none"
          },
          {
            "name": "ServIceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "SUBSTITUTE('ServiceRiskAnalysisCombined'[FacilityName], \" \", \"\")",
            "isDataTypeInferred": true,
            "lineageTag": "748fb988-66b5-4559-9c8a-b9dfd8963977",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Calendar Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "string",
            "expression": "LEFT(ServiceRiskAnalysisCombined[CalendarMonth],4)",
            "isDataTypeInferred": true,
            "lineageTag": "a3d5e016-ffbe-4fea-b7a7-e74c183df712",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "F2FOverallComaliance",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "925520bb-d4c2-4870-b70e-2729f894aecf",
            "sourceColumn": "F2FOverallComaliance",
            "summarizeBy": "sum"
          },
          {
            "name": "HOA Revised",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Kate Durband\",\"Reporting\",ServiceRiskAnalysisCombined[Head_Of_Operations])",
            "isDataTypeInferred": true,
            "lineageTag": "d3bd38a7-606c-42d6-b846-da5ff38c3f37",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "High Risk Grouping",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF(ServiceRiskAnalysisCombined[CQCinspectionRisk]>2,1,0)+IF(ServiceRiskAnalysisCombined[RecruitmentRisk]>2,1,0)+IF(ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]>2,1,0)+IF(ServiceRiskAnalysisCombined[F2FOverallComaliance]>2,1,0)+IF(ServiceRiskAnalysisCombined[InternalAuditRisk]>2,1,0)+IF(ServiceRiskAnalysisCombined[Manager_present_at_service]>2,1,0)+IF(ServiceRiskAnalysisCombined[RegionalMGR_Risk]>2,1,0)+IF(ServiceRiskAnalysisCombined[Agency_cost_pct]>2,1,0)+IF(ServiceRiskAnalysisCombined[ElrngOverallComaliance]>2,1,0)+IF(ServiceRiskAnalysisCombined[MGRTurnOver_Risk]>2,1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "605a5481-6e2c-477a-9fc9-5d767c0b0d59",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Moderate Risk Grouping",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF(ServiceRiskAnalysisCombined[CQCinspectionRisk]=2,1,0)+IF(ServiceRiskAnalysisCombined[RecruitmentRisk]=2,1,0)+IF(ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]=2,1,0)+IF(ServiceRiskAnalysisCombined[F2FOverallComaliance]=2,1,0)+IF(ServiceRiskAnalysisCombined[InternalAuditRisk]=2,1,0)+IF(ServiceRiskAnalysisCombined[Manager_present_at_service]=2,1,0)+IF(ServiceRiskAnalysisCombined[RegionalMGR_Risk]=2,1,0)+IF(ServiceRiskAnalysisCombined[Agency_cost_pct]=2,1,0)+IF(ServiceRiskAnalysisCombined[ElrngOverallComaliance]=2,1,0)+IF(ServiceRiskAnalysisCombined[MGRTurnOver_Risk]=2,1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "1e8abe2c-e46f-47b7-96c8-1979a7d72ed9",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Current Month Slicer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    IF(",
              "    MONTH('ServiceRiskAnalysisCombined'[CalendarMonthNameYear_New]) = MONTH(TODAY()) && YEAR('ServiceRiskAnalysisCombined'[CalendarMonthNameYear_New]) = YEAR(TODAY()),",
              "    \"Current Month\",",
              "    //FORMAT('SnapshotRiskbytype'[Date], \"MMMM YYYY\")",
              "    FORMAT('ServiceRiskAnalysisCombined'[CalendarMonthNameYear_New],\"MMMM YYYY\")",
              "",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "5b1642a5-1904-4a7c-8203-80ec253bce93",
            "sortByColumn": "CalendarMonth",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Previous Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": [
              "IF(",
              "    MONTH('ServiceRiskAnalysisCombined'[CalendarMonthNameYear_New]) = MONTH(TODAY())-1 && YEAR('ServiceRiskAnalysisCombined'[CalendarMonthNameYear_New]) = YEAR(TODAY()),",
              "    1,",
              "    0)"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a3d56fa6-0e53-4e8d-a3eb-4ce38b811c19",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "fbc5dd93-247e-420c-b840-b5184dd73663",
        "measures": [
          {
            "name": "Rtest",
            "expression": "CALCULATE(COUNT(ServiceRiskAnalysisCombined[Recruitment]))",
            "formatString": "0",
            "lineageTag": "e98b51b4-4051-4445-951e-ac28e226b071"
          },
          {
            "name": "Test Measure",
            "expression": "IF(SELECTEDVALUE(DimTEst[New table]) = \"CQC Inspection\", [LatestCQCInspection_MEASURE],[LatestInternalAudit_MEASURE])",
            "formatString": "0",
            "lineageTag": "4877d1e1-69a1-46ef-8b21-8cf0d95b3279"
          },
          {
            "name": "cateogory",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "IF(SELECTEDVALUE('Category_PBI'[Categories]) = \"CQC Inspection\", [LatestCQCInspection_MEASURE],",
              " IF(SELECTEDVALUE('Category_PBI'[Categories]) = \"Internal Audit\", [LatestInternalAudit_MEASURE],",
              " IF(SELECTEDVALUE('Category_PBI'[Categories]) = \"CQC Manager Registered\", [MRwithCQC_Measure],",
              "IF(SELECTEDVALUE('Category_PBI'[Categories]) = \"Manager Vacancies\", [ManagerVacancies_MEASURE],",
              " IF(SELECTEDVALUE('Category_PBI'[Categories]) = \"Regional Manager\", [R3_Regnional Manager],",
              " IF(SELECTEDVALUE('Category_PBI'[Categories]) = \"Team Member Attrition\", [TeamMemberAttri_MEASURE],",
              " IF(SELECTEDVALUE('Category_PBI'[Categories]) = \"Training Compliance\", [TrainingCompliance_MEASURE],",
              " IF(SELECTEDVALUE('Category_PBI'[Categories]) = \"Agency Cost\", [ACP_MEASURE],[Recruitment]))))))))"
            ],
            "formatString": "0",
            "lineageTag": "526df6d3-6c5d-40d3-a547-4cc6bd00d401"
          },
          {
            "name": "Max CombinedScore",
            "expression": "MAX(ServiceRiskAnalysisCombined[TotalRisk])",
            "formatString": "0",
            "lineageTag": "4f312c73-0c05-4ba2-b622-69529cb046e7"
          }
        ],
        "partitions": [
          {
            "name": "ServiceRiskAnalysisCombined-1017eacf-92c6-4b3b-9a07-39b9ce180bb4",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\"),",
                "    ATDMP = Source{[Name=\"ATDMP\"]}[Data],",
                "    dbo_ServiceRiskAnalysisCombined = ATDMP{[Schema=\"dbo\",Item=\"ServiceRiskAnalysisCombined\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_ServiceRiskAnalysisCombined,{{\"UniqueRecord\", type text}}),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Changed Type\", \"CalendarMonthNameYear\", \"CalendarMonthNameYear - Copy\"),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Duplicated Column\",{{\"CalendarMonthNameYear\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type1\",{{\"CalendarMonthNameYear\", \"CalendarMonthNameYear_New\"}, {\"CalendarMonthNameYear - Copy\", \"CalendarMonthNameYear\"}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Renamed Columns\", each true),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Filtered Rows\", \"CalendarMonthNameYear\", \"CalendarMonthNameYear - Copy\"),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Duplicated Column1\",{{\"CalendarMonthNameYear - Copy\", \"CalendarMonthNameYear_Internal\"}}),",
                "    #\"Duplicated Column2\" = Table.DuplicateColumn(#\"Renamed Columns1\", \"CalendarMonthNameYear_Internal\", \"CalendarMonthNameYear_Internal - Copy\"),",
                "    #\"Duplicated Column3\" = Table.DuplicateColumn(#\"Duplicated Column2\", \"CalendarMonthNameYear\", \"CalendarMonthNameYear - Copy\"),",
                "    #\"Duplicated Column4\" = Table.DuplicateColumn(#\"Duplicated Column3\", \"CalendarMonthNameYear\", \"CalendarMonthNameYear - Copy.1\"),",
                "    #\"Duplicated Column5\" = Table.DuplicateColumn(#\"Duplicated Column4\", \"CalendarMonthNameYear\", \"CalendarMonthNameYear - Copy.2\"),",
                "    #\"Duplicated Column6\" = Table.DuplicateColumn(#\"Duplicated Column5\", \"CalendarMonthNameYear\", \"CalendarMonthNameYear - Copy.3\"),",
                "    #\"Duplicated Column7\" = Table.DuplicateColumn(#\"Duplicated Column6\", \"CalendarMonthNameYear\", \"CalendarMonthNameYear - Copy.4\"),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Duplicated Column7\",{{\"CalendarMonthNameYear_Internal - Copy\", \"New3_CalendarMonthNameYear\"}, {\"CalendarMonthNameYear_Internal\", \"New1_CalendarMonthNameYear\"}, {\"CalendarMonthNameYear - Copy\", \"New4_CalendarMonthNameYear - Copy\"}, {\"CalendarMonthNameYear - Copy.1\", \"New5_CalendarMonthNameYear - Copy.1\"}, {\"CalendarMonthNameYear - Copy.2\", \"New6_CalendarMonthNameYear - Copy.2\"}, {\"CalendarMonthNameYear - Copy.3\", \"New7_CalendarMonthNameYear - Copy.3\"}, {\"CalendarMonthNameYear - Copy.4\", \"New_8CalendarMonthNameYear - Copy.4\"}}),",
                "    #\"Duplicated Column8\" = Table.DuplicateColumn(#\"Renamed Columns2\", \"New_8CalendarMonthNameYear - Copy.4\", \"New_8CalendarMonthNameYear - Copy.4 - Copy\"),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Duplicated Column8\",{{\"New_8CalendarMonthNameYear - Copy.4 - Copy\", \"New_9CalendarMonthNameYear - Copy.4 - Copy\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns3\",{\"New_9CalendarMonthNameYear - Copy.4 - Copy\"}),",
                "    #\"Duplicated Column9\" = Table.DuplicateColumn(#\"Removed Columns\", \"Operations Director\", \"Operations Director - Copy\"),",
                "    #\"Duplicated Column10\" = Table.DuplicateColumn(#\"Duplicated Column9\", \"New_8CalendarMonthNameYear - Copy.4\", \"New_8CalendarMonthNameYear - Copy.4 - Copy\"),",
                "    #\"Duplicated Column11\" = Table.DuplicateColumn(#\"Duplicated Column10\", \"New_8CalendarMonthNameYear - Copy.4 - Copy\", \"New_8CalendarMonthNameYear - Copy.4 - Copy - Copy\"),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Duplicated Column11\",{{\"New_8CalendarMonthNameYear - Copy.4 - Copy\", \"New_9CalendarMonthNameYear - Copy.4 - Copy\"}, {\"New_8CalendarMonthNameYear - Copy.4 - Copy - Copy\", \"New_10CalendarMonthNameYear - Copy.4 - Copy - Copy\"}}),",
                "    #\"Duplicated Column12\" = Table.DuplicateColumn(#\"Renamed Columns4\", \"Head_Of_Operations\", \"Head_Of_Operations - Copy\"),",
                "    #\"Duplicated Column13\" = Table.DuplicateColumn(#\"Duplicated Column12\", \"New_10CalendarMonthNameYear - Copy.4 - Copy - Copy\", \"New_10CalendarMonthNameYear - Copy.4 - Copy - Copy - Copy\"),",
                "    #\"Renamed Columns5\" = Table.RenameColumns(#\"Duplicated Column13\",{{\"New_10CalendarMonthNameYear - Copy.4 - Copy - Copy - Copy\", \"New_11CalendarMonthNameYear\"}}),",
                "    #\"Duplicated Column14\" = Table.DuplicateColumn(#\"Renamed Columns5\", \"New_11CalendarMonthNameYear\", \"New_11CalendarMonthNameYear - Copy\"),",
                "    #\"Renamed Columns6\" = Table.RenameColumns(#\"Duplicated Column14\",{{\"New_11CalendarMonthNameYear - Copy\", \"CalendarMonthName_REgnional Manager\"}}),",
                "    #\"Duplicated Column15\" = Table.DuplicateColumn(#\"Renamed Columns6\", \"CalendarMonthNameYear\", \"CalendarMonthNameYear - Copy\"),",
                "    #\"Renamed Columns7\" = Table.RenameColumns(#\"Duplicated Column15\",{{\"CalendarMonthNameYear - Copy\", \"CalendarMonthNameYear_Trend\"}}),",
                "    #\"Duplicated Column16\" = Table.DuplicateColumn(#\"Renamed Columns7\", \"CalendarMonthNameYear_Trend\", \"CalendarMonthNameYear_Trend - Copy\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Duplicated Column16\",{\"CalendarMonthNameYear_Trend - Copy\"}),",
                "    #\"Duplicated Column17\" = Table.DuplicateColumn(#\"Removed Columns1\", \"Head_Of_Operations\", \"Head_Of_Operations - Copy.1\"),",
                "    #\"Duplicated Column18\" = Table.DuplicateColumn(#\"Duplicated Column17\", \"Head_Of_Operations - Copy.1\", \"Head_Of_Operations - Copy.1 - Copy\"),",
                "    #\"Duplicated Column19\" = Table.DuplicateColumn(#\"Duplicated Column18\", \"Head_Of_Operations - Copy.1 - Copy\", \"Head_Of_Operations - Copy.1 - Copy - Copy\"),",
                "    #\"Duplicated Column20\" = Table.DuplicateColumn(#\"Duplicated Column19\", \"Head_Of_Operations - Copy.1 - Copy - Copy\", \"Head_Of_Operations - Copy.1 - Copy - Copy - Copy\"),",
                "    #\"Renamed Columns8\" = Table.RenameColumns(#\"Duplicated Column20\",{{\"Head_Of_Operations - Copy.1\", \"Head_Of_Operations - CQCInspection\"}, {\"Head_Of_Operations - Copy.1 - Copy\", \"Head_Of_Operations - Internal Audit\"}, {\"Head_Of_Operations - Copy.1 - Copy - Copy\", \"Head_Of_Operations -Regional Manager\"}, {\"Head_Of_Operations - Copy.1 - Copy - Copy - Copy\", \"Head_Of_Operations - Recruitment\"}}),",
                "    #\"Duplicated Column21\" = Table.DuplicateColumn(#\"Renamed Columns8\", \"Head_Of_Operations - Recruitment\", \"Head_Of_Operations - Recruitment - Copy\"),",
                "    #\"Renamed Columns9\" = Table.RenameColumns(#\"Duplicated Column21\",{{\"Head_Of_Operations - Recruitment - Copy\", \"Head_Of_Operations -CQC Registered\"}}),",
                "    #\"Duplicated Column22\" = Table.DuplicateColumn(#\"Renamed Columns9\", \"Head_Of_Operations -CQC Registered\", \"Head_Of_Operations -CQC Registered - Copy\"),",
                "    #\"Renamed Columns10\" = Table.RenameColumns(#\"Duplicated Column22\",{{\"Head_Of_Operations -CQC Registered - Copy\", \"Head_Of_Operations -Manager Vacancies\"}}),",
                "    #\"Duplicated Column23\" = Table.DuplicateColumn(#\"Renamed Columns10\", \"Head_Of_Operations -Manager Vacancies\", \"Head_Of_Operations -Manager Vacancies - Copy\"),",
                "    #\"Renamed Columns11\" = Table.RenameColumns(#\"Duplicated Column23\",{{\"Head_Of_Operations -Manager Vacancies - Copy\", \"Head_Of_Operations -Training Compliance\"}}),",
                "    #\"Duplicated Column24\" = Table.DuplicateColumn(#\"Renamed Columns11\", \"Head_Of_Operations -Training Compliance\", \"Head_Of_Operations -Training Compliance - Copy\"),",
                "    #\"Renamed Columns12\" = Table.RenameColumns(#\"Duplicated Column24\",{{\"Head_Of_Operations -Training Compliance - Copy\", \"Head_Of_Operations -Team Member\"}}),",
                "    #\"Duplicated Column25\" = Table.DuplicateColumn(#\"Renamed Columns12\", \"Head_Of_Operations -Team Member\", \"Head_Of_Operations -Team Member - Copy\"),",
                "    #\"Renamed Columns13\" = Table.RenameColumns(#\"Duplicated Column25\",{{\"Head_Of_Operations -Team Member - Copy\", \"Head_Of_Operations -Agency\"}}),",
                "    #\"Duplicated Column26\" = Table.DuplicateColumn(#\"Renamed Columns13\", \"CalendarMonthNameYear_Trend\", \"CalendarMonthNameYear_Trend - Copy\"),",
                "    #\"Renamed Columns14\" = Table.RenameColumns(#\"Duplicated Column26\",{{\"CalendarMonthNameYear_Trend - Copy\", \"CalendarMonthNameYear-Trend\"}}),",
                "    #\"Duplicated Column27\" = Table.DuplicateColumn(#\"Renamed Columns14\", \"Head_Of_Operations -Agency\", \"Head_Of_Operations -Agency - Copy\"),",
                "    #\"Renamed Columns15\" = Table.RenameColumns(#\"Duplicated Column27\",{{\"Head_Of_Operations -Agency - Copy\", \"Head_Of_Operations -Previous\"}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Renamed Columns15\",\"holly mceneaney\",\"TCB\",Replacer.ReplaceText,{\"Regional Manager\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Regional Manager\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations - Copy\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations - CQCInspection\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations - Internal Audit\"}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Replaced Value5\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations -Regional Manager\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations - Recruitment\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations -CQC Registered\"}),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Replaced Value8\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations -Manager Vacancies\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations -Training Compliance\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations -Team Member\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"Holly Mceneaney\",\"TBCX\",Replacer.ReplaceText,{\"Head_Of_Operations -Agency\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations -Previous\"}),",
                "    #\"Duplicated Column28\" = Table.DuplicateColumn(#\"Replaced Value13\", \"FacilityName\", \"FacilityName - Copy\"),",
                "    #\"Renamed Columns16\" = Table.RenameColumns(#\"Duplicated Column28\",{{\"FacilityName - Copy\", \"Service Name\"}})",
                "in",
                "    #\"Renamed Columns16\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "All Summary Measures",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "44083f06-daf6-4216-be00-c20a1b63a18e",
        "measures": [
          {
            "name": "CombinedRisk_sum",
            "expression": "'All Measure'[ACP_MEASURE] +  'All Measure'[ManagerVacancies_MEASURE] + 'All Measure'[TrainingCompliance_MEASURE]  + 'All Measure'[TeamMemberAttri_MEASURE] + 'All Measure'[IRNYRated_Measure] + 'All Measure'[MRwithCQC_Measure] + 'All Measure'[LatestInternalAudit_MEASURE] + 'All Measure'[LatestCQCInspection_MEASURE]+'All Measure'[Recruitment]+'All Measure'[R3_Regnional Manager]",
            "formatString": "0",
            "lineageTag": "70830b5c-bb57-4dc8-9652-9b45bc6e5760"
          },
          {
            "name": "InternalAudit_Dean",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a= CALCULATE(COUNT(ServiceRiskAnalysisCombined[FacilityCode]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Dean Thomas-Bines\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "7e70c561-472a-4bd6-8e89-c41b460e0697"
          },
          {
            "name": "InternalAudit_Joanna",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[InternalAuditRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Joanna Mcnally\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "75bc0c8a-3652-4033-a923-06dd989525ef"
          },
          {
            "name": "InternalAudit_Kate",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[InternalAuditRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Kate Durband\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "14a013a4-2651-4bd0-90db-147c9da76954"
          },
          {
            "name": "InternalAudit_Matt",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[InternalAuditRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Matt Davis\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e0cc4373-f1c8-438d-a1e5-fdeaf1880c67"
          },
          {
            "name": "InternalAudit_Racheal",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[InternalAuditRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rachael Hawkins\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "b8fad0c3-8962-4caf-a99e-60ea59a3b485"
          },
          {
            "name": "InternalAudit_Rebecca",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[InternalAuditRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rebecca Dunning\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fb6cd422-f298-42c9-a1b7-de00524dde61"
          },
          {
            "name": "InternalAudit_Sharon",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[InternalAuditRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[InternalAuditRisk] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Sharon Ford\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "77786e68-6766-4e6a-8f1a-1667e42a0b44"
          },
          {
            "name": "MR_Matt",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_Registered_with_CQC]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Matt Davis\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "3c460a85-7b14-4cb6-9715-84a4e1603ef6"
          },
          {
            "name": "MR_Racheal",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_Registered_with_CQC]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rachael Hawkins\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "e7e78098-0380-445c-a57c-c5b304b9ad2c"
          },
          {
            "name": "MR_Rebecca",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_Registered_with_CQC]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rebecca Dunning\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c2ae59e6-84ba-4973-810e-9a4d1d68c0ee"
          },
          {
            "name": "MR_Sharon",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_Registered_with_CQC]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] =3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Sharon Ford\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "Return DIVIDE(a,b)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "580a6ca2-2f42-4dec-94be-befc157ffe83"
          },
          {
            "name": "Overall_RegionalMan",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RegionalMGR_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RegionalMGR_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Dean Thomas-Bines\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "return DIVIDE(a,b)",
              "+",
              "var c=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RegionalMGR_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RegionalMGR_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Holly Mceneaney\")",
              "",
              "return DIVIDE(c,b)",
              "+",
              "var d=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RegionalMGR_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RegionalMGR_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Joanna Mcnally\")",
              "",
              "return DIVIDE(d,b)",
              "+",
              "var e=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RegionalMGR_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RegionalMGR_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Sharon Ford\")",
              "",
              "return DIVIDE(e,b)+",
              "var f=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RegionalMGR_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RegionalMGR_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Kate Durband\")",
              "",
              "return DIVIDE(f,b)+",
              "var g=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RegionalMGR_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RegionalMGR_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Matt Davis\")",
              "",
              "return DIVIDE(g,b)+",
              "var h=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RegionalMGR_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RegionalMGR_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rachael Hawkins\")",
              "",
              "return DIVIDE(h,b)+",
              "var i=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RegionalMGR_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RegionalMGR_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rebecca Dunning\")",
              "",
              "return DIVIDE(i,b)",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "31e7947c-1787-49e0-a08a-47dc8d71c4e7"
          },
          {
            "name": "ManagerVac_Prev",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Overall_Managervac],PREVIOUSMONTH(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]))",
            "lineageTag": "836b6b49-778c-4494-a6b9-83e666bc6daf"
          },
          {
            "name": "ManagerVac_Colour",
            "expression": "IF([Overall_Managervac]>[ManagerVac_Prev],\"#FD625E\",\"#00B810\")",
            "lineageTag": "1c1f9a6c-a933-485f-9abf-a756dd0ef2f4"
          },
          {
            "name": "REgional_previous",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Overall_RegionalMan],PREVIOUSMONTH(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]))",
            "lineageTag": "78ae368a-3767-426a-9bbd-a6957af70ef6"
          },
          {
            "name": "RegiionalManager_Colour",
            "expression": "IF([Overall_RegionalMan]>[REgional_previous],\"#FD625E\",\"#00B810\")",
            "lineageTag": "edf2d04f-0349-44b6-93dd-708f9cd6604c"
          },
          {
            "name": "Overall_TeamMember",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[MGRTurnOver_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Dean Thomas-Bines\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "return DIVIDE(a,b)",
              "+",
              "var c=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[MGRTurnOver_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Holly Mceneaney\")",
              "",
              "return DIVIDE(c,b)",
              "+",
              "var d=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[MGRTurnOver_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Joanna Mcnally\")",
              "",
              "return DIVIDE(d,b)",
              "+",
              "var e=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[MGRTurnOver_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Sharon Ford\")",
              "",
              "return DIVIDE(e,b)+",
              "var f=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[MGRTurnOver_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Kate Durband\")",
              "",
              "return DIVIDE(f,b)+",
              "var g=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[MGRTurnOver_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Matt Davis\")",
              "",
              "return DIVIDE(g,b)+",
              "var h=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[MGRTurnOver_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rachael Hawkins\")",
              "",
              "return DIVIDE(h,b)+",
              "var i=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[MGRTurnOver_Risk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[MGRTurnOver_Risk] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rebecca Dunning\")",
              "",
              "return DIVIDE(i,b)",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "42bb295b-1bec-40fb-8d6f-82d9329d97a4"
          },
          {
            "name": "TeamMember_Previ",
            "expression": "CALCULATE([Overall_TeamMember],PREVIOUSMONTH(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]))",
            "formatString": "0",
            "lineageTag": "a55689ca-8f3d-474e-8802-f578a7e899e2"
          },
          {
            "name": "TeamMember_Colour",
            "expression": "IF([Overall_TeamMember]>[TeamMember_Previ],\"#FD625E\",\"#00B810\")",
            "lineageTag": "df8206f2-d099-4d5f-bc26-3edc0007424f"
          },
          {
            "name": "Overall_Trainingcompliance",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[ElrngOverallComaliance]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Dean Thomas-Bines\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "return DIVIDE(a,b)",
              "+",
              "var c=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[ElrngOverallComaliance]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Holly Mceneaney\")",
              "",
              "return DIVIDE(c,b)",
              "+",
              "var d=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[ElrngOverallComaliance]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Joanna Mcnally\")",
              "",
              "return DIVIDE(d,b)",
              "+",
              "var e=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[ElrngOverallComaliance]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Sharon Ford\")",
              "",
              "return DIVIDE(e,b)+",
              "var f=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[ElrngOverallComaliance]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Kate Durband\")",
              "",
              "return DIVIDE(f,b)+",
              "var g=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[ElrngOverallComaliance]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Matt Davis\")",
              "",
              "return DIVIDE(g,b)+",
              "var h=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[ElrngOverallComaliance]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rachael Hawkins\")",
              "",
              "return DIVIDE(h,b)+",
              "var i=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[ElrngOverallComaliance]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[ElrngOverallComaliance] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rebecca Dunning\")",
              "",
              "return DIVIDE(i,b)",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c35488d8-9af8-4a2f-aedf-acd738cd4cf3"
          },
          {
            "name": "Training_previous",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Overall_Trainingcompliance],PREVIOUSMONTH(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]))",
            "lineageTag": "40b02cab-fdb1-4c0d-a28f-49487549d62f"
          },
          {
            "name": "Training_Colour",
            "expression": "IF([Overall_Trainingcompliance]>[Training_previous],\"#FD625E\",\"#00B810\")",
            "lineageTag": "27b8bb8d-db52-4575-b7ac-5facd7df17fc"
          },
          {
            "name": "Overall_Agency",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Agency_cost_pct]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Dean Thomas-Bines\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "return DIVIDE(a,b)",
              "+",
              "var c=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Agency_cost_pct]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Holly Mceneaney\")",
              "",
              "return DIVIDE(c,b)",
              "+",
              "var d=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Agency_cost_pct]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Joanna Mcnally\")",
              "",
              "return DIVIDE(d,b)",
              "+",
              "var e=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Agency_cost_pct]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Sharon Ford\")",
              "",
              "return DIVIDE(e,b)+",
              "var f=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Agency_cost_pct]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Kate Durband\")",
              "",
              "return DIVIDE(f,b)+",
              "var g=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Agency_cost_pct]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Matt Davis\")",
              "",
              "return DIVIDE(g,b)+",
              "var h=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Agency_cost_pct]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rachael Hawkins\")",
              "",
              "return DIVIDE(h,b)+",
              "var i=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Agency_cost_pct]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Agency_cost_pct] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rebecca Dunning\")",
              "",
              "return DIVIDE(i,b)",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "d4716de8-ee12-46bf-9257-f91f6ce66977"
          },
          {
            "name": "Overall_Recruitment",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RecruitmentRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk] in {3,4}),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Dean Thomas-Bines\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "return DIVIDE(a,b)",
              "+",
              "var c=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RecruitmentRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk] in {3,4}),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Holly Mceneaney\")",
              "",
              "return DIVIDE(c,b)",
              "+",
              "var d=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RecruitmentRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk]  in {3,4}),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Joanna Mcnally\")",
              "",
              "return DIVIDE(d,b)",
              "+",
              "var e=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RecruitmentRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk]  in {3,4}),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Sharon Ford\")",
              "",
              "return DIVIDE(e,b)+",
              "var f=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RecruitmentRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk]  in {3,4}),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Kate Durband\")",
              "",
              "return DIVIDE(f,b)+",
              "var g=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RecruitmentRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk]  in {3,4}),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Matt Davis\")",
              "",
              "return DIVIDE(g,b)+",
              "var h=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RecruitmentRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk] in {3,4}),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rachael Hawkins\")",
              "",
              "return DIVIDE(h,b)+",
              "var i=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[RecruitmentRisk]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[RecruitmentRisk]  in {3,4}),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rebecca Dunning\")",
              "",
              "return DIVIDE(i,b)",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "56f8d4fa-3bbf-449c-842a-47b59217859e"
          },
          {
            "name": "agency_previous",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE([Overall_Agency],PREVIOUSMONTH(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "f1d83355-2a38-4442-b59b-9e3317c0a6bd"
          },
          {
            "name": "Recruitment_previous",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([Overall_Recruitment],PREVIOUSMONTH(ServiceRiskAnalysisCombined[CalendarMonthNameYear_New]))",
            "lineageTag": "6f608f62-24d6-4299-b784-57a686e1da89"
          },
          {
            "name": "Overall_Managervac",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_present_at_service]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Dean Thomas-Bines\")",
              "",
              "VAr b= [CombinedRisk]",
              "",
              "return DIVIDE(a,b)",
              "+",
              "var c=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_present_at_service]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Holly Mceneaney\")",
              "",
              "return DIVIDE(c,b)",
              "+",
              "var d=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_present_at_service]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations - Copy]=\"Joanna Mcnally\")",
              "",
              "return DIVIDE(d,b)",
              "+",
              "var e=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_present_at_service]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Sharon Ford\")",
              "",
              "return DIVIDE(e,b)+",
              "var f=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_present_at_service]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Kate Durband\")",
              "",
              "return DIVIDE(f,b)+",
              "var g=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_present_at_service]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Matt Davis\")",
              "",
              "return DIVIDE(g,b)+",
              "var h=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_present_at_service]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rachael Hawkins\")",
              "",
              "return DIVIDE(h,b)+",
              "var i=CALCULATE(COUNT('ServiceRiskAnalysisCombined'[Manager_present_at_service]), FILTER(ServiceRiskAnalysisCombined, ServiceRiskAnalysisCombined[Manager_present_at_service] = 3),ServiceRiskAnalysisCombined[Head_Of_Operations]=\"Rebecca Dunning\")",
              "",
              "return DIVIDE(i,b)",
              "",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "c6676e42-cb32-4f74-ba8d-eca7fb4ed102"
          },
          {
            "name": "PreviousweekCategory",
            "expression": [
              "--var a = CALCULATE([TotalCategory],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "--var a=calCULATE([TotalCategory],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "",
              "--var b = calCULATE([TotalCategory],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear]))",
              "",
              "",
              "--return ",
              "--if(TODAY()=MAX(SnapshotRiskbytype[CalendarMonthNameYear]),b,a)",
              "",
              " [Manager vac Last week]+[Internal Audit last week]+[Recruitment Last week]+[Regional Mnager Last week]+[Team Member last week]+[CQC Inspection Risk last week]+[CQC REg Last week]+[Agency Cost Risk_LastWeek]+[F2f Last week]+[ELearning Last week]"
            ],
            "formatString": "0",
            "lineageTag": "a43c9740-957b-42b6-8165-4008e14e38ad"
          },
          {
            "name": "Recuritment",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"),filter(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] in {3,4}),SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))",
            "formatString": "0",
            "lineageTag": "34e6d1f7-b34c-493d-9570-31fcf424c8c9"
          },
          {
            "name": "Agency Cost Risk",
            "expression": [
              "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"),filter(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] = 3),SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9ee310e4-16bb-48cf-8442-764269bc91a4"
          },
          {
            "name": "CQCInspectionRisk",
            "expression": [
              "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,",
              "SnapshotRiskbytype[SOURCE - Drill Through]=\"CQC Inspection Risk\"),filter(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue]in {3,4}),SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))"
            ],
            "formatString": "0",
            "lineageTag": "1c85a65f-72c1-4d88-920b-2ce7963904f2"
          },
          {
            "name": "CQC Registered Manager Risk",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Regd Mgr Risk\"),filter(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] =3),SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))",
            "formatString": "0",
            "lineageTag": "06101e88-be80-45ac-8844-7d0bb7f08ebb"
          },
          {
            "name": "InternalAuditRisk",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"),filter(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] =3),SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))",
            "formatString": "0",
            "lineageTag": "2125dd7c-14b4-421e-84dc-c382ff9d096e"
          },
          {
            "name": "ManagerVacanciesRisk",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype[SOURCE]=\"ManagerVacancies Risk\",SnapshotRiskbytype[SourceSeq] =4,SnapshotRiskbytype[RiskValue]>=3,SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))",
            "formatString": "0",
            "lineageTag": "b70471bf-9dc9-4958-84cf-67641325f835"
          },
          {
            "name": "RegionalManagerRisk",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Regional Manager Risk\"),filter(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] =3),SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))",
            "formatString": "0",
            "lineageTag": "9f1cec4e-d140-40b7-bc6e-012b0f5d627e"
          },
          {
            "name": "TeamMember",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Team Member Attriton\"),SnapshotRiskbytype[RiskValue]=3,SnapshotRiskbytype[SOURCE]<>\"totalrisk\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
            "formatString": "0",
            "lineageTag": "b9890e6c-b242-417f-bf3e-cd040d74f8ae"
          },
          {
            "name": "TotalCategory",
            "expression": "[Agency Cost Risk]+[CQCInspectionRisk]+[CQC Registered Manager Risk]+[InternalAuditRisk]+[ManagerVacanciesRisk]+[Recuritment]+[RegionalManagerRisk]+[Team Member]+[F2F High Risk]+[Elearning High Risk]",
            "formatString": "0",
            "lineageTag": "32b2f8ee-22c5-4c77-9e35-45ca1f1dccce"
          },
          {
            "name": "Agency Cost Risk_LastWeek",
            "expression": [
              "",
              "",
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\",",
              "                        SnapshotRiskbytype[RiskValue] = 3,",
              "                       SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9e345e57-a481-4ff6-a325-58925c772a86"
          },
          {
            "name": "CQC Inspection Risk last week",
            "expression": [
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\",",
              "                        SnapshotRiskbytype[RiskValue] in {3,4},",
              "                       ---SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d1d49317-2e62-420b-8d1b-711a90b4671e"
          },
          {
            "name": "CQC REg Last week",
            "expression": [
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"CQC Regd Mgr Risk\",",
              "                        SnapshotRiskbytype[RiskValue] = 3,",
              "                       SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0e0828c0-155c-4c79-9985-5ac5fc756b88"
          },
          {
            "name": "Internal Audit last week",
            "expression": [
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\",",
              "                        SnapshotRiskbytype[RiskValue] = 3,",
              "                       SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "00d04c55-7dbe-4538-9491-774744fcb016"
          },
          {
            "name": "Manager vac Last week",
            "expression": [
              "",
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"ManagerVacancies Risk\",",
              "                        SnapshotRiskbytype[RiskValue] = 3,",
              "                       SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "5244f992-1d4b-4be0-b016-51ecb062c117"
          },
          {
            "name": "Recruitment Last week",
            "expression": [
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\",",
              "                        SnapshotRiskbytype[RiskValue] in{3,4},",
              "                       SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "45184e56-956d-431c-8460-4d6de0ea9a80"
          },
          {
            "name": "Regional Mnager Last week",
            "expression": [
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"Regional Manager Risk\",",
              "                        SnapshotRiskbytype[RiskValue] =3,",
              "                       SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d67062e7-059d-472d-92ac-cdbd0e471ba0"
          },
          {
            "name": "Team Member",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Team Attrition Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))",
            "formatString": "0",
            "lineageTag": "f679bab2-01d6-4dfa-b221-73bbb354c364"
          },
          {
            "name": "F2F High Risk",
            "expression": [
              "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,",
              "SnapshotRiskbytype[SOURCE - Drill Through]=\"F2F Compliance Risk\"),filter(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue]in {3,4}),SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))"
            ],
            "formatString": "0",
            "lineageTag": "80e8a711-2d60-4d12-af0b-1be0b4715537"
          },
          {
            "name": "F2f Last week",
            "expression": [
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"F2F Compliance Risk\",",
              "                        SnapshotRiskbytype[RiskValue] in{3,4},",
              "                       SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "d0065ccd-8a04-45aa-b085-11181520596e"
          },
          {
            "name": "Elearning High Risk",
            "expression": [
              "CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,",
              "SnapshotRiskbytype[SOURCE - Drill Through]=\"Elearning Compliance Risk\"),filter(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue]in {3,4}),SnapshotRiskbytype[SnapshotDate - Copy]=MAX(SnapshotRiskbytype[SnapshotDate - Copy]))"
            ],
            "formatString": "0",
            "lineageTag": "3ca0a8fe-f9af-4d93-92f4-555b054b3d6a"
          },
          {
            "name": "ELearning Last week",
            "expression": [
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"Elearning Compliance Risk\",",
              "                        SnapshotRiskbytype[RiskValue] in{3,4},",
              "                       SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "b4350abd-4703-4ce5-b938-feb204978d04"
          },
          {
            "name": "TotalCategory 2",
            "expression": "CALCULATE([TotalCategory],FILTER(SnapshotRiskbytype,SnapshotRiskbytype[CalendarMonthNameYear]=SELECTEDVALUE(ServiceRiskAnalysisCombined[CalendarMonthNameYear])))",
            "formatString": "0",
            "lineageTag": "54ff7693-417a-467b-acc3-2fea4ca386af"
          }
        ],
        "partitions": [
          {
            "name": "All Summary Measures-d6b0b9c9-f31b-4e6c-b3e3-9771a3d7249f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "NewSummaryMeasure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "20f058ad-37b3-4712-9f60-109fc4876e34",
        "measures": [
          {
            "name": "HighriskDistinct",
            "expression": "CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] in {3,4} && SnapshotRiskbytype[SOURCE]<>\"Totalrisk\" && SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate])))",
            "formatString": "0",
            "lineageTag": "b72548b0-7d8f-4a08-830b-ecab0a842039"
          },
          {
            "name": "ModerateRiskDistinct",
            "expression": [
              "VAR B = CALCULATETABLE( VALUES(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] in {3,4}),SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "",
              "VAR A =",
              " CALCULATE(distinctcount(SnapshotRiskbytype[FacilityName])",
              ",FILTER(SnapshotRiskbytype,(SnapshotRiskbytype[RiskValue]=2 && SnapshotRiskbytype[SOURCE]<>\"Totalrisk\" && SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "&&",
              "NOT(SnapshotRiskbytype[FacilityName]) IN B  ))",
              "",
              "",
              "",
              "",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1)))"
            ],
            "formatString": "0",
            "lineageTag": "1b4a1319-afd9-4953-a54a-969275a2fd32"
          },
          {
            "name": "LowRiskDistinct",
            "expression": [
              "VAR B = CALCULATETABLE( VALUES(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] in {2,3,4}),SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "",
              "VAR A =",
              " CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName])",
              ",FILTER(SnapshotRiskbytype,(SnapshotRiskbytype[RiskValue]=1 && SnapshotRiskbytype[SOURCE]<>\"Totalrisk\" && SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "&&",
              "NOT(SnapshotRiskbytype[FacilityName]) IN B  ))",
              "",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1)))"
            ],
            "formatString": "0",
            "lineageTag": "3ca92230-102d-4518-9e6c-0f047c3481fe"
          },
          {
            "name": "TotalRiskDistinct",
            "expression": "[HighriskDistinct]+[LowRiskDistinct]+[ModerateRiskDistinct]",
            "formatString": "0",
            "lineageTag": "ceabf512-b6b2-4f44-a635-b4f7c4c53b75"
          },
          {
            "name": "AGencyCost",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"),SnapshotRiskbytype[RiskValue]=3,SnapshotRiskbytype[SOURCE]<>\"totalrisk\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
            "formatString": "0",
            "lineageTag": "b5c35478-60bd-4fc0-a4b1-fab9778b0ad2"
          },
          {
            "name": "CQCRegistered",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Regd Mgr Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
            "formatString": "0",
            "lineageTag": "db15d3d9-0df1-4c1c-9fea-993f7fa46e64"
          },
          {
            "name": "Internal Audit",
            "expression": "CALCULATE(COUNT(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\",SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
            "formatString": "0",
            "lineageTag": "01bb6243-ce45-470a-95dc-2c5dc4e772c3"
          },
          {
            "name": "PrevTotalCAtegory",
            "expression": [
              "",
              "CALCULATE([TotalCategory],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "--var a=calCULATE([TotalCategory],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "",
              "--var b = calCULATE([TotalCategory],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear]))",
              "",
              "--return IF(WEEKNUM(TODAY()=1),b,a)"
            ],
            "formatString": "0",
            "lineageTag": "d0175b1a-a3dc-4488-b07a-3c895d892724"
          },
          {
            "name": "CategoryCol",
            "expression": "IF([TotalCategory]>[PrevTotalCAtegory],\"#FD625E\",\"#00B810\")",
            "lineageTag": "31d6c83b-2a40-4ea6-a9bf-2343a6044ccd"
          },
          {
            "name": "RiskValue",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] <>\"TotalRisk\"),FILTER( SnapshotRiskbytype,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate])))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1b7ada95-75d2-4c32-8bf0-0c0a765d72a8"
          },
          {
            "name": "PreviousweekTotalcategory",
            "lineageTag": "2669702f-f40c-4953-801d-08faac559fa6"
          },
          {
            "name": "Holly-Lowrisk",
            "expression": [
              "VAR B = CALCULATETABLE( VALUES(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] in {2,3,4},SnapshotRiskbytype[SOURCE] <>\"Totalrisk\")",
              "",
              "VAR A =",
              " CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] =1,SnapshotRiskbytype[SOURCE] <>\"Totalrisk\", SnapshotRiskbytype[Head_Of_Operations]=\"Holly Mceneaney\"",
              "&&",
              "NOT(SnapshotRiskbytype[FacilityCode]) IN B  )",
              "",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1)))"
            ],
            "formatString": "0",
            "lineageTag": "6d53b020-2814-493d-9b7b-ed7e79b23021"
          },
          {
            "name": "Sharon_moderateRisk",
            "expression": [
              "VAR B = CALCULATETABLE( VALUES(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] in {3,4},SnapshotRiskbytype[SOURCE] <>\"Totalrisk\")",
              "",
              "VAR A =",
              " CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] =2,SnapshotRiskbytype[SOURCE] <>\"Totalrisk\", SnapshotRiskbytype[Head_Of_Operations]=\"Holly Mceneaney\",SnapshotRiskbytype[Head_Of_Operations]=\"Sharon Ford\"",
              "&&",
              "NOT(SnapshotRiskbytype[FacilityCode]) IN B  )",
              "",
              "",
              "",
              "",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1)))"
            ],
            "formatString": "0",
            "lineageTag": "f6e35470-5e74-48a0-9dce-0c617144c35b"
          },
          {
            "name": "Holly_moderateRisk",
            "expression": [
              "VAR B = CALCULATETABLE( VALUES(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] in {3,4},SnapshotRiskbytype[SOURCE] <>\"Totalrisk\")",
              "",
              "VAR A =",
              " CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] =2,SnapshotRiskbytype[SOURCE] <>\"Totalrisk\", SnapshotRiskbytype[Head_Of_Operations]=\"Holly Mceneaney\"",
              "&&",
              "NOT(SnapshotRiskbytype[FacilityCode]) IN B  )",
              "",
              "",
              "",
              "",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1)))"
            ],
            "formatString": "0",
            "lineageTag": "86194417-3d27-468e-9869-ecd3cf9cc6e6"
          },
          {
            "name": "PreviousweekHOp",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a = [Last week date]",
              " ",
              " VAR B = CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SnapshotDate - Copy]=A))",
              "VAR C  =CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate - Copy]= A,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\"",
              ")",
              "",
              "RETURN c/b",
              " ",
              " --CALCULATE([HopPercentage],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "",
              "--var a=calCULATE([HopPercentage],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "",
              "--var b = calCULATE([HopPercentage],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear]))",
              "",
              "--return IF(WEEKNUM(TODAY()=1),b,a)"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "0d11a040-f7bb-45d4-a75f-8b90bce2a245"
          },
          {
            "name": "PreviousWeekServices",
            "expression": [
              "--CALCULATE([RiskValue],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "",
              "--var a=calCULATE([RiskValue],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "",
              "--var b = calCULATE([RiskValue],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear]))",
              "",
              "--return IF",
              "--(TODAY()=MAX(SnapshotRiskbytype[CalendarMonthNameYear]),b,a)",
              "",
              "--CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] <>\"TotalRisk\"),",
              "--FILTER( SnapshotRiskbytype,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate])))",
              "",
              "",
              "",
              "",
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "",
              "Var Risk = CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),SnapshotRiskbytype[SOURCE] <>\"TotalRisk\", ",
              "            SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "",
              "RETURN Risk ",
              "",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0d18c8b3-7564-4ad2-84ef-b31dca76288d"
          },
          {
            "name": "PreviousRiskbyservice",
            "expression": [
              "CALCULATE([RiskValue],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "--var a=calCULATE([RiskValue],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "",
              "--var b = calCULATE([RiskValue],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear]))",
              "",
              "--return IF(WEEKNUM(TODAY()=1),b,a)"
            ],
            "formatString": "0",
            "lineageTag": "1e1866ba-aad0-46c4-aa20-d72d0d14f0cb"
          },
          {
            "name": "TotalRiskServiceColour",
            "expression": [
              "--IF([RiskValue]>=[Risk value Selected Month Check],\"#FD625E\",\"#00B810\") ",
              " IF([RiskValue]>=[PreviousWeekServices],\"#FD625E\",\"#00B810\") "
            ],
            "lineageTag": "523d7810-c3d3-4243-9cba-3cbfb4b49536"
          },
          {
            "name": "CategoryDistinct",
            "expression": [
              "",
              "var a= CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"),SnapshotRiskbytype[RiskValue] in {3,4},SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "var b= CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"),SnapshotRiskbytype[RiskValue] in {3,4},SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "var c=  CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "var d=CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "var e =CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Rgional Manager Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "var f= CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC registered Manager Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "var g =CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"ManagerVacancies Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "var h =CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"),SnapshotRiskbytype[RiskValue] = 3,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              "",
              "return a+b+c+d+e+f+g+h",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9e269cba-0498-4c46-ab8d-dac32adfec17"
          },
          {
            "name": "HighriskDistinctServices",
            "expression": "CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] in {3,4}),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[SourceSeq]<>\"Totalrisk\")",
            "formatString": "0",
            "lineageTag": "a0d0fd7a-821f-4bab-9826-068ec96f4260"
          },
          {
            "name": "ModerateRiskDistinctservices",
            "expression": [
              "VAR B = CALCULATETABLE( VALUES(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] in {3,4},SnapshotRiskbytype[SOURCE] <>\"Totalrisk\")",
              "",
              "VAR A =",
              " CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] =2,SnapshotRiskbytype[SOURCE] <>\"Totalrisk\"",
              "&&",
              "NOT(SnapshotRiskbytype[FacilityCode]) IN B)",
              "",
              "",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1)))"
            ],
            "formatString": "0",
            "lineageTag": "aa3cf0ed-144e-4307-b341-4b0416d46297"
          },
          {
            "name": "LowRiskDistinctService",
            "expression": [
              "VAR B = CALCULATETABLE( VALUES(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] in {2,3,4},SnapshotRiskbytype[SOURCE] <>\"Totalrisk\")",
              "",
              "VAR A =",
              " CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\",",
              "SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]),SnapshotRiskbytype[RiskValue] =1,SnapshotRiskbytype[SOURCE] <>\"Totalrisk\"",
              "&&",
              "NOT(SnapshotRiskbytype[FacilityCode]) IN B)",
              "",
              "",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1)))"
            ],
            "formatString": "0",
            "lineageTag": "5b7998be-81a9-4160-b3ff-006ee2ec672c"
          },
          {
            "name": "totaldistinctservices",
            "expression": "[HighriskDistinctServices]+[ModerateRiskDistinctservices]+[LowRiskDistinctService]",
            "formatString": "0",
            "lineageTag": "98505337-8ee9-4313-807f-54d1d9705aa0"
          },
          {
            "name": "CQCInspectondist",
            "expression": "CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"Internal Audit risk\"),SnapshotRiskbytype[RiskValue] in {3,4},SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
            "formatString": "0",
            "lineageTag": "3d6ad3fa-5d0f-4db7-8ffc-2888fcf3fbfd"
          },
          {
            "name": "HighriskTotal",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityCode]),SnapshotRiskbytype,SnapshotRiskbytype[SOURCE]=\"CQC Inspection Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Recruitment Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Team Member Attrition Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"rgional Manager Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Managervacancies Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Internal Audit Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"Agency Cost Risk\"||",
              "SnapshotRiskbytype[SOURCE]=\"CQC Registered Manager Risk\"",
              ",SnapshotRiskbytype[RiskValue] in {3,4},SnapshotRiskbytype[SOURCE] <>\"Totalrisk\")"
            ],
            "formatString": "0",
            "lineageTag": "5d060d6f-3325-46b9-9382-ea90a27ec977"
          },
          {
            "name": "Highrisk",
            "expression": [
              "",
              "",
              "VAR A = [Max Snapshot Date]",
              "",
              "",
              "VAR B  =CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate]= a,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\"",
              "     )",
              "/*Var C=CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate]= a,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",SnapshotRiskbytype[Head of Ops_Revised)]<>\"kate Durband\" && SnapshotRiskbytype[Head of Ops_Revised)]<>\"Reporting\")",
              "Var D=CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate]= a,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",SnapshotRiskbytype[Head of Ops_Revised)]=\"kate Durband\")",
              "",
              "     +CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate]= a,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",SnapshotRiskbytype[Head of Ops_Revised)]=\"Reporting\")*/",
              "",
              "RETURN B"
            ],
            "formatString": "0",
            "lineageTag": "c4f7e51d-5c33-4182-aa19-cec5c5348d69"
          },
          {
            "name": "HopPercentage",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "var a=[Highrisk]/[DistinctFaclities]",
              "",
              "",
              "",
              "return a"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "fd5768da-8154-41c7-816d-f9e058c3fe4b"
          },
          {
            "name": "PreviousHopPercent",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE([HopPercentage],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear]))",
            "lineageTag": "9e690d04-c095-423b-8d25-8670e67380e0"
          },
          {
            "name": "HopPercentColour",
            "expression": [
              "--IF([HopPercentage]>=[HOP Selected Month Check],\"#FD625E\",\"#00B810\")",
              "",
              "IF([HopPercentage]>=[Hop Percentage Last week],\"#FD625E\",\"#00B810\")"
            ],
            "lineageTag": "98f3b41a-673f-4e92-932f-e6ce97565a5b"
          },
          {
            "name": "PreviousweekPercentage",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] in {3,4})",
              "    ,SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "",
              "   "
            ],
            "formatString": "0",
            "lineageTag": "9a0fe70d-5c66-4df5-8e71-61c4a80d8258"
          },
          {
            "name": "HighriskPreviousweek",
            "expression": [
              "CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] in {3,4})",
              "  ,SnapshotRiskbytype[SOURCE]<>\"Totalrisk\"",
              "",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "5af97641-797d-4b77-86ac-3ae0446ed2be"
          },
          {
            "name": "moderatePreviousweek",
            "expression": [
              "VAR B = CALCULATETABLE( VALUES(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[RiskValue] in {3,4}),SnapshotRiskbytype[SOURCE]<>\"Totalrisk\")",
              "",
              "",
              "VAR A =",
              " CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName])",
              ",FILTER(SnapshotRiskbytype,(SnapshotRiskbytype[RiskValue]=2 && SnapshotRiskbytype[SOURCE]<>\"Totalrisk\" )",
              "&&",
              "NOT(SnapshotRiskbytype[FacilityName]) IN B  ))",
              "",
              "",
              "",
              "",
              "",
              "",
              "RETURN A --- COUNTROWS(FILTER(B,1=1)))"
            ],
            "formatString": "0",
            "lineageTag": "d9df811c-ad46-4358-84ec-648aad3dcfcb"
          },
          {
            "name": "hoppreviousmonth",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE([HopPercentage],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "--var a=calCULATE([HopPercentage],DATEADD(SnapshotRiskbytype[WeekEnd Date],-1,DAY))",
              "",
              "--var b = calCULATE([HopPercentage],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear]))",
              "",
              "--return IF(WEEKNUM(TODAY()=1),b,a)"
            ],
            "lineageTag": "33c83bcc-4d93-48a1-98b5-b18a62622e75"
          },
          {
            "name": "DistinctFaclities",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": "CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate])))",
            "lineageTag": "04b43f8e-2c1a-4648-b807-53261c7bde77"
          },
          {
            "name": "Service DrillThrough",
            "expression": "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] <>\"Photography Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
            "formatString": "0",
            "lineageTag": "c9c2ad71-e97b-4d96-b039-2d8aa10edff7"
          },
          {
            "name": "Max Snapshot Date",
            "expression": "CALCULATE( MAX(SnapshotRiskbytype[SnapshotDate]), ALL(SnapshotRiskbytype[Head of Operations]))",
            "lineageTag": "24155acf-5972-47a8-8dba-1f5033b8568d"
          },
          {
            "name": "Previousweek date",
            "expression": [
              "var a = MAX(SnapshotRiskbytype[SnapshotDate - Copy])",
              "var b = a-6",
              "return b"
            ],
            "formatString": "General Date",
            "lineageTag": "11dfe63e-15b3-4966-bc4e-fdb8ac4726d7"
          },
          {
            "name": "Last week date",
            "expression": "CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy])-WEEKDAY(TODAY()),ALL(SnapshotRiskbytype[Head_Of_Operations]),ALL(SnapshotRiskbytype[SnapshotDate - Copy]))",
            "formatString": "General Date",
            "lineageTag": "bf9353ce-7d67-4a6d-b704-ede1f1470a08"
          },
          {
            "name": "Weeknum Today",
            "expression": "WEEKNUM(TODAY())",
            "formatString": "0",
            "lineageTag": "ea4ac770-730c-4a07-85a3-fad833cb24a1"
          },
          {
            "name": "Hop Percentage Last week",
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "expression": [
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "Var Highrisk1  =CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate ,    ",
              "ALL(SnapshotRiskbytype[Current Month Slicer]), ---ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\")",
              " ",
              "",
              "Var DistinctFaclities1 = CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "ALL(SnapshotRiskbytype[Current Month Slicer]),  ---ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate )",
              "",
              "Var Hop_Pctg = DIVIDE(Highrisk1  ,DistinctFaclities1 ,0)",
              "",
              "REturn Hop_Pctg",
              "",
              "--REturn DistinctFaclities1"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "aa66ce9f-a5ca-4a65-8380-de06c20f3db2"
          },
          {
            "name": "Team Member last week",
            "expression": [
              "/*",
              "Var Currentmonth = FORMAT(TODAY(),\"YYYYMM\")",
              "Var LastMonth = FORMAT(TODAY()- WEEKDAY(TODAY()),\"YYYYMM\")",
              "Var LastWeekEndDate =    IF(Currentmonth = LastMonth, TODAY()- WEEKDAY(TODAY()), DATE(YEAR(TODAY()),MONTH(TODAY()),1) -1)",
              "*/",
              "",
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[Current Month Slicer]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMM\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "Var Risk = CALCULATE(COUNT(SnapshotRiskbytype[FacilityName]),",
              "                        SnapshotRiskbytype[SOURCE]=\"Team Attrition Risk\",",
              "                        SnapshotRiskbytype[RiskValue] =3,",
              "                       SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",",
              "                       SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate , ",
              "                        ALL(SnapshotRiskbytype[Current Month Slicer]))",
              "",
              "RETURN Risk ",
              ""
            ],
            "formatString": "0",
            "lineageTag": "27d35e80-72c4-403d-a0e9-5f92483eb160"
          },
          {
            "name": "Lastweek Category",
            "expression": "[Manager vac Last week]+[Internal Audit last week]+[Recruitment Last week]+[Regional Mnager Last week]+[Team Member last week]+[CQC Inspection Risk last week]+[CQC REg Last week]+[Agency Cost Risk_LastWeek]",
            "formatString": "0",
            "lineageTag": "bce9c6aa-1de0-4303-85d5-4121419d24f5"
          },
          {
            "name": "Test date",
            "expression": [
              "",
              "",
              "---------------------------------------------------------------------------------",
              "",
              "Var SelectedMOnth = SELECTEDVALUE(SnapshotRiskbytype[CalendarMonthNameYear]) -- 202301",
              " ",
              "VAr MaxSnapshotDateforSelectedMOnth = CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),",
              "ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "                                        ALLSELECTED(SnapshotRiskbytype[CalendarMonthNameYear]))",
              "",
              " Var MaxDateforSelectedMOnth =  ",
              " ",
              " IF(FORMAT(SelectedMOnth,\"YYYYMM\") = FORMAT(MaxSnapshotDateforSelectedMOnth, \"YYYYMM\"),",
              "    MaxSnapshotDateforSelectedMOnth,MaxSnapshotDateforSelectedMOnth-1) -- 202301 --20230131",
              " ",
              "----------------------------------------------------------------------------------",
              "Var CurrentmonthMaxDate = FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") --- 31/1/2023 -- 202301",
              "Var LastWeekend = FORMAT(MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth),\"YYYYMMdd\") -- 28/1/2023 -- 202301--YYYYMM",
              "Var LastMonthLastDate =IF(FORMAT(MaxDateforSelectedMOnth,\"YYYYMM\") = FORMAT(TODAY(),\"YYYYMM\") ,",
              "                           DATE(YEAR( MaxDateforSelectedMOnth), MONTH(MaxDateforSelectedMOnth),1)-1, MaxDateforSelectedMOnth) ",
              " ",
              "Var LastWeekEndDate =  ",
              "  IF(CurrentmonthMaxDate = LastWeekend,MaxDateforSelectedMOnth - WEEKDAY(MaxDateforSelectedMOnth), LastMonthLastDate)",
              "",
              "Var Highrisk1  =CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate ,    ",
              "ALL(SnapshotRiskbytype[CalendarMonthNameYear]), ---ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\")",
              " ",
              "",
              "Var DistinctFaclities1 = CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "ALL(SnapshotRiskbytype[CalendarMonthNameYear]),  ---ALL(SnapshotRiskbytype[Head_Of_Operations]),",
              "SnapshotRiskbytype[SnapshotDate - Copy]= LastWeekEndDate )",
              "",
              "Var Hop_Pctg = DIVIDE(Highrisk1  ,DistinctFaclities1 ,0)",
              "",
              "REturn Hop_Pctg",
              "",
              "--REturn DistinctFaclities1"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "34742009-4f95-4a6b-8085-1e30024e2e5a"
          },
          {
            "name": "Selected Month Max",
            "expression": [
              "",
              "VAR MaxMonth = CALCULATE(MAX('SnapshotRiskbytype'[CalendarMonthNameYear]), ALL('SnapshotRiskbytype'))",
              "VAR SelectedMonth = SELECTEDVALUE('SnapshotRiskbytype'[CalendarMonthNameYear])",
              "RETURN",
              "    IF(SelectedMonth = MaxMonth, \"Max Month\", \"Not Max Month\")"
            ],
            "lineageTag": "3a7bc79b-dcc0-47ff-abc3-a89e0e17cc5a"
          },
          {
            "name": "HOP Selected Month Check",
            "expression": [
              "",
              "VAR MaxMonth = CALCULATE(MAX('SnapshotRiskbytype'[CalendarMonthNameYear]), ALL('SnapshotRiskbytype'))",
              "VAR SelectedMonth = SELECTEDVALUE('SnapshotRiskbytype'[CalendarMonthNameYear])",
              "RETURN",
              "    IF(SelectedMonth = MaxMonth,CALCULATE([HopPercentage],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear])),[Hop Percentage Last week])",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "39e0872f-163d-49f4-aec6-ee1bd6a83aed"
          },
          {
            "name": "Category Selected Month Check",
            "expression": [
              "",
              "VAR MaxMonth = CALCULATE(MAX('SnapshotRiskbytype'[CalendarMonthNameYear]), ALL('SnapshotRiskbytype'))",
              "VAR SelectedMonth = SELECTEDVALUE('SnapshotRiskbytype'[CalendarMonthNameYear])",
              "RETURN",
              "    IF(SelectedMonth = MaxMonth,CALCULATE([TotalCategory],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear])),[PreviousweekCategory])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4fed9c1e-5814-4b7a-9762-cec4a267c931"
          },
          {
            "name": "Risk value Selected Month Check",
            "expression": [
              "",
              "VAR MaxMonth = CALCULATE(MAX('SnapshotRiskbytype'[CalendarMonthNameYear]), ALL('SnapshotRiskbytype'))",
              "VAR SelectedMonth = SELECTEDVALUE('SnapshotRiskbytype'[CalendarMonthNameYear])",
              "RETURN",
              "    IF(SelectedMonth = MaxMonth,CALCULATE([RiskValue],PREVIOUSMONTH(SnapshotRiskbytype[CalendarMonthNameYear])),[PreviousWeekServices])",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0a78846e-362f-4176-b339-e3a184c2884a"
          },
          {
            "name": "Weekly AgencyCost",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] =\"Agency Cost Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "caad3e16-0ffc-425b-8957-f545ddf67748"
          },
          {
            "name": "Weekly CQC Inherited",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] =\"CQC Inherited Rating Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ca440229-eccd-425c-8d9d-0fd9b875e2c1"
          },
          {
            "name": "Weekly CQCInspection",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] =\"CQC Inspection Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "064d1885-c34f-4a11-8cb6-27c9348eb8b4"
          },
          {
            "name": "Weekly CQC Registered",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] =\"CQC Regd mgr Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4bff5ada-39e1-435f-ba25-ae6d18337a36"
          },
          {
            "name": "Weekly InternalAudit",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] =\"Internal Audit Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "ac793f47-9e30-4ba7-8199-af960e239107"
          },
          {
            "name": "Weekly ManagerVacancies",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] =\"ManagerVacancies Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "acd1abff-ce13-4632-974c-d533f0f19970"
          },
          {
            "name": "Weekly Recruitment",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] =\"Recruitment Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "39ecbd99-952b-44b1-8ba8-e7833d346093"
          },
          {
            "name": "Weekly RegionalMgr",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] =\"REgional Manager Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "c24251e2-33ba-432f-ad46-c7d6b8a007bc"
          },
          {
            "name": "Weekly Team Attrition",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] =\"Team Attrition Risk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "2c1809f3-d51b-4cc7-b2ae-3f0f3db4e563"
          },
          {
            "name": "Weekly CombinedScore",
            "expression": [
              "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SOURCE] <>\"TotalRisk\"),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f6bbdc17-9d07-43a5-a0bc-c22f239795b9"
          },
          {
            "name": "Highrisk Test",
            "expression": [
              "",
              "",
              "VAR A = [Max Snapshot Date]",
              "",
              "VAR B  =CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate]= a,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\" && SnapshotRiskbytype[Head of Operations] = \"reporting\" && SnapshotRiskbytype[Head of Operations]=\"kate durband\"",
              ")",
              "",
              "RETURN B "
            ],
            "formatString": "0",
            "lineageTag": "697bb69d-572f-4a01-9ed9-9b03db2de97c"
          },
          {
            "name": "Test HighRisk",
            "expression": [
              "var D=IF(SELECTEDVALUE(SnapshotRiskbytype[Head of Operations_Revised)])=0,0,SELECTEDVALUE(SnapshotRiskbytype[Head of Operations_Revised)]))",
              "",
              "",
              "var A =CALCULATE([Highrisk],SnapshotRiskbytype[Head of Ops_Revised)]=\"Kate durband\")",
              "",
              "var B=CALCULATE([Highrisk],SnapshotRiskbytype[Head of Ops_Revised)]=\"Reporting\")",
              "",
              " return IF(ISFILTERED(SnapshotRiskbytype[Head of Ops_Revised)]),a+b,[Highrisk])"
            ],
            "formatString": "0",
            "lineageTag": "73f35e4f-8ab4-4e37-a1f0-77bd32ba34f8"
          },
          {
            "name": "Measure 9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "var a= CALCULATE([HopPercentage],SnapshotRiskbytype[Head of Ops_Revised)]=\"Kate Durband\")",
              "",
              " var b=CALCULATE([HopPercentage],SnapshotRiskbytype[Head of Ops_Revised)]=\"reporting\")",
              "",
              " return a+b"
            ],
            "lineageTag": "71dfe5a1-a813-41f4-b447-ab7de2590468"
          },
          {
            "name": "Test HOA",
            "expression": "REPLACE(FIND(\"Reporting\",SELECTEDVALUE(SnapshotRiskbytype[Head_Of_Operations]),1,BLANK()),1,12,\"Kate Durband\")",
            "lineageTag": "b4179788-e739-4421-982e-c5effa4d66ad"
          },
          {
            "name": "HopPercentage drill though",
            "expression": [
              "var a=CALCULATE([Highrisk]/[DistinctFaclities],all(SnapshotRiskbytype[CalendarMonthNameYear]))",
              "",
              "",
              "",
              "return a"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "49910ea4-e293-496d-9de6-a8c268140703"
          },
          {
            "name": "Highrisk_Test",
            "expression": [
              "",
              "",
              "VAR A = [Max Snapshot Date]",
              "",
              "",
              "VAR B  =CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate]= a,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\"",
              "     )",
              "/*Var C=CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate]= a,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",SnapshotRiskbytype[Head of Ops_Revised)]<>\"kate Durband\" && SnapshotRiskbytype[Head of Ops_Revised)]<>\"Reporting\")",
              "Var D=CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate]= a,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",SnapshotRiskbytype[Head of Ops_Revised)]=\"kate Durband\")",
              "",
              "     +CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),",
              "SnapshotRiskbytype[RiskValue] in {3,4},",
              "SnapshotRiskbytype[SnapshotDate]= a,    ----MAX(SnapshotRiskbytype[SnapshotDate]),",
              "     SnapshotRiskbytype[SOURCE]<>\"Totalrisk\",SnapshotRiskbytype[Head of Ops_Revised)]=\"Reporting\")*/",
              "",
              "RETURN CALCULATE(IF(b=BLANK(),0,B))"
            ],
            "formatString": "0",
            "lineageTag": "7a242bac-59e3-43ad-80a2-88e3e148fce0"
          }
        ],
        "partitions": [
          {
            "name": "NewSummaryMeasure-c61be4ef-b2ab-4d3b-b530-580dbd6e1709",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_570c7e04-6503-47a6-aa3d-df22165e45c8",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "21af2d99-48d3-4de5-b068-4bf4cf86ab8c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "871112b5-4589-449d-b379-85d40449da8a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "91d290a7-5b9c-44d7-99dc-ac50a10139c7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a3f357af-186b-4e40-9373-3b554aa9a0cd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5030453d-a4a4-4198-91fb-3472563b9193",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "94720bb5-9f77-498f-811a-ef0301aa0ca4",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "01f819ae-de27-44ea-af5b-b0b58c4867ba",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d775b0f5-8278-499c-a1cb-d6cd573613db",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a26bdc75-4bd3-4bce-86cd-069e744c0053",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "07bb1f49-a261-4ed9-8732-7379311a5c81",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d08de892-ba05-4b52-a9be-c91cc051a9f1",
                "ordinal": 3
              }
            ],
            "lineageTag": "8963bbd7-63a0-4e4b-8f10-627d92188dd5"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "71b8c512-ade3-4745-8808-e5ec2b490706",
        "partitions": [
          {
            "name": "DateTableTemplate_570c7e04-6503-47a6-aa3d-df22165e45c8-e4af7820-9568-410c-a5fc-f547a925bba1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a6b79582-a5d1-43a0-ab76-c7f902d0d17b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "37cd7ae6-b7b3-4814-86cf-695034e7ad9a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9a29775b-1514-49f0-abe9-13ea8805111c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ddacde22-aab8-463f-a38e-c0dd3d989f48",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "98a3a55c-3f69-4208-b218-20994a0a4e44",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cacfdfbb-f6f4-4b9d-a92b-59303d3fb472",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "a793c3c1-ff20-466e-9eca-caf6a5c696c1",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "981f9499-665e-4c7d-924c-a5de34cbfd3a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "209f6691-db7e-46d0-b70f-ec4d9164b0bb",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d8d2d194-8616-4078-8896-702acd27dc1a",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "cd2e6837-ba0b-4475-95ba-ab28d717a49b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "113a5504-5421-4d1d-b5ae-41a41a288fff",
                "ordinal": 3
              }
            ],
            "lineageTag": "0a6ae6c8-00eb-404d-ab7b-f85b1b355bdc"
          }
        ],
        "isHidden": true,
        "lineageTag": "dd5c7bd3-f666-4a0a-b1a2-5b4b03c30977",
        "partitions": [
          {
            "name": "LocalDateTable_a6b79582-a5d1-43a0-ab76-c7f902d0d17b-eb5cd40f-6ffb-40fb-9bc5-d22dc4632d26",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceRiskAnalysisCombined'[CalendarMonthNameYear_New])), 1, 1), Date(Year(MAX('ServiceRiskAnalysisCombined'[CalendarMonthNameYear_New])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "SnapshotRiskbytype",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Regulator ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1056593b-3742-43cd-9842-9294189b7573",
            "sourceColumn": "Regulator ID",
            "summarizeBy": "none"
          },
          {
            "name": "RegulatorName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0412c585-c310-4a89-bf59-24a97ba686cc",
            "sourceColumn": "RegulatorName",
            "summarizeBy": "none"
          },
          {
            "name": "FacilityCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "74dd2a23-75f2-4270-b776-0b6bf6a74dad",
            "sourceColumn": "FacilityCode",
            "summarizeBy": "count"
          },
          {
            "name": "FacilityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3126a622-c368-421a-ab4e-3cc1297c8e6e",
            "sourceColumn": "FacilityName",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bedf2f34-e6c7-46eb-b205-3e8f36af570c",
            "sourceColumn": "SOURCE",
            "summarizeBy": "none"
          },
          {
            "name": "SourceSeq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e9f8046-0a41-4f79-a722-240a5de80c1c",
            "sourceColumn": "SourceSeq",
            "summarizeBy": "sum"
          },
          {
            "name": "R0",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "103d936f-e61f-43fa-95f9-ce12162f4091",
            "sourceColumn": "R0",
            "summarizeBy": "sum"
          },
          {
            "name": "R1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0aa30c32-5f5f-4eca-bfb3-6969e94b95bc",
            "sourceColumn": "R1",
            "summarizeBy": "sum"
          },
          {
            "name": "R2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "94a8ad17-18a0-492b-bbd5-67f738d2a195",
            "sourceColumn": "R2",
            "summarizeBy": "sum"
          },
          {
            "name": "R3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "66ddb38a-8503-4ca1-8f14-9956eb521ec3",
            "sourceColumn": "R3",
            "summarizeBy": "sum"
          },
          {
            "name": "R4",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "de31cfb9-2df3-4ae0-bf03-bc274dfc3747",
            "sourceColumn": "R4",
            "summarizeBy": "sum"
          },
          {
            "name": "RiskValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d486668a-2482-49bf-9e36-42d77490713e",
            "sourceColumn": "RiskValue",
            "summarizeBy": "sum"
          },
          {
            "name": "SnapshotDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfe764d5-280c-4f34-9d37-16e2f3589ac1",
            "sourceColumn": "SnapshotDate",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar_Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1776f146-02e5-4106-8bdf-ad700cf83c12",
            "sourceColumn": "Calendar_Month",
            "summarizeBy": "sum"
          },
          {
            "name": "calendar_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e045ecd2-ab88-420b-a3ee-269cefda4596",
            "sourceColumn": "calendar_year",
            "summarizeBy": "sum"
          },
          {
            "name": "calendar_quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f9d2f1d9-a08c-4627-aa16-dedc0271d7aa",
            "sourceColumn": "calendar_quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Month_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac5f1770-3ff1-4c52-848b-c9f5cd88568a",
            "sourceColumn": "Month_Name",
            "summarizeBy": "none"
          },
          {
            "name": "days_in_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "194474b2-df51-4c65-84fe-9913578959d5",
            "sourceColumn": "days_in_month",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c4c73c13-cac7-4328-b386-68878347ae87",
            "sourceColumn": "fiscal_quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9313a45e-6853-4f2d-a7fc-69aaae10c09f",
            "sourceColumn": "fiscal_month",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f752d598-f81d-492c-9126-0702f0b4af92",
            "sourceColumn": "fiscal_year",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarYearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7f22d297-b13a-49e0-a5b7-b261aba0736d",
            "sourceColumn": "CalendarYearMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarMonthNameYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm yyyy",
            "lineageTag": "80b640ec-10da-42af-9976-27297e552fba",
            "sourceColumn": "CalendarMonthNameYear",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_ee449bc3-2cb8-4430-9c1f-d230ea3cc726"
                },
                "isDefault": true,
                "relationship": "35f507c6-97e2-46b5-b366-825656879983"
              }
            ]
          },
          {
            "name": "SnapshotDate - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "9c03ee1b-d997-4b3a-9769-aa9bb09e8c10",
            "sourceColumn": "SnapshotDate - Copy",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a04394d1-20be-4d7a-8ced-363cd252879d"
                },
                "isDefault": true,
                "relationship": "d3bb4120-82b9-4e57-815d-ed429a83c6e7"
              }
            ]
          },
          {
            "name": "WeekNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "36571858-0763-4477-a78f-bd81e0f54627",
            "sourceColumn": "WeekNumber",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59b562f8-eabd-493d-8998-2489f51e1a07",
            "sourceColumn": "Head_Of_Operations",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarMonthNameYear - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              },
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "yyyy-mm",
            "lineageTag": "69dc0416-6f34-425c-b989-03d491ef9934",
            "sourceColumn": "CalendarMonthNameYear - Copy",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0fa806a5-90a9-4072-a8a9-275e2ac65b3d"
                },
                "isDefault": true,
                "relationship": "d11cd7de-afec-4eca-b92f-c00ac14cade2"
              }
            ]
          },
          {
            "name": "WeekEnd Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              }
            ],
            "dataType": "dateTime",
            "formatString": "dd/mm/yyyy",
            "lineageTag": "981d40b9-b484-4db2-97e1-5984c98d51d7",
            "sourceColumn": "WeekEnd Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_b4e98804-ed73-46c7-adef-0b320e68ac96"
                },
                "isDefault": true,
                "relationship": "3e156957-5abc-4ad7-8be9-c1c19675e64d"
              }
            ]
          },
          {
            "name": "WeekDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "FormatString"
              },
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "dateTime",
            "expression": "CALCULATE(MAX(SnapshotRiskbytype[SnapshotDate - Copy]),ALLEXCEPT(SnapshotRiskbytype,SnapshotRiskbytype[WeekNumber]))",
            "formatString": "dd/mm/yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "c9334186-4142-49ca-98f6-61a852bfdb50",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_8c3691f2-59b0-4e87-ad93-2943ed2dc02b"
                },
                "isDefault": true,
                "relationship": "39df39e7-6019-42ee-8529-35e7370e226b"
              }
            ]
          },
          {
            "name": "SOURCE - Copy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40b73492-70d2-425a-a656-86eefded2e86",
            "sourceColumn": "SOURCE - Copy",
            "summarizeBy": "none"
          },
          {
            "name": "FacilityName - Drill Through",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67b15c96-67a0-4539-a617-1d2dedb0e6f6",
            "sourceColumn": "FacilityName - Drill Through",
            "summarizeBy": "none"
          },
          {
            "name": "Head of Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "573563e2-34a2-451e-a1a3-0a301f15678e",
            "sourceColumn": "Head of Operations",
            "summarizeBy": "none"
          },
          {
            "name": "SOURCE - Drill Through",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0ed0eb2-9445-47df-8cc5-5c1b7989b909",
            "sourceColumn": "SOURCE - Drill Through",
            "summarizeBy": "none"
          },
          {
            "name": "WeekNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "01e2c4dd-40fb-405a-9bf9-906c1e5b0bb8",
            "sourceColumn": "WeekNum",
            "summarizeBy": "sum"
          },
          {
            "name": "Column 2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKNUM(SnapshotRiskbytype[SnapshotDate - Copy])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "7aeeb820-863e-4850-ab2d-9012051c7cbd",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "SOURCE Drill Through",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "702d3612-74dd-4e53-9d3a-5f092a5b77ba",
            "sourceColumn": "SOURCE Drill Through",
            "summarizeBy": "none"
          },
          {
            "name": "Month Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(RIGHT(SnapshotRiskbytype[CalendarYearMonth],2),\"-\"),LEFT(SnapshotRiskbytype[CalendarYearMonth],4))",
            "isDataTypeInferred": true,
            "lineageTag": "e15d3af5-5ad9-45f5-afe3-3f1af6762db3",
            "sortByColumn": "CalendarYearMonth",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Column",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF(SnapshotRiskbytype[RiskValue]in{3,4},\"bad\",\"good\")",
            "isDataTypeInferred": true,
            "lineageTag": "217cfbc9-121d-481e-8fed-edc324866a31",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "    VALUE(LEFT([CalendarYearMonth], 4)),",
              "    VALUE(RIGHT([CalendarYearMonth], 2)),",
              "    1",
              ")",
              ""
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "69816d50-bc9a-407c-8b94-419720d1ee4c",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e50f56d3-ada2-4687-886c-83e896ca9442"
                },
                "isDefault": true,
                "relationship": "7f117174-c50c-49c7-a4e3-0303ab44ad3c"
              }
            ]
          },
          {
            "name": "CalendarMonthNameYear_Short",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(LEFT(SnapshotRiskbytype[Month_Name],3),\" \"),RIGHT(SnapshotRiskbytype[calendar_year],4))",
            "isDataTypeInferred": true,
            "lineageTag": "93a3323d-f7c1-4c49-989f-35433f02bb50",
            "sortByColumn": "CalendarYearMonth",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "HASH KEY",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(CONCATENATE(SnapshotRiskbytype[FacilityCode],SnapshotRiskbytype[ServIceName]),SnapshotRiskbytype[fiscal_month])",
            "isDataTypeInferred": true,
            "lineageTag": "150ac458-e977-43c4-a569-8223ba46dd3f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ServIceName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "SUBSTITUTE('SnapshotRiskbytype'[FacilityName], \" \", \"\")",
            "isDataTypeInferred": true,
            "lineageTag": "f4ded85d-9afb-42f7-871c-e7c4fa57e276",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": "DATEVALUE(FORMAT(SnapshotRiskbytype[SnapshotDate - Copy], \"yyyy-mm\"))",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "95d67760-792b-4740-ae46-a2bacf2fe8a4",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_412af3c3-2343-4649-86dd-f10f833f1a4b"
                },
                "isDefault": true,
                "relationship": "b1ba1d15-dfce-43aa-8883-df7b1c5d26e5"
              }
            ]
          },
          {
            "name": "Source_RiskValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE(SnapshotRiskbytype[SOURCE],SnapshotRiskbytype[RiskValue])",
            "isDataTypeInferred": true,
            "lineageTag": "89e95342-b503-4a27-9e21-279fe809dd05",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Head of Operations_Revised)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "IF(SnapshotRiskbytype[Head_Of_Operations]=\"kate durband\",\"Emma Bagley\",SnapshotRiskbytype[Head_Of_Operations])",
              "",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "264e9db7-14ed-4093-a2f8-a2902e58e62e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "HOA_FiscalMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "CONCATENATE(IF('SnapshotRiskbytype'[Head of Operations]=\"Emma Bagley\",\"kate Durband\"),SnapshotRiskbytype[fiscal_month])",
              "//CONCATENATE(SnapshotRiskbytype[Head_Of_Operations],SnapshotRiskbytype[fiscal_month])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "3f7169d1-e5c8-4a07-b242-50b6de14fbc6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Head_Of_Operations  DB",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46232d00-0192-4952-9850-d386e94b5565",
            "sourceColumn": "Head_Of_Operations  DB",
            "summarizeBy": "none"
          },
          {
            "name": "HOA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f7a6caa8-904b-4dff-aa9b-a75a98b5c00a",
            "sourceColumn": "HOA",
            "summarizeBy": "none"
          },
          {
            "name": "Current Month Slicer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "    IF(",
              "    MONTH('SnapshotRiskbytype'[CalendarMonthNameYear]) = MONTH(TODAY()) && YEAR('SnapshotRiskbytype'[CalendarMonthNameYear]) = YEAR(TODAY()),",
              "    \"Current Month\",",
              "    //FORMAT('SnapshotRiskbytype'[Date], \"MMMM YYYY\")",
              "    FORMAT('SnapshotRiskbytype'[CalendarMonthNameYear],\"MMMM YYYY\")",
              "",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "d42bba17-f216-4e4c-8cdd-95cb4564f58a",
            "sortByColumn": "CalendarMonthNameYear",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "732c2e02-8764-4aca-bb12-6abaa059d366",
        "measures": [
          {
            "name": "FacilityCount",
            "expression": "CALCULATE(DISTINCTCOUNT(SnapshotRiskbytype[FacilityName]),FILTER(SnapshotRiskbytype,SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate])))",
            "formatString": "0",
            "lineageTag": "6db2877a-80bd-4e90-9b0c-4ffa359259c0"
          },
          {
            "name": "Risk value",
            "expression": "CALCULATE(SUM(SnapshotRiskbytype[RiskValue]),SnapshotRiskbytype[SOURCE]<>\"TOTALRISK\",SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
            "formatString": "0",
            "lineageTag": "49058ce5-51c9-4291-867e-1bb4f844af70"
          },
          {
            "name": "Measure 6",
            "annotations": [
              {
                "name": "43dbc3e8-3a1c-4b6f-9923-b49ff7d6691c",
                "value": "True"
              }
            ],
            "lineageTag": "aae39d2a-749b-46e3-8f04-c6a0feb0abc3"
          },
          {
            "name": "Risk value Good",
            "expression": "CALCULATE([Risk value],SnapshotRiskbytype[RiskValue] in {0,1,2},VW_Risk_Level_Groups[RiskGroup]=\"good\")",
            "formatString": "0",
            "lineageTag": "ff1f6793-770d-406c-82d5-a820cef9a43b"
          },
          {
            "name": "Risk value bad",
            "expression": "CALCULATE([Risk value],SnapshotRiskbytype[RiskValue] in {3,4},VW_Risk_Level_Groups[RiskGroup]<>\"good\")",
            "formatString": "0",
            "lineageTag": "03462bc3-4c42-4aae-aae8-acfd05b7349f"
          },
          {
            "name": "Max Risk value",
            "expression": "CALCULATE(AVERAGE(SnapshotRiskbytype[RiskValue]),SnapshotRiskbytype[SnapshotDate]=MAX(SnapshotRiskbytype[SnapshotDate]))",
            "formatString": "0",
            "lineageTag": "6dc9ad7e-d1d1-4a6f-bae8-a0816ceccd65"
          },
          {
            "name": "Measure 8",
            "expression": "CALCULATE(SELECTEDVALUE(SnapshotRiskbytype[Head of Operations_Revised)],))",
            "lineageTag": "31be7290-7d8e-488b-9f7c-b07e0e2e1b71"
          }
        ],
        "partitions": [
          {
            "name": "SnapshotRiskbytype-1fdf5e2f-55b2-4530-842b-7cb302b927e3",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\"),",
                "    ATDMP = Source{[Name=\"ATDMP\"]}[Data],",
                "    dbo_SnapshotRiskbytype = ATDMP{[Schema=\"dbo\",Item=\"SnapshotRiskbytype\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_SnapshotRiskbytype, each true),",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"Filtered Rows\", \"SnapshotDate\", \"SnapshotDate - Copy\"),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Duplicated Column\",{{\"SnapshotDate - Copy\", type date}}),",
                "    #\"Duplicated Column1\" = Table.DuplicateColumn(#\"Changed Type\", \"SnapshotDate - Copy\", \"SnapshotDate - Copy - Copy\"),",
                "    #\"Calculated Week of Month\" = Table.TransformColumns(#\"Duplicated Column1\",{{\"SnapshotDate - Copy - Copy\", Date.WeekOfMonth, Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Calculated Week of Month\",{{\"SnapshotDate - Copy - Copy\", \"WeekNumber\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"CalendarMonthNameYear\", type date}}),",
                "    #\"Duplicated Column2\" = Table.DuplicateColumn(#\"Changed Type1\", \"CalendarMonthNameYear\", \"CalendarMonthNameYear - Copy\"),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Duplicated Column2\",{{\"CalendarMonthNameYear - Copy\", type text}}),",
                "    #\"Duplicated Column3\" = Table.DuplicateColumn(#\"Changed Type2\", \"SnapshotDate - Copy\", \"SnapshotDate - Copy - Copy\"),",
                "    #\"Calculated End of Week\" = Table.TransformColumns(#\"Duplicated Column3\",{{\"SnapshotDate - Copy - Copy\", Date.EndOfWeek, type date}}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Calculated End of Week\",{{\"SnapshotDate - Copy - Copy\", \"WeekEnd Date\"}}),",
                "    #\"Changed Type3\" = Table.TransformColumnTypes(#\"Renamed Columns1\",{{\"WeekNumber\", type text}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type3\",\"1\",\"1st Week\",Replacer.ReplaceText,{\"WeekNumber\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"2\",\"2nd Week\",Replacer.ReplaceText,{\"WeekNumber\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"3\",\"3rd Week\",Replacer.ReplaceText,{\"WeekNumber\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"4\",\"4th Week\",Replacer.ReplaceText,{\"WeekNumber\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\"5\",\"5th Week\",Replacer.ReplaceText,{\"WeekNumber\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\"6\",\"6th Week\",Replacer.ReplaceText,{\"WeekNumber\"}),",
                "    #\"Duplicated Column4\" = Table.DuplicateColumn(#\"Replaced Value5\", \"SOURCE\", \"SOURCE - Copy\"),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Duplicated Column4\",\"TotalRisk\",\"Number of Services after Total Risk\",Replacer.ReplaceText,{\"SOURCE - Copy\"}),",
                "    #\"Replaced Value7\" = Table.ReplaceValue(#\"Replaced Value6\",\"Number of services after total risk\",\"Total Risk by Number of ervices\",Replacer.ReplaceText,{\"SOURCE - Copy\"}),",
                "    #\"Replaced Value8\" = Table.ReplaceValue(#\"Replaced Value7\",\"Number of services after total risk\",\"Total Risk by Number of Service\",Replacer.ReplaceText,{\"SOURCE - Copy\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value8\",{\"SOURCE - Copy\"}),",
                "    #\"Duplicated Column5\" = Table.DuplicateColumn(#\"Removed Columns\", \"SOURCE\", \"SOURCE - Copy\"),",
                "    #\"Replaced Value9\" = Table.ReplaceValue(#\"Duplicated Column5\",\"TotalRisk\",\"Total Risk by Number of Service\",Replacer.ReplaceText,{\"SOURCE - Copy\"}),",
                "    #\"Replaced Value10\" = Table.ReplaceValue(#\"Replaced Value9\",\"Total Risk by number of service\",\"Total Risk by Number of Services\",Replacer.ReplaceText,{\"SOURCE - Copy\"}),",
                "    #\"Replaced Value11\" = Table.ReplaceValue(#\"Replaced Value10\",\"Total Risk by Number of Service\",\"Total Risk by Number of Services\",Replacer.ReplaceText,{\"SOURCE - Copy\"}),",
                "    #\"Replaced Value12\" = Table.ReplaceValue(#\"Replaced Value11\",\"Team Member Attrition Risk\",\"Team Attrition Risk\",Replacer.ReplaceText,{\"SOURCE\"}),",
                "    #\"Replaced Value13\" = Table.ReplaceValue(#\"Replaced Value12\",\"CQC Registered Manager Risk\",\"CQC Regd Mgr Risk\",Replacer.ReplaceText,{\"SOURCE\"}),",
                "    #\"Replaced Value14\" = Table.ReplaceValue(#\"Replaced Value13\",\"\",\"\",Replacer.ReplaceValue,{\"SOURCE\"}),",
                "    #\"Replaced Value15\" = Table.ReplaceValue(#\"Replaced Value14\",\"Rgional Manager\",\"Regional Manager\",Replacer.ReplaceText,{\"SOURCE\"}),",
                "    #\"Replaced Value16\" = Table.ReplaceValue(#\"Replaced Value15\",\"rgional Manager Risk\",\"Regional Manager Risk\",Replacer.ReplaceText,{\"SOURCE\"}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Replaced Value16\", each true),",
                "    #\"Duplicated Column6\" = Table.DuplicateColumn(#\"Filtered Rows1\", \"FacilityName\", \"FacilityName - Copy\"),",
                "    #\"Renamed Columns2\" = Table.RenameColumns(#\"Duplicated Column6\",{{\"FacilityName - Copy\", \"FacilityName - Drill Through\"}}),",
                "    #\"Duplicated Column7\" = Table.DuplicateColumn(#\"Renamed Columns2\", \"SOURCE - Copy\", \"SOURCE - Copy - Copy\"),",
                "    #\"Renamed Columns3\" = Table.RenameColumns(#\"Duplicated Column7\",{{\"SOURCE - Copy - Copy\", \"SOURCE - Drill Through\"}}),",
                "    #\"Duplicated Column8\" = Table.DuplicateColumn(#\"Renamed Columns3\", \"Head_Of_Operations\", \"Head_Of_Operations - Copy\"),",
                "    #\"Renamed Columns4\" = Table.RenameColumns(#\"Duplicated Column8\",{{\"Head_Of_Operations - Copy\", \"Head of Operations\"}}),",
                "    #\"Duplicated Column9\" = Table.DuplicateColumn(#\"Renamed Columns4\", \"SOURCE\", \"SOURCE - Copy.1\"),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Duplicated Column9\",{\"SOURCE - Drill Through\"}),",
                "    #\"Renamed Columns5\" = Table.RenameColumns(#\"Removed Columns1\",{{\"SOURCE - Copy.1\", \"SOURCE - Drill Through\"}}),",
                "    #\"Replaced Value17\" = Table.ReplaceValue(#\"Renamed Columns5\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head_Of_Operations\"}),",
                "    #\"Replaced Value18\" = Table.ReplaceValue(#\"Replaced Value17\",\"hOLLY mCENEANEY\",\"TBC\",Replacer.ReplaceText,{\"Head of Operations\"}),",
                "    #\"Replaced Value19\" = Table.ReplaceValue(#\"Replaced Value18\",\"Holly Mceneaney\",\"TBC\",Replacer.ReplaceText,{\"Head of Operations\"}),",
                "    #\"Duplicated Column10\" = Table.DuplicateColumn(#\"Replaced Value19\", \"SnapshotDate - Copy\", \"SnapshotDate - Copy - Copy\"),",
                "    #\"Calculated Week of Month1\" = Table.TransformColumns(#\"Duplicated Column10\",{{\"SnapshotDate - Copy - Copy\", Date.WeekOfMonth, Int64.Type}}),",
                "    #\"Renamed Columns6\" = Table.RenameColumns(#\"Calculated Week of Month1\",{{\"SnapshotDate - Copy - Copy\", \"WeekNum\"}}),",
                "    #\"Duplicated Column11\" = Table.DuplicateColumn(#\"Renamed Columns6\", \"SOURCE - Drill Through\", \"SOURCE - Drill Through - Copy\"),",
                "    #\"Renamed Columns7\" = Table.RenameColumns(#\"Duplicated Column11\",{{\"SOURCE - Drill Through - Copy\", \"SOURCE Drill Through\"}}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Renamed Columns7\", each true),",
                "    #\"Duplicated Column12\" = Table.DuplicateColumn(#\"Filtered Rows2\", \"Head of Operations\", \"Head of Operations - Copy\"),",
                "    #\"Replaced Value20\" = Table.ReplaceValue(#\"Duplicated Column12\",\"Kate Durband\",\"Reporting\",Replacer.ReplaceText,{\"Head of Operations - Copy\"}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Replaced Value20\",{\"Head of Operations - Copy\"}),",
                "    #\"Duplicated Column13\" = Table.DuplicateColumn(#\"Removed Columns2\", \"Head_Of_Operations\", \"Head_Of_Operations - Copy\"),",
                "    #\"Renamed Columns8\" = Table.RenameColumns(#\"Duplicated Column13\",{{\"Head_Of_Operations - Copy\", \"Head_Of_Operations  DB\"}}),",
                "    #\"Replaced Value21\" = Table.ReplaceValue(#\"Renamed Columns8\",\"kate Durband\",\"Reporting\",Replacer.ReplaceText,{\"Head_Of_Operations\"}),",
                "    #\"Replaced Value22\" = Table.ReplaceValue(#\"Replaced Value21\",\"Kate Durband\",\"Emma Bagley\",Replacer.ReplaceText,{\"Head_Of_Operations\"})",
                "in",
                "    #\"Replaced Value22\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a04394d1-20be-4d7a-8ced-363cd252879d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "90f4b9de-dce4-432d-9673-9578576e347c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b4a33fd8-b33d-4d07-aabd-aed358ff4402",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0c772698-05de-48ee-97ed-80a751a122b1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4f4835f3-86fa-4ac2-a701-c7365771afcc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bf3d8bc2-1bb2-4f50-bdc9-021fe4b325cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0ae2fde9-9f6e-4a5f-a846-f00342468664",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "afb7902e-194f-4c04-bfdd-343228a24d41",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "05b65e24-49f6-4f6d-a7c9-0ff06cb749e2",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "329f2beb-5370-423d-9f67-e4e9da75f876",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "750259a8-645f-40d2-81f4-b45a5bf1fdbe",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "87bed2fd-0e94-46f4-beac-1b7d3d93a3b1",
                "ordinal": 3
              }
            ],
            "lineageTag": "438eeae8-0045-4241-acb1-a7e1ae9d91e2"
          }
        ],
        "isHidden": true,
        "lineageTag": "5ade1c8a-ff05-4825-8547-b2c1f324d3e7",
        "partitions": [
          {
            "name": "LocalDateTable_a04394d1-20be-4d7a-8ced-363cd252879d-f78c8e2f-aef9-4c10-b499-a950c12160a3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SnapshotRiskbytype'[SnapshotDate - Copy])), 1, 1), Date(Year(MAX('SnapshotRiskbytype'[SnapshotDate - Copy])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_0fa806a5-90a9-4072-a8a9-275e2ac65b3d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9d9840a3-0672-4e43-840e-156c56f97e51",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ca569cf6-7a62-4c2f-a018-1887909167a3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "76deb904-4d0f-4fff-9a36-1a8f743edfc2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7ed13220-34be-419e-97c0-0558a45e56e1",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2284064a-3045-460e-bee6-386d7da0e22f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8e4a004e-3917-4c60-bd2c-551b365c0fe6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "53eb338a-446a-452e-b6bf-102cc56ff574",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a2474bee-c2c9-495f-9864-cdd1d09449f0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c73ad17a-daeb-4112-9549-d3e2af868462",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "57f4f3db-f194-409e-9c37-5d8e01d70f64",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "73bd4e3e-9af9-4485-90fc-ab03fec2387d",
                "ordinal": 3
              }
            ],
            "lineageTag": "0f047696-12e9-4853-995a-670f56ab9a34"
          }
        ],
        "isHidden": true,
        "lineageTag": "5c055cbd-c455-4ac7-a2d2-d1d497c3b4c2",
        "partitions": [
          {
            "name": "LocalDateTable_0fa806a5-90a9-4072-a8a9-275e2ac65b3d-db5e8327-06b8-44b8-8e85-134801efb1a2",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SnapshotRiskbytype'[CalendarMonthNameYear - Copy])), 1, 1), Date(Year(MAX('SnapshotRiskbytype'[CalendarMonthNameYear - Copy])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b4e98804-ed73-46c7-adef-0b320e68ac96",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9deb2d05-ab12-489a-9481-478355b48322",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "63d158c2-007d-4e65-a08a-551389e83a64",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "375f52b2-506f-49f5-b071-17f917102ecb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c44c05f0-4768-42c0-93c0-7d9279e3c699",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ca94ad55-d094-4b08-8f6f-a7d4b4313437",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "652ea7e7-e85b-4358-94d8-d73cb6023b02",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c2097720-7209-43cc-9334-b206e96d38b6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2c4a3061-466f-4c1d-8420-98dd6ef7cb16",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fdcbf0ac-a129-4055-b586-02f6b97275f2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6e4ee34f-de57-4788-afa2-a910125da75f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3e6b677e-6fdf-4578-955e-33ff6b929107",
                "ordinal": 3
              }
            ],
            "lineageTag": "2e21eb0b-a2eb-441e-bedb-bdbd3f827f3c"
          }
        ],
        "isHidden": true,
        "lineageTag": "acafbdb6-82d7-4593-b612-9a04ff58a5b1",
        "partitions": [
          {
            "name": "LocalDateTable_b4e98804-ed73-46c7-adef-0b320e68ac96-b4c845bd-0f5e-4c54-b651-0f802121d1bf",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SnapshotRiskbytype'[WeekEnd Date])), 1, 1), Date(Year(MAX('SnapshotRiskbytype'[WeekEnd Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_8c3691f2-59b0-4e87-ad93-2943ed2dc02b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ceb7900a-13f5-4627-9a82-5d8a68ee400c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "cfb7e6ec-e88c-4fc9-aa48-2a4b975375d4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9e3acbcb-2896-4fe1-8d72-061d9afc7666",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fdeb7737-06a6-4adb-9c39-e60cba52f63c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7494a5e7-2e3c-4940-afbe-e63ecf77137c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "58902ffe-c506-4d5c-9c9f-12781b9787d8",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7ee10343-8854-44cd-b26a-4659cacf4ef2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "fe290a8f-46b3-47e8-bfeb-6d4291b85c19",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "3e428e43-888a-4c41-b471-91c727c401ae",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "072aa871-ce54-4ec1-a427-568ce2ac23f2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fe8ccb54-9e11-440e-b38c-6be1477bb212",
                "ordinal": 3
              }
            ],
            "lineageTag": "b8ca2120-e184-42af-9e21-f737a2cd7c3a"
          }
        ],
        "isHidden": true,
        "lineageTag": "c301f2fc-27fc-4c01-b420-da087ece0f64",
        "partitions": [
          {
            "name": "LocalDateTable_8c3691f2-59b0-4e87-ad93-2943ed2dc02b-2a092d76-219c-4ffe-9d36-b65bad3b7372",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SnapshotRiskbytype'[WeekDate])), 1, 1), Date(Year(MAX('SnapshotRiskbytype'[WeekDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_ee449bc3-2cb8-4430-9c1f-d230ea3cc726",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ab554fb5-a179-411e-8ab7-db367337325c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5f63b23d-9bc8-4725-af42-7b4eb9e6f504",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0f380a59-de34-46e6-9845-6be9072e24eb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "83cac1e7-4b8e-4fcc-8a47-2585b4d54b6a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d52d590d-88c5-43bb-b57c-aa88f70e5105",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1da9224c-895f-471c-91ae-cfbf8b453f11",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d81d9e47-a476-4039-9843-321d91f04926",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d785c877-b907-4998-88ad-0efaff7e3a83",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "99ddd6ac-8502-4400-9c22-0de759b8d872",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0ece9721-d402-4f1c-b3fc-5af2aea13619",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e64bff3d-b2dc-4405-881d-d5ae183f128b",
                "ordinal": 3
              }
            ],
            "lineageTag": "e7e83d57-75bf-47c0-a503-1455f6132197"
          }
        ],
        "isHidden": true,
        "lineageTag": "8349b05c-c21c-453a-a850-fba9b798e9aa",
        "partitions": [
          {
            "name": "LocalDateTable_ee449bc3-2cb8-4430-9c1f-d230ea3cc726-e8700ec0-cbc8-42a6-8057-3a6df5d548d3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SnapshotRiskbytype'[CalendarMonthNameYear])), 1, 1), Date(Year(MAX('SnapshotRiskbytype'[CalendarMonthNameYear])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Measure for Mnthly Dashboard",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fee0bc6d-6ca2-41cf-8cf3-8ed07fc33c00",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "Rating",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8500581f-e453-4e1e-a6a3-ca1df0cb0154",
            "sourceColumn": "Rating",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "facf915b-26dc-4943-a688-95d55a6e85a2",
        "measures": [
          {
            "name": "Monthly CQC Inspection",
            "expression": "sum(ServiceRiskAnalysisCombined[CQCinspectionRisk])",
            "formatString": "0",
            "lineageTag": "542b9ac5-32bd-4442-b0c7-06146394bfbc"
          },
          {
            "name": "Monthly CQC Registered Manager Risk",
            "expression": "sum(ServiceRiskAnalysisCombined[Manager_Registered_with_CQC])",
            "formatString": "0",
            "lineageTag": "952a6dab-1d3f-4b1b-bf74-84f62747d421"
          },
          {
            "name": "Monthly Internal Audit Risk",
            "expression": "sum(ServiceRiskAnalysisCombined[InternalAuditRisk])",
            "formatString": "0",
            "lineageTag": "9497cd84-002b-4a5c-b910-424db11eecee"
          },
          {
            "name": "Monthly Agency Cost Risk",
            "expression": "sum(ServiceRiskAnalysisCombined[Agency_cost_pct])",
            "formatString": "0",
            "lineageTag": "ccca1e4d-f60f-4cfc-95c1-4cc274222890"
          },
          {
            "name": "Monthly CQC Inherited Rating Risk",
            "expression": "sum(ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated])",
            "formatString": "0",
            "lineageTag": "234be4ea-9d7c-4a8f-8608-06378759f40f"
          },
          {
            "name": "Monthly Recruitment Risk",
            "expression": "sum(ServiceRiskAnalysisCombined[RecruitmentRisk])",
            "formatString": "0",
            "lineageTag": "960ff40f-8a10-424f-bac3-7f220cf660bb"
          },
          {
            "name": "Monthly Rgional Manager Risk",
            "expression": "sum(ServiceRiskAnalysisCombined[RegionalMGR_Risk])",
            "formatString": "0",
            "lineageTag": "8a680892-fae6-4819-81cf-711815374e45"
          },
          {
            "name": "Monthly Team Member Attrition Risk",
            "expression": "sum(ServiceRiskAnalysisCombined[MGRTurnOver_Risk])",
            "formatString": "0",
            "lineageTag": "a9b02015-6df7-4930-a1fe-aa38f2b3a211"
          },
          {
            "name": "Monthly ManagerVacancies Risk",
            "expression": "sum(ServiceRiskAnalysisCombined[Manager_present_at_service])",
            "formatString": "0",
            "lineageTag": "3bdf96f2-302b-4dfe-b2ca-2c91c875011a"
          },
          {
            "name": "Dynamic selection",
            "expression": [
              "",
              "SELECTEDVALUE ( 'Measure for Mnthly Dashboard'[id], 1 )"
            ],
            "formatString": "0",
            "lineageTag": "e6ca6937-5472-493d-acc5-1715e92f7dfd"
          },
          {
            "name": "Dynamic Switch",
            "expression": [
              "",
              "",
              "    ",
              "",
              "SWITCH (",
              "    [Dynamic selection],",
              "    1, [Monthly Agency Cost Risk],",
              "    2, [Monthly CQC Inherited Rating Risk],",
              "    3, [Monthly ManagerVacancies Risk],",
              "    4, [Monthly Recruitment Risk],",
              "    5, [Monthly Rgional Manager Risk],",
              "    6,[Monthly Team Member Attrition Risk],",
              "    7,[Monthly CQC Inspection],",
              "    8,[Monthly CQC Registered Manager Risk],",
              "    9,[Monthly Internal Audit Risk]",
              ")",
              "",
              "--return IF(SELECTEDVALUE('Table'[ID]),a,[Combined Risk Monthly])"
            ],
            "formatString": "0",
            "lineageTag": "9ed88d34-285b-482d-881a-d23b9184c833"
          },
          {
            "name": "Combined Risk Monthly",
            "expression": "[Monthly Agency Cost Risk]+[Monthly CQC Inherited Rating Risk]+[Monthly CQC Inspection]+[Monthly CQC Registered Manager Risk]+[Monthly Internal Audit Risk]+[Monthly ManagerVacancies Risk]+[Monthly Recruitment Risk]+[Monthly Rgional Manager Risk]+[Monthly Team Member Attrition Risk]",
            "formatString": "0",
            "lineageTag": "983bbbbb-b87b-479c-9b84-14072d6ab398"
          },
          {
            "name": "Good Risk Level",
            "expression": [
              "var a=CALCULATE(SUM(ServiceRiskAnalysisCombined[Agency_cost_pct]),ServiceRiskAnalysisCombined[Agency_cost_pct] in {0,1,1} ) ",
              "var b=CALCULATE(SUM(ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated]),ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated] in {0,1,2})",
              " var c=                               CALCULATE(SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk]),ServiceRiskAnalysisCombined[CQCinspectionRisk] in {0,1,2} )",
              "    var d=                             CALCULATE(SUM(ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]),ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] in {0,1,2})",
              "     var e=                              CALCULATE(SUM(ServiceRiskAnalysisCombined[InternalAuditRisk]),ServiceRiskAnalysisCombined[InternalAuditRisk] in {0,1,2})",
              "         var f=                            CALCULATE(SUM(ServiceRiskAnalysisCombined[Manager_present_at_service]),ServiceRiskAnalysisCombined[Manager_present_at_service] in {0,1,2})",
              "            var g=                          CALCULATE(SUM(ServiceRiskAnalysisCombined[RecruitmentRisk]),ServiceRiskAnalysisCombined[RecruitmentRisk] in {0,1,2})",
              "              var h=                          CALCULATE(SUM(ServiceRiskAnalysisCombined[RegionalMGR_Risk]),ServiceRiskAnalysisCombined[RegionalMGR_Risk] in {0,1,2})",
              "                  var i=                       CALCULATE(SUM(ServiceRiskAnalysisCombined[MGRTurnOver_Risk]),ServiceRiskAnalysisCombined[MGRTurnOver_Risk] in {0,1,2})",
              "                  return a+b+c+d+e+f+g+h+i",
              "                                    ",
              "                                    "
            ],
            "formatString": "0",
            "lineageTag": "c07d023b-5384-4bf9-83b6-31f45f4f96db"
          },
          {
            "name": "Qudrant line",
            "expression": "CALCULATE(sum(ServiceRiskAnalysisCombined[TotalRisk]),ServiceRiskAnalysisCombined[TotalRisk]=10)",
            "formatString": "0",
            "lineageTag": "3aea4233-f2dc-401f-8458-d31ad3f28c67"
          },
          {
            "name": "Quadrant line",
            "expression": "CALCULATE([Dynamic Switch],VW_Risk_Level_Groups[RiskGroup]=\"No high Risk\")",
            "formatString": "0",
            "lineageTag": "078b0a6a-7584-4c7d-aeab-a16f6aa60b16"
          },
          {
            "name": "Bad Risk Level",
            "expression": [
              "var a=CALCULATE(SUM(ServiceRiskAnalysisCombined[Agency_cost_pct]),ServiceRiskAnalysisCombined[Agency_cost_pct] in {3,4} ) ",
              "var b=CALCULATE(SUM(ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated]),ServiceRiskAnalysisCombined[Inherited_rating_or_not_yet_rated] in {3,4})",
              " var c=                               CALCULATE(SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk]),ServiceRiskAnalysisCombined[CQCinspectionRisk] in {3,4} )",
              "    var d=                             CALCULATE(SUM(ServiceRiskAnalysisCombined[Manager_Registered_with_CQC]),ServiceRiskAnalysisCombined[Manager_Registered_with_CQC] in {3,4})",
              "     var e=                              CALCULATE(SUM(ServiceRiskAnalysisCombined[InternalAuditRisk]),ServiceRiskAnalysisCombined[InternalAuditRisk] in {3,4})",
              "         var f=                            CALCULATE(SUM(ServiceRiskAnalysisCombined[Manager_present_at_service]),ServiceRiskAnalysisCombined[Manager_present_at_service] in {3,4})",
              "            var g=                          CALCULATE(SUM(ServiceRiskAnalysisCombined[RecruitmentRisk]),ServiceRiskAnalysisCombined[RecruitmentRisk] in {3,4})",
              "              var h=                          CALCULATE(SUM(ServiceRiskAnalysisCombined[RegionalMGR_Risk]),ServiceRiskAnalysisCombined[RegionalMGR_Risk] in {3,4})",
              "                  var i=                       CALCULATE(SUM(ServiceRiskAnalysisCombined[MGRTurnOver_Risk]),ServiceRiskAnalysisCombined[MGRTurnOver_Risk] in {3,4})",
              "                  return a+b+c+d+e+f+g+h+i",
              "                                    "
            ],
            "formatString": "0",
            "lineageTag": "1f3a5252-99b5-4e0d-b533-08960708c669"
          },
          {
            "name": "Service with 2 high risk",
            "expression": "CALCULATE([Dynamic Switch],VW_Risk_Level_Groups[RiskGroup]=\"Service with 2 high risk\" )",
            "formatString": "0",
            "lineageTag": "d0986a75-8ec5-4db2-95f1-77bcfee8c573"
          },
          {
            "name": "Avg Total risk",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sum(ServiceRiskAnalysisCombined[TotalRisk]))",
            "lineageTag": "3a1c1050-6007-4961-a106-a63d9b71af0d"
          },
          {
            "name": "Switch",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SWITCH(TRUE(),SELECTEDMEASURE()=[Avg Total risk],[Distinct Facility Name],SUM(ServiceRiskAnalysisCombined[TotalRisk]))",
            "lineageTag": "513cf0b8-3dc7-4d2e-a438-9a0c38bdee35"
          },
          {
            "name": "Distinct Facility Name",
            "expression": "DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityName])",
            "formatString": "0",
            "lineageTag": "f2c87165-fcf0-4bd3-8d6c-c55ff565be26"
          },
          {
            "name": "Avg Faclities",
            "expression": "AVERAGEX(ServiceRiskAnalysisCombined,DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityName]))",
            "formatString": "0",
            "lineageTag": "5281912b-e74a-4563-ab42-261867c42ee0"
          },
          {
            "name": "Top 5 High risk 4 High risk",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "CALCULATE([Variance],VW_Risk_Level_Groups[RiskGroup]=\"Service with 3-4 High risk\"",
              " /*(CALCULATE(AVERAGE(ServiceRiskAnalysisCombined[TotalRisk]),VW_Risk_Level_Groups[RiskGroup]=\"service with 4 High risk\",TOPN(5,ServiceRiskAnalysisCombined,ServiceRiskAnalysisCombined[TotalRisk],DESC))*/",
              "   )"
            ],
            "lineageTag": "2b5cfe6f-2d48-46ed-8ddd-7ca79bc925d7"
          },
          {
            "name": "Measure",
            "expression": [
              "-- CALCULATE([Top 5 High risk],DATESINPERIOD(ServiceRiskAnalysisCombined[Date],MAX(ServiceRiskAnalysisCombined[Date]),-12,MONTH))",
              "var a=CALCULATE(MAX(ServiceRiskAnalysisCombined[Date]))",
              "var b =CALCULATETABLE(",
              "    VALUES('ServiceRiskAnalysisCombined'[Date]),",
              "    DATESBETWEEN(",
              "        'ServiceRiskAnalysisCombined'[Date],",
              "         DATEADD('ServiceRiskAnalysisCombined'[Date], -12, MONTH),",
              "        MAX('ServiceRiskAnalysisCombined'[Date])",
              "    )",
              ")",
              "",
              " return b",
              ""
            ],
            "formatString": "General Date",
            "lineageTag": "1e109df3-6757-4ca4-91d7-532af580d21a"
          },
          {
            "name": "Variance",
            "expression": [
              "var a= CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[Date]),all(VW_Reporting_Calendar[Date]))",
              "",
              "var b=CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-2,MONTH),all(VW_Reporting_Calendar[Date]))",
              "",
              "return a-b"
            ],
            "formatString": "0",
            "lineageTag": "a02e7ac8-b675-492f-afc8-37452641998e"
          },
          {
            "name": "Top 5 High risk more than 4 High risk",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "(CALCULATE([Variance],VW_Risk_Level_Groups[RiskGroup]=\"Service with 5 and over High Risk\"))",
            "lineageTag": "e2658996-8c13-4f7a-9cc3-d017f753aedf"
          },
          {
            "name": "Line Color CQC Inspection",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly CQC Inspection] in {0,1},\"#27B54D\",IF([Monthly CQC Inspection]=2,\"#0EAAF2\",IF([Monthly CQC Inspection]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              ")))"
            ],
            "lineageTag": "8fa6f0fc-6864-4e85-9348-d3fef199a8a2"
          },
          {
            "name": "Line Color agency",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly Agency Cost Risk] in {0,1},\"#27B54D\",IF([Monthly Agency Cost Risk]=2,\"#0EAAF2\",IF([Monthly Agency Cost Risk]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              ")))"
            ],
            "lineageTag": "cd32539e-92d8-492f-bc23-05c62b667ae3"
          },
          {
            "name": "Line Color regional",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly Rgional Manager Risk] in {0,1},\"#27B54D\",IF([Monthly Rgional Manager Risk]=2,\"#0EAAF2\",IF([Monthly Rgional Manager Risk]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              ")))"
            ],
            "lineageTag": "cb8b3b9d-3298-41d9-8215-c11eca01e68f"
          },
          {
            "name": "Line Color CQC Registered",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly CQC Registered Manager Risk] in {0,1},\"#27B54D\",IF([Monthly CQC Registered Manager Risk]=2,\"#0EAAF2\",IF([Monthly CQC Registered Manager Risk]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              ")))"
            ],
            "lineageTag": "93b0a347-5a44-47c7-9a8d-32a761fd7f28"
          },
          {
            "name": "Line Color Internal Audit",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly Internal Audit Risk] in {0,1},\"#27B54D\",IF([Monthly Internal Audit Risk]=2,\"#0EAAF2\",IF([Monthly Internal Audit Risk]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              ")))"
            ],
            "lineageTag": "a81a59db-3232-4a8d-9ac1-4245c8e58743"
          },
          {
            "name": "Line Color Manager Vac",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly ManagerVacancies Risk] in {0,1},\"#27B54D\",IF([Monthly ManagerVacancies Risk]=2,\"#0EAAF2\",IF([Monthly ManagerVacancies Risk]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              ")))"
            ],
            "lineageTag": "7483eff7-206d-47f5-9232-da1bb963af08"
          },
          {
            "name": "Line Color Team Member",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly Team Member Attrition Risk] in {0,1},\"#27B54D\",IF([Monthly Team Member Attrition Risk]=2,\"#0EAAF2\",IF([Monthly Team Member Attrition Risk]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              "))) "
            ],
            "lineageTag": "48217821-30f9-4513-ad7f-7d1f95999c46"
          },
          {
            "name": "Line Color Recruitment",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly Recruitment Risk] in {0,1},\"#27B54D\",IF([Monthly Recruitment Risk]=2,\"#0EAAF2\",IF([Monthly Recruitment Risk]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              ")))"
            ],
            "lineageTag": "90e20a9b-0519-4f94-968d-4f8f8aa81837"
          },
          {
            "name": "Last 3 Months date",
            "expression": [
              "--DATEADD(ServiceRiskAnalysisCombined[Date],-3,MONTH)",
              "CONCATENATE(CONCATENATE(LEFT(FORMAT(DATEADD(ServiceRiskAnalysisCombined[Date], -2, MONTH), \"mmm\"), 3),\" \"), RIGHT(FORMAT(DATEADD(ServiceRiskAnalysisCombined[Date], -3, MONTH), \"yyYY\"), 4))",
              ""
            ],
            "lineageTag": "c98a53e2-d8f0-4d5e-83d7-259e175350b2"
          },
          {
            "name": "Predictive",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "--CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),",
              "",
              "var a=DATEADD(ServiceRiskAnalysisCombined[Date],-3,MONTH)",
              "    --DATESBETWEEN(ServiceRiskAnalysisCombined[Date], LASTDATE(ServiceRiskAnalysisCombined[Date]), -3,MONTH )",
              "var b=CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATESINPERIOD(ServiceRiskAnalysisCombined[Date],LASTDATE(ServiceRiskAnalysisCombined[Date]),1,YEAR))",
              "",
              "var c= CALCULATE(AVERAGE(ServiceRiskAnalysisCombined[TotalRisk]),SAMEPERIODLASTYEAR(ServiceRiskAnalysisCombined[Date]))",
              "return c",
              ""
            ],
            "lineageTag": "d7a39c0b-d1b9-452d-8e54-8c10f77dffde"
          },
          {
            "name": "Variance Line",
            "expression": "IF([Variance]<0,0)",
            "formatString": "0",
            "lineageTag": "3be1d773-f644-4af0-af38-50306ed02559"
          },
          {
            "name": "Monthly Training Compliance",
            "expression": "SUM(ServiceRiskAnalysisCombined[ElrngOverallComaliance])",
            "formatString": "0",
            "lineageTag": "6188e008-f42f-424e-953c-a98941aa62be"
          },
          {
            "name": "Monthly F2F Compliance",
            "expression": "SUM(ServiceRiskAnalysisCombined[F2FOverallComaliance])",
            "formatString": "0",
            "lineageTag": "6e7a39ca-301b-408a-bcc0-341cace9f2ab"
          },
          {
            "name": "Line Color E-Learning Audit",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly Training Compliance] in {0,1},\"#27B54D\",IF([Monthly Training Compliance]=2,\"#0EAAF2\",IF([Monthly Training Compliance]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              ")))"
            ],
            "lineageTag": "0c7dee2b-bfd9-499e-917d-9566a23fe528"
          },
          {
            "name": "Line Color F2F Audit",
            "expression": [
              "IF (",
              "    ISFILTERED(ServiceRiskAnalysisCombined[Service Name]),IF([Monthly F2F Compliance] in {0,1},\"#27B54D\",IF([Monthly F2F Compliance]=2,\"#0EAAF2\",IF([Monthly F2F Compliance]>=3,",
              "\"#FD625E\"",
              "",
              ")",
              "",
              "",
              "",
              "",
              "",
              ")))"
            ],
            "lineageTag": "a5944870-c440-4b68-b13b-153c582f74b9"
          },
          {
            "name": "Teext Swtich",
            "expression": [
              "CALCULATE(",
              "    SUM('ServiceRiskAnalysisCombined'[TotalRisk]),",
              "    'VW_Reporting_Calendar'[calendar_quarter] = CALCULATE(",
              "        MAX('VW_Reporting_Calendar'[calendar_quarter]),",
              "        ALL('VW_Reporting_Calendar'),",
              "        'VW_Reporting_Calendar'[calendar_quarter] = \"Previous Quarter\"",
              "    )",
              ")"
            ],
            "lineageTag": "8ce90096-2856-45ae-82ef-c7cee55cbad6"
          },
          {
            "name": "Quarter_Current Quarter",
            "expression": [
              "var a=MAX(ServiceRiskAnalysisCombined[Date])",
              "",
              "var b=CALCULATE(AVERAGE(ServiceRiskAnalysisCombined[TotalRisk]),DATESINPERIOD(ServiceRiskAnalysisCombined[Date],a,-3,MONTH))",
              "",
              "return b"
            ],
            "formatString": "0",
            "lineageTag": "bea5ef6c-2fd2-4c3a-a0a9-b2d45ddcafce"
          },
          {
            "name": "quarter_Previous quarter",
            "expression": [
              "var a=DATEADD(ALLSELECTED(ServiceRiskAnalysisCombined[Date]),-3,MONTH)",
              "",
              "var b=CALCULATE(AVERAGE(ServiceRiskAnalysisCombined[TotalRisk]),DATESINPERIOD(ServiceRiskAnalysisCombined[Date],a,-3,MONTH))",
              "",
              "return b"
            ],
            "formatString": "0",
            "lineageTag": "5a58f75b-94a5-4719-bf34-74a3ccbff299"
          },
          {
            "name": "quarter_3RD",
            "expression": [
              "var a=DATEADD(ALLSELECTED(ServiceRiskAnalysisCombined[Date]),-6,MONTH)",
              "",
              "var b=CALCULATE(AVERAGE(ServiceRiskAnalysisCombined[TotalRisk]),DATESINPERIOD(ServiceRiskAnalysisCombined[Date],a,-3,MONTH))",
              "",
              "return b"
            ],
            "formatString": "0",
            "lineageTag": "5ffdf8a0-70b3-4e06-8c70-56d2535a3a4a"
          },
          {
            "name": "quarter_4TH",
            "expression": [
              "var a=DATEADD(ALLSELECTED(ServiceRiskAnalysisCombined[Date]),-9,MONTH)",
              "",
              "var b=CALCULATE(AVERAGE(ServiceRiskAnalysisCombined[TotalRisk]),DATESINPERIOD(ServiceRiskAnalysisCombined[Date],a,-3,MONTH))",
              "",
              "return b"
            ],
            "formatString": "0",
            "lineageTag": "13f2b172-ce3a-4361-b9a1-a99ef0f7878e"
          },
          {
            "name": "Arrows_Quarter",
            "expression": "IF([Quarter_Current Quarter]<[quarter_4TH],1,0)",
            "formatString": "0",
            "lineageTag": "d5b35020-bec1-445a-9a52-635f8f61f55d"
          },
          {
            "name": "Variance last 12 months",
            "expression": [
              "var a= CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[Date]))",
              "",
              "var b= CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-11,MONTH))",
              "",
              "return a-b"
            ],
            "formatString": "0",
            "lineageTag": "9336f73c-9c71-4a07-a96a-7b6e3d1822f9"
          },
          {
            "name": "Measure 2",
            "expression": "DATESINPERIOD(ServiceRiskAnalysisCombined[Date],a,-3,MONTH))",
            "lineageTag": "67b7efbd-4fd7-4309-aadf-3604ec43b2ca"
          },
          {
            "name": "Risk Prediction",
            "expression": [
              "",
              "Var A = CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-1,MONTH))",
              "",
              "Var B=CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-2,MONTH))",
              "",
              "Var C=CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-1,YEAR))",
              "",
              "Return DIVIDE(A+B+C,3,0)",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "739bf5db-ce07-4e84-be6d-59b7c4520b43"
          },
          {
            "name": "Prediction CQC Inspection",
            "expression": [
              "Var A = CALCULATE([Monthly CQC Inspection],DATEADD(ServiceRiskAnalysisCombined[Date],-1,MONTH))",
              "",
              "Var B=CALCULATE([Monthly CQC Inspection],DATEADD(ServiceRiskAnalysisCombined[Date],-2,MONTH))",
              "",
              "Var C=CALCULATE([Monthly CQC Inspection],DATEADD(ServiceRiskAnalysisCombined[Date],-1,YEAR))",
              "",
              "Return DIVIDE(A+B+C,3,0)"
            ],
            "formatString": "0",
            "lineageTag": "e81687c2-f75e-4a1f-a8bb-8dde3498995d"
          },
          {
            "name": "Prediction_CQC Inspection",
            "expression": "[Monthly CQC Inspection]*'Risk value'[Risk % Value]/100",
            "formatString": "0",
            "lineageTag": "ff43b4c9-256d-4404-bdb6-29997b20d475"
          },
          {
            "name": "Measure 3",
            "expression": "CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-2,MONTH))",
            "formatString": "0",
            "lineageTag": "7ce0e8d7-33c7-4238-9432-3f88aabe08ce"
          },
          {
            "name": "Measure 5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[quarter_3RD]+[quarter_4TH]+[quarter_Previous quarter]+[Quarter_Current Quarter]",
            "lineageTag": "1489994a-e86d-4180-b2df-b8d568f16c91"
          },
          {
            "name": "Risk for Last 3rd month",
            "expression": [
              "CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-2,MONTH))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9752ff37-2b8e-426d-b9a3-0925555b0737"
          },
          {
            "name": "DateTable",
            "expression": "CALENDAR(MIN('ServiceRiskAnalysisCombined'[Date]), MAX('ServiceRiskAnalysisCombined'[Date]))",
            "formatString": "General Date",
            "lineageTag": "c26cb55a-549b-4cbe-8aab-7ff0e58aa383"
          },
          {
            "name": "AVERAGE Variance",
            "expression": [
              "var a= CALCULATE(AVERAGE(ServiceRiskAnalysisCombined[TotalRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[Date]))",
              "",
              "var b=CALCULATE(AVERAGE(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-2,MONTH))",
              "",
              "return a-b"
            ],
            "formatString": "0.00",
            "lineageTag": "94e48c77-90ae-41ea-9864-8f0549002a4a"
          },
          {
            "name": "Variance Monthly",
            "expression": [
              "var a= CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[Date]),all(VW_Reporting_Calendar[Date]))",
              "",
              "var b=CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-1,MONTH),all(VW_Reporting_Calendar[Date]))",
              "",
              "return a-b"
            ],
            "formatString": "0",
            "lineageTag": "34022c7b-ea04-4f33-855e-a503d1220c7e"
          }
        ],
        "partitions": [
          {
            "name": "Measure for Mnthly Dashboard-4efe89e2-5b88-46e4-9cb3-a2271a4df957",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"XY69DoIwFEZf5aYzi/86EiYGBolxIQzXclNvlItpy+DbWxpKiPM5+b7TNCo3JPoLxeA81OxeKlMb1WaNKq4FlPIky546qNGzmGRso1GhoCELd9QomsklvIu4Jm1H9j3JsryfgeFB8A1pYKaHSG+EPVTUPwLIvQ/3QU7KcZXmPqTX7LSw6cB5sqH77+IcnVICnALyseMl7qLa9gc=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Rating = _t, ID = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Rating\", type text}, {\"ID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e50f56d3-ada2-4687-886c-83e896ca9442",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5cd46ca9-53d5-493a-b3b9-40e613a018bf",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0dc457a1-a206-4ef2-b027-1ac8cc2d6c54",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d340b428-7476-4cfb-bb9c-44ccc3643fb2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "042036af-bfd4-4ec4-abd5-bbed5f6dd9d5",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "dd8ee161-0e3c-4ad8-ad4e-7e1af7861937",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "560bc912-47cd-43f4-9555-45077ccc676e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0de6c9a8-0e1c-4592-8148-e077ef6ac313",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1120252b-3937-4acb-a47e-ad179236e47e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "e3f2fd66-aaa2-43b0-951b-a55d99cf25d7",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "54d40f91-9c4c-4e02-943e-0e1fd8b973d2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f224a5c2-1b97-491f-9f97-a783f56e98fb",
                "ordinal": 3
              }
            ],
            "lineageTag": "9684ab7d-e6de-44bb-8501-034bcd70c22b"
          }
        ],
        "isHidden": true,
        "lineageTag": "66ba5644-913d-4357-8e29-dfddab95b50d",
        "partitions": [
          {
            "name": "LocalDateTable_e50f56d3-ada2-4687-886c-83e896ca9442-502b34cb-7343-425a-9961-0c43be355430",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SnapshotRiskbytype'[Date])), 1, 1), Date(Year(MAX('SnapshotRiskbytype'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "VW_Risk_Level_Groups",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "FacilityCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6c0b22bd-a73d-427c-9eca-7f154f49753a",
            "sourceColumn": "FacilityCode",
            "summarizeBy": "count"
          },
          {
            "name": "FacilityName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9e614c2a-ef3c-4cfc-b82a-95f00720e1cf",
            "sourceColumn": "FacilityName",
            "summarizeBy": "none"
          },
          {
            "name": "Head_Of_Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "febea4c0-37fc-4859-9c2d-24f69b8de10c",
            "sourceColumn": "Head_Of_Operations",
            "summarizeBy": "none"
          },
          {
            "name": "Month_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b8bfd038-f221-44b0-b407-d02b00932efc",
            "sourceColumn": "Month_Name",
            "summarizeBy": "none"
          },
          {
            "name": "fiscal_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a3c2eaf0-a556-49e1-a6d5-7d802a14753d",
            "sourceColumn": "fiscal_month",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarYearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "40c14021-a815-4a3d-8ad7-f83e5f27984e",
            "sourceColumn": "CalendarYearMonth",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarMonthNameYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "2f5fb856-5d98-4fa3-905c-430f920413fb",
            "sortByColumn": "CalendarYearMonth",
            "sourceColumn": "CalendarMonthNameYear",
            "summarizeBy": "none"
          },
          {
            "name": "RisLevelkCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "275e33a8-fd9f-4f18-a466-de40d11c5618",
            "sourceColumn": "RisLevelkCount",
            "summarizeBy": "sum"
          },
          {
            "name": "RiskLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae6a889a-3e04-4098-97d8-b650d03345a3",
            "sourceColumn": "RiskLevel",
            "summarizeBy": "none"
          },
          {
            "name": "RiskGroup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c9920d85-d67d-489a-b17c-da81808f8e7b",
            "sourceColumn": "RiskGroup",
            "summarizeBy": "none"
          },
          {
            "name": "HashKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "baefcf6f-646c-4565-9de8-832ed0e12d50",
            "sourceColumn": "HashKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7d34a65c-585e-4f42-851c-d0559a49b737",
        "measures": [
          {
            "name": "Scattered Chart colour",
            "expression": [
              "",
              "",
              "--IF(CALCULATE([Combined Risk Monthly],VW_Risk_Level_Groups[RiskGroup]=\"No high Risk\"),\"#27B54D\"",
              "IF(CALCULATE([Combined Risk Monthly],VW_Risk_Level_Groups[RiskGroup]=\"Service with 1-2 High Risk\"),\"#0EAAF2\",",
              "IF(CALCULATE([Combined Risk Monthly],VW_Risk_Level_Groups[RiskGroup]=\"Service with 3-4 High risk\"),\"#F2C80F\",",
              "IF(CALCULATE([Combined Risk Monthly],VW_Risk_Level_Groups[RiskGroup]=\"Service with 5 and Over High Risk\"),\"#FD625E\",\"#27B54D\")))"
            ],
            "lineageTag": "145b2a41-a53c-44b3-8225-ab290a49f2d2"
          },
          {
            "name": "Service by Rating Colour",
            "expression": [
              "",
              "",
              "CALCULATE(DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityName]),VW_Risk_Level_Groups[RiskGroup]=\"no high risk\")"
            ],
            "formatString": "0",
            "lineageTag": "222d6a1f-2242-4469-b250-e52040bd8b18"
          }
        ],
        "partitions": [
          {
            "name": "VW_Risk_Level_Groups-52f1e390-00cd-44d0-bc71-dc31217801ca",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\"),",
                "    ATDMP = Source{[Name=\"ATDMP\"]}[Data],",
                "    dbo_VW_Risk_Level_Groups = ATDMP{[Schema=\"dbo\",Item=\"VW_Risk_Level_Groups\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(dbo_VW_Risk_Level_Groups,\"good\",\"No High Risk\",Replacer.ReplaceText,{\"RiskGroup\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"Service with more than 4 high Risk\",\"Services with 5 and over High risk\",Replacer.ReplaceText,{\"RiskGroup\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"Service with more than 4  High Risk\",\"Services with 5 and over High Risk\",Replacer.ReplaceText,{\"RiskGroup\"})",
                "in",
                "    #\"Replaced Value2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_412af3c3-2343-4649-86dd-f10f833f1a4b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f9f969b9-b515-4316-8314-fcb6ccb4dd46",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "fe1b06ce-ef33-49d5-b115-73a4490dc0f3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f2540683-31cc-4727-a6c6-2834b3e7ad11",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d2e8bdc5-4cb5-4a91-b64b-d98bb7ac09e3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "62fe5c55-d6d4-4dff-b243-81c557e72568",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f106af29-3a41-4d81-8489-2b0595f006d6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4af7c9f1-f6c5-453a-91d6-48bd3cb8c662",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "beba0c6c-d453-4c30-abf3-ff990ae1679f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "a6153ac1-ba50-45fb-afe1-ea8386b83d24",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "33b7e1e7-19d2-437f-8333-ce2f4b1f9c9c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2f8eb2c4-a419-4396-a0e0-278039ebe925",
                "ordinal": 3
              }
            ],
            "lineageTag": "17b518dd-cbae-43c0-b657-3a9133199c76"
          }
        ],
        "isHidden": true,
        "lineageTag": "22ae6533-34a9-441f-bdea-b78611b66843",
        "partitions": [
          {
            "name": "LocalDateTable_412af3c3-2343-4649-86dd-f10f833f1a4b-0e82fd05-0878-4a7c-bb08-1613d9b01f3a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SnapshotRiskbytype'[MonthYear])), 1, 1), Date(Year(MAX('SnapshotRiskbytype'[MonthYear])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "DimServiceLocationsMapping",
        "columns": [
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "62956a0f-4f63-4181-bc10-7a63ee835329",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "Property interest",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77520954-3799-414d-8383-220051e212c4",
            "sourceColumn": "Property interest",
            "summarizeBy": "none"
          },
          {
            "name": "Facility Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a52babd-2782-49c3-bc60-d16bb776c861",
            "sourceColumn": "Facility Status",
            "summarizeBy": "none"
          },
          {
            "name": "Service Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ceb3b19e-abe6-48f6-be3b-9261159a4609",
            "sourceColumn": "Service Status",
            "summarizeBy": "none"
          },
          {
            "name": "Service Type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "408903f9-190b-4c48-acf8-d7b5e2074613",
            "sourceColumn": "Service Type",
            "summarizeBy": "none"
          },
          {
            "name": "Agency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8103ec4c-900b-4837-a8d4-103f6dc79466",
            "sourceColumn": "Agency",
            "summarizeBy": "none"
          },
          {
            "name": "Regulator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ebb6d95f-c4c2-48fe-87e0-959d65ebb9e7",
            "sourceColumn": "Regulator",
            "summarizeBy": "none"
          },
          {
            "name": "Regulator ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4f35062f-a02b-4b0a-bd42-67617046a006",
            "sourceColumn": "Regulator ID",
            "summarizeBy": "none"
          },
          {
            "name": "Regulator Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b94f7a8f-445e-4ffa-adc9-fe114a77bace",
            "sourceColumn": "Regulator Name",
            "summarizeBy": "none"
          },
          {
            "name": "Area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "974e7a70-8d43-4824-9015-57c88a850550",
            "sourceColumn": "Area",
            "summarizeBy": "none"
          },
          {
            "name": "Operations Director",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "071f9a21-da86-4adf-a065-197046d68f03",
            "sourceColumn": "Operations Director",
            "summarizeBy": "none"
          },
          {
            "name": "Head of Operations",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf45d084-7fc6-4c1f-92f7-e121041c6f99",
            "sourceColumn": "Head of Operations",
            "summarizeBy": "none"
          },
          {
            "name": "Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a669844-5291-4c76-8761-5da73acee7d7",
            "sourceColumn": "Region",
            "summarizeBy": "none"
          },
          {
            "name": "Regional Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad853ea2-d308-4660-a557-44821afab80a",
            "sourceColumn": "Regional Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Senior Service Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6e5f5e80-d790-41a9-9e5b-c6cdac8bdfdc",
            "sourceColumn": "Senior Service Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d372a39-2269-40a4-9d17-6ab17680c91e",
            "sourceColumn": "Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Deputy Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "88233251-081b-4dcd-b9a6-bce2d63a5b03",
            "sourceColumn": "Deputy Manager",
            "summarizeBy": "none"
          },
          {
            "name": "Administrator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a50fb04f-e21b-44bc-aa5b-300925bbf23e",
            "sourceColumn": "Administrator",
            "summarizeBy": "none"
          },
          {
            "name": "Recruitment Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d342971-3913-417e-b8f4-6114f7964ac7",
            "sourceColumn": "Recruitment Manager",
            "summarizeBy": "none"
          },
          {
            "name": "HR Advisor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41ba2545-f9e6-43dd-b7f3-1dd24c4920bd",
            "sourceColumn": "HR Advisor",
            "summarizeBy": "none"
          },
          {
            "name": "APM",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e480371c-c73a-4e95-8b99-4182feb1389c",
            "sourceColumn": "APM",
            "summarizeBy": "none"
          },
          {
            "name": "Quality Partner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "335e58f9-170b-4e90-b559-68ff85da08d5",
            "sourceColumn": "Quality Partner",
            "summarizeBy": "none"
          },
          {
            "name": "Local Authority",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b34643d1-528c-4184-9d6a-1e50d95676ae",
            "sourceColumn": "Local Authority",
            "summarizeBy": "none"
          },
          {
            "name": "Phone Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "620d8c60-29f9-4e66-88f9-26d1437d12e3",
            "sourceColumn": "Phone Number",
            "summarizeBy": "none"
          },
          {
            "name": "Cost Centre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07a79d7e-1fb4-46c7-992e-a7db08084d3e",
            "sourceColumn": "Cost Centre",
            "summarizeBy": "none"
          },
          {
            "name": "Facility Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d675c88-838a-4453-9f4e-46e81765f5bd",
            "sourceColumn": "Facility Code",
            "summarizeBy": "none"
          },
          {
            "name": "Historical Company Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fba2d040-b0d3-4200-b91c-7449fb30a403",
            "sourceColumn": "Historical Company Name",
            "summarizeBy": "none"
          },
          {
            "name": "Update Required?",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e92e2d55-b278-4ff8-bc47-7e4e6839864d",
            "sourceColumn": "Update Required?",
            "summarizeBy": "none"
          },
          {
            "name": "Temporary Systems Access Request",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "764c9ddd-2d05-4efe-a315-3316285ccaf4",
            "sourceColumn": "Temporary Systems Access Request",
            "summarizeBy": "none"
          },
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dc6df684-832a-48b1-84f7-e71b13d5d593",
            "sourceColumn": "ID",
            "summarizeBy": "none"
          },
          {
            "name": "Modified",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a351d27d-1a60-4dd5-9351-1a33bdf4ce96",
            "sourceColumn": "Modified",
            "summarizeBy": "none"
          },
          {
            "name": "Modified By",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "673c2f9c-ce70-41a8-b627-24bec4d62ebd",
            "sourceColumn": "Modified By",
            "summarizeBy": "none"
          },
          {
            "name": "R1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b164d761-28e8-4ca8-b89d-afe47bd4e297",
            "sourceColumn": "R1",
            "summarizeBy": "none"
          },
          {
            "name": "AC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fd2895c-c6e9-4c54-8e27-848efc45f682",
            "sourceColumn": "AC",
            "summarizeBy": "none"
          },
          {
            "name": "HC",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d3a2c75-6f1d-45fe-81af-8302819511cc",
            "sourceColumn": "HC",
            "summarizeBy": "none"
          },
          {
            "name": "OfficeSpace",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e10ee91-8eac-475c-93c9-6e5362582a9b",
            "sourceColumn": "OfficeSpace",
            "summarizeBy": "none"
          },
          {
            "name": "LocationCountryRegion",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "955e6dc8-326f-4655-abd5-b85af7818189",
            "sourceColumn": "LocationCountryRegion",
            "summarizeBy": "none"
          },
          {
            "name": "Coordinates",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bb2992eb-4c9c-492e-ac6a-ff218739adc1",
            "sourceColumn": "Coordinates",
            "summarizeBy": "none"
          },
          {
            "name": "Map_LocationName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1808a761-03dd-447b-8695-d1811e8e71eb",
            "sourceColumn": "Map_LocationName",
            "summarizeBy": "none"
          },
          {
            "name": "Map_Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d63af450-d56e-4997-96a3-701de6081b7b",
            "sourceColumn": "Map_Country",
            "summarizeBy": "none"
          },
          {
            "name": "Map_City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "116ec979-946b-4f4a-951f-99a07062c810",
            "sourceColumn": "Map_City",
            "summarizeBy": "none"
          },
          {
            "name": "Map_PostalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46f7d5bf-46b2-4986-af73-abead52a084e",
            "sourceColumn": "Map_PostalCode",
            "summarizeBy": "none"
          },
          {
            "name": "Map_Street",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d0304ac-4c45-420a-8cd2-194c9d67fae5",
            "sourceColumn": "Map_Street",
            "summarizeBy": "none"
          },
          {
            "name": "Longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bad317d-dca4-4051-8d48-1e6df27e384f",
            "sourceColumn": "Longitude",
            "summarizeBy": "none"
          },
          {
            "name": "Latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd78c480-7c87-4afe-b215-ca1025bf8e1d",
            "sourceColumn": "Latitude",
            "summarizeBy": "none"
          },
          {
            "name": "Finance_Service_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8c54cddf-2618-4cb8-bbd0-c9ca24c28bff",
            "sourceColumn": "Finance_Service_name",
            "summarizeBy": "none"
          },
          {
            "name": "Finance_Facility_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6c7aeea-ffbe-4f34-8e0a-5550440b00de",
            "sourceColumn": "Finance_Facility_code",
            "summarizeBy": "none"
          },
          {
            "name": "Finance_cost_centre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db23a39b-44b5-4faf-a001-83e588fae1bb",
            "sourceColumn": "Finance_cost_centre",
            "summarizeBy": "none"
          },
          {
            "name": "Director_of_Ops_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8796272b-3d7f-4d84-b568-bc4b3ea7ac63",
            "sourceColumn": "Director_of_Ops_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Head_of_Ops_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8cd8ae7b-e6c5-4d11-a02d-245ca3fef5bc",
            "sourceColumn": "Head_of_Ops_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Regional_Manager_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07bc0bc5-063c-43ce-b8c4-a2a26bbbeb29",
            "sourceColumn": "Regional_Manager_Email",
            "summarizeBy": "none"
          },
          {
            "name": "Manager_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b12b2e73-6ec6-4fc5-aa2e-5f3545ae1cbf",
            "sourceColumn": "Manager_Email",
            "summarizeBy": "none"
          },
          {
            "name": "DCA_Manager_Email",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "311b40c9-9650-460a-8f0a-16d9e9091a0d",
            "sourceColumn": "DCA_Manager_Email",
            "summarizeBy": "none"
          },
          {
            "name": "DCA_Manager",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "09675574-3e00-4846-ba97-0454d08556e6",
            "sourceColumn": "DCA_Manager",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "2414a171-8206-4fde-a63c-60df61ea1988",
        "partitions": [
          {
            "name": "DimServiceLocationsMapping-09713efb-7f91-458f-a793-243d92011caa",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\"),",
                "    ATDMP = Source{[Name=\"ATDMP\"]}[Data],",
                "    dbo_DimServiceLocationsMapping = ATDMP{[Schema=\"dbo\",Item=\"DimServiceLocationsMapping\"]}[Data]",
                "in",
                "    dbo_DimServiceLocationsMapping"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "VW_Reporting_Calendar",
        "columns": [
          {
            "name": "Calendar_Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64ae1200-9686-43c5-8135-e20ae7ab8a28",
            "sourceColumn": "Calendar_Month",
            "summarizeBy": "sum"
          },
          {
            "name": "calendar_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "69811232-60e3-4a18-88cd-d0e5f39eef2b",
            "sourceColumn": "calendar_year",
            "summarizeBy": "sum"
          },
          {
            "name": "calendar_quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a9456c7c-3c7b-4108-bd6c-357183418cdf",
            "sourceColumn": "calendar_quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Month_Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb03712f-280d-46f1-ac6a-cc75ef3379e4",
            "sourceColumn": "Month_Name",
            "summarizeBy": "none"
          },
          {
            "name": "days_in_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0da9ed90-197b-453e-a102-af2d215a67b3",
            "sourceColumn": "days_in_month",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9da1e3db-48c3-4d8d-9efb-b7db56465bb5",
            "sourceColumn": "fiscal_quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "67793fab-246c-4137-9d80-c2689de2e73b",
            "sourceColumn": "fiscal_month",
            "summarizeBy": "sum"
          },
          {
            "name": "fiscal_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5b469a95-426e-4f3b-94e5-d825f87860aa",
            "sourceColumn": "fiscal_year",
            "summarizeBy": "sum"
          },
          {
            "name": "CalendarYearMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "389998b7-dbf5-49fc-b3a0-d4a694eef1c4",
            "sourceColumn": "CalendarYearMonth",
            "summarizeBy": "none"
          },
          {
            "name": "CalendarMonthNameYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab6b24b7-28ce-4ea9-b977-a04ef4dd966d",
            "sourceColumn": "CalendarMonthNameYear",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal_MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0a2789a-c613-42f6-8966-a169704354af",
            "sourceColumn": "Fiscal_MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "FiscalMonthNameYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f78027f7-2f43-4992-813d-cf1e72d782b2",
            "sourceColumn": "FiscalMonthNameYear",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "    VALUE(LEFT([CalendarYearMonth],4)),",
              "    VALUE(RIGHT([CalendarYearMonth], 2)),",
              "    1",
              ")"
            ],
            "formatString": "mmmm yyyy",
            "isDataTypeInferred": true,
            "lineageTag": "805b8d6e-498a-49c0-8411-b69f1cd9673f",
            "summarizeBy": "none",
            "type": "calculated",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_65c127da-c204-48fa-8138-59bcdfce17b8"
                },
                "isDefault": true,
                "relationship": "b46455f2-78a0-444c-9c30-9e28d06f17da"
              }
            ]
          },
          {
            "name": "First_Date_of_Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "36743b38-6fc6-45c3-877b-905dbb6b5827",
            "sourceColumn": "First_Date_of_Month",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_9359371c-f6a8-4e93-a3c9-49bd5d0f4dd6"
                },
                "isDefault": true,
                "relationship": "a4a8c1ff-235b-425b-98b3-bc278dba43ca"
              }
            ]
          },
          {
            "name": "Last_Date_of_Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a6b44136-5881-432d-a43b-70ae31f9c5f2",
            "sourceColumn": "Last_Date_of_Month",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_0623f1e2-e5a3-4be3-84ed-f2d9bcdb69e7"
                },
                "isDefault": true,
                "relationship": "f6b10162-a512-41ad-8689-5d39f9bac5c7"
              }
            ]
          }
        ],
        "lineageTag": "8a8b4235-36d9-4419-8c42-6ed23d69487f",
        "partitions": [
          {
            "name": "VW_Reporting_Calendar-d4fd0ece-4329-4017-b731-3a04e4e7017f",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Databases(\"sqlminstanceatprod.public.6ebcd2a481ea.database.windows.net,3342\"),",
                "    ATDMP = Source{[Name=\"ATDMP\"]}[Data],",
                "    dbo_VW_Reporting_Calendar = ATDMP{[Schema=\"dbo\",Item=\"VW_Reporting_Calendar\"]}[Data]",
                "in",
                "    dbo_VW_Reporting_Calendar"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_40459186-9a00-4d17-87f1-129b9e044325",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a1fb02b5-32d8-4af4-9bf0-d8d7f40ec4cc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "08b118e0-c44b-43e7-96c4-e9b68116191c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "55f65425-826d-4603-b659-60c73d2add0c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2b58dd9e-3dc6-4015-a279-03333d6f2a9a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "5add372e-2650-4cfa-994d-555b76c9562d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "76d04597-ec49-4b90-b08f-df308471695f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "99181214-5386-4341-a570-9621bc0fcde4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "29e9c7ff-1f88-4d49-88c8-6d15008f7246",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "2c558f36-1ac2-439a-9a49-861520ed0447",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ad773825-ded7-4d4d-b24a-7e859f1177ad",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3fd3fdfe-2015-48b0-879e-1888c0056c1d",
                "ordinal": 3
              }
            ],
            "lineageTag": "28331823-317f-449f-a99b-14262ce9521d"
          }
        ],
        "isHidden": true,
        "lineageTag": "ce727199-1fc1-45f8-8c23-4b7e59416b48",
        "partitions": [
          {
            "name": "LocalDateTable_40459186-9a00-4d17-87f1-129b9e044325-113392f5-979f-45ac-99ba-7b1b2dcd6c45",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('ServiceRiskAnalysisCombined'[Date])), 1, 1), Date(Year(MAX('ServiceRiskAnalysisCombined'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Risk value",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b36dd9793d0748069ad3697cc09b8c89"
          }
        ],
        "columns": [
          {
            "name": "Risk %",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "6b3385a0-a474-4dad-bb32-8f3e54cad2e9",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "e8d38c39-a8af-486d-8d6e-fde97cbdb3c7",
        "measures": [
          {
            "name": "Risk % Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE('Risk value'[Risk %],0)",
            "lineageTag": "1c734f5f-acb5-4fff-97bd-608efdd4c3ef"
          },
          {
            "name": "Predictive Risk",
            "expression": "sum(ServiceRiskAnalysisCombined[CQCinspectionRisk])*1",
            "formatString": "0",
            "lineageTag": "6220f25a-140b-4605-b85b-593617606edc"
          },
          {
            "name": "Same Period last year",
            "expression": [
              "CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),DATEADD(ServiceRiskAnalysisCombined[Date],-11,MONTH))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "fb02c3aa-d8f3-4e0f-bceb-e5abcf970817"
          },
          {
            "name": "Forecaste",
            "expression": "[Avg Total risk]-[Same Period last year]",
            "formatString": "0",
            "lineageTag": "db643c51-f040-4a55-ab08-fe19d5a42638"
          },
          {
            "name": "Measure 4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "[Risk Prediction]*'Risk value'[Risk % Value]",
            "lineageTag": "2bde4d14-a888-4668-b1aa-7d1bcc8a8fee"
          },
          {
            "name": "SamePeriodlastyear",
            "expression": [
              "VAR a=CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),SAMEPERIODLASTYEAR(VW_Reporting_Calendar[Date]))",
              "",
              "VAR B=CALCULATE(a,ServiceRiskAnalysisCombined[Date]>MAX(ServiceRiskAnalysisCombined[date]))",
              "",
              "return IF(MAX(ServiceRiskAnalysisCombined[date]),a)"
            ],
            "formatString": "0",
            "lineageTag": "858d9923-490b-48ca-9f13-da8bc7efe9a7"
          },
          {
            "name": "2023 Forecast",
            "expression": [
              "var a= [SamePeriodlastyear]",
              "",
              "Var b=CALCULATE(a,YEAR(VW_Reporting_Calendar[Date]=2023),all(VW_Reporting_Calendar))",
              "",
              "return b",
              "--SAMEPERIODLASTYEAR(VW_Reporting_Calendar[Date]),VW_Reporting_Calendar[calendar_year]=2022)"
            ],
            "formatString": "0",
            "lineageTag": "3eb76f83-3333-4f84-9df4-1bf92107f276"
          },
          {
            "name": "Cumilative Risk",
            "expression": "CALCULATE(SUM(ServiceRiskAnalysisCombined[TotalRisk]),FILTER(ALLSELECTED(VW_Reporting_Calendar),VW_Reporting_Calendar[Date]<=MAX(VW_Reporting_Calendar[Date])))",
            "formatString": "0",
            "lineageTag": "4ecc3178-3a4a-41c6-a8c7-6a36bc11de5e"
          },
          {
            "name": "Cumilative 2023 Risk",
            "expression": [
              "var a=CALCULATE([2023 Forecast],FILTER(ALLSELECTED(VW_Reporting_Calendar),VW_Reporting_Calendar[Date]<=MAX(VW_Reporting_Calendar[Date])))",
              "",
              "return CALCULATE(a,ALLSELECTED(ServiceRiskAnalysisCombined))"
            ],
            "formatString": "0",
            "lineageTag": "67b6605e-1cfb-42a1-a2d5-c14dd3f4c02f"
          },
          {
            "name": "Last12 months Variance",
            "expression": [
              "VAR a=",
              "CALCULATE([Variance],",
              "    DATESINPERIOD('ServiceRiskAnalysisCombined'[Date], LASTDATE('ServiceRiskAnalysisCombined'[Date]), -12, MONTH)",
              ")",
              " VAR SelectedDate = SELECTEDVALUE('VW_Reporting_Calendar'[Date])",
              "RETURN ",
              "    IF(SelectedDate>MAX(ServiceRiskAnalysisCombined[Date]),A,IF(SelectedDate<=MAX(ServiceRiskAnalysisCombined[Date]),[Variance]))",
              "",
              "    "
            ],
            "formatString": "0",
            "lineageTag": "7819dd43-4190-46f2-bc96-c96e82308a93"
          }
        ],
        "partitions": [
          {
            "name": "Risk value-1b1e2a79-f325-445f-a7ae-2a5286db7c19",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 4, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "72cd351def4f4d9e873b688d95937ff3"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "f65318b5-8693-4646-8283-ebc2f6febbf0",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "9f859567-eb49-47b8-81ea-40fb81cfe925",
        "measures": [
          {
            "name": "Parameter Value",
            "expression": "SELECTEDVALUE('Parameter'[Parameter], 0)",
            "formatString": "0",
            "lineageTag": "9e638f3c-5ffc-4f84-a536-ac058415e290"
          },
          {
            "name": "CQC",
            "expression": "DISTINCTCOUNT(ServiceRiskAnalysisCombined[FacilityCode])*Parameter[Parameter Value]",
            "formatString": "0",
            "lineageTag": "f67cb480-553a-4129-8403-5d15463db246"
          }
        ],
        "partitions": [
          {
            "name": "Parameter-994f54b4-ba6c-46b8-86e9-2ad21df182ba",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 4, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Table (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Source",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ea2fc922-075b-48cb-837d-128549f44e4b",
            "sourceColumn": "Source",
            "summarizeBy": "none"
          },
          {
            "name": "RiskValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f858df89-427e-4691-b6df-64dc8b3a622b",
            "sourceColumn": "RiskValue",
            "summarizeBy": "none"
          },
          {
            "name": "Source_RiskValue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE('Table (2)'[Source],'Table (2)'[RiskValue])",
            "isDataTypeInferred": true,
            "lineageTag": "24dbb164-5d1e-49ad-9daa-9bc59f0223c2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "26cb2d17-f451-4973-b71e-19659e25e11f",
        "measures": [
          {
            "name": "Measure 7",
            "expression": [
              "IF(VALUE(ISFILTERED('Table (2)'[Source])=\"CQC Inspection Risk\"),1,0)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "6a664648-f5c6-40f5-bb6b-f0bbcdf2a73a"
          },
          {
            "name": "CQC Forecast",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR A=CALCULATE([Monthly CQC Inspection],DATEADD(VW_Reporting_Calendar[Date],-1,YEAR))*(1+0.1)",
              "",
              "return if(YEAR(MAX(VW_Reporting_Calendar[date]))=2024,a)"
            ],
            "lineageTag": "86a37d7b-0a8b-424b-8797-61a8ce13c833"
          }
        ],
        "partitions": [
          {
            "name": "Table (2)-f7b9b6c3-c210-4bf5-b996-0329884d2d63",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"hdTBasMwDAbgVzE59zCpe4EQViish4WxS+nBOMIza9TiuIe9/dx5Y0tqqedP+Jdlo/2+6V46s+XpTC6FE5s+TB/NqnloDivJQDFUbK3Y47f15OIlpJE4zRupAEiAEqwl+A33uSF7NDvL1lNcdlBXUBVV/RtIrhjMzsfb8S8FREFRSs4GN6Y7jedjsOxonlQ3UAwVK3lPz2QjB/ZiqlYBdyvwbkXpY8uJ4nX67WUIi39VN1AMFSt5P4/8Zl3uJdA0T5QUVEVVS27rid1nHsO0uGQFQAKUoGS8kh1Nm1IMt8uibqAYKvZ/WbxTNhpMb9P1oSsrql6Rzz98AQ==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", Int64.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Source\"}, {\"Column2\", \"RiskValue\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Head of Operations",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b72be0a9f00b4c62b96479fa1a58bb18"
          }
        ],
        "columns": [
          {
            "name": "HOA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "e87875de-a65c-4f82-8931-0bd6dc3db3cf",
            "sourceColumn": "[HOA]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Fiscal Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "de26f8d1-65bb-4519-82d9-448c120bd3fd",
            "sourceColumn": "[Fiscal Month]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "HOA_Alias",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "IF('Head of Operations'[HOA]=\"Emma Bagley\",\"kate Durband\",'Head of Operations'[HOA])",
            "isDataTypeInferred": true,
            "lineageTag": "baa875bb-8fbd-4027-b7ec-ee1c81710f2b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "HOA_FiscalMOnth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "CONCATENATE('Head of Operations'[HOA_Alias],'Head of Operations'[Fiscal Month])",
            "isDataTypeInferred": true,
            "lineageTag": "9e7b8610-1532-4af5-8f97-781942b322fe",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "997c5aea-8bba-4375-b958-5bf16ac7d8f6",
        "measures": [
          {
            "name": "HOA's",
            "expression": "IF(ISFILTERED(SnapshotRiskbytype[Head of Operations_Revised)]),SELECTEDVALUE('SnapshotRiskbytype'[Head of Operations],BLANK()))",
            "lineageTag": "85234595-6c45-4363-9ab5-a4120fe564b4"
          }
        ],
        "partitions": [
          {
            "name": "Head of Operations-6acfb240-758b-42b8-a7cc-514f9ca9cadf",
            "mode": "import",
            "source": {
              "expression": "CALCULATETABLE(DISTINCT(SELECTCOLUMNS(SnapshotRiskbytype,\"HOA\",SnapshotRiskbytype[Head of Operations],\"Fiscal Month\",SnapshotRiskbytype[fiscal_month])))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_65c127da-c204-48fa-8138-59bcdfce17b8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "990bd28f-92be-43bb-965b-1b7a5c862d30",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f3bc3380-20f7-407e-82e4-28c550485e00",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1048834d-1d02-48ad-a850-f7a49d87101b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ab079f90-8487-4c86-a492-24ce63ac090e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3db4539e-2332-4311-87bf-822d4d9d656a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "d6d2a913-8234-43fc-9804-6427dc89dfe3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "42a6d001-4a56-4338-bbc5-274ac96be4ce",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "3ada4720-0918-4856-b7c8-2aaeaa05e910",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "abb7c3dd-f2a7-4f4b-a104-2d2b63197586",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "abef9e3d-6683-4d37-91ef-3c56e2890dea",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2ca03905-9a86-4067-81ff-4ba611e1ef9b",
                "ordinal": 3
              }
            ],
            "lineageTag": "9b50dc5b-62af-4224-aadb-b367a5af826f"
          }
        ],
        "isHidden": true,
        "lineageTag": "e9e7974a-9642-4aae-9013-f6dd421f94ad",
        "partitions": [
          {
            "name": "LocalDateTable_65c127da-c204-48fa-8138-59bcdfce17b8-ee6deafb-85c5-490a-847e-bf1d2f1fdd50",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('VW_Reporting_Calendar'[Date])), 1, 1), Date(Year(MAX('VW_Reporting_Calendar'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Parameter 2",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b35489d1531842459e8ef7c12930d7b3"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "e657ad58-c72a-49da-a765-1e569fdecad9",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "6ff9dd50-c377-4e6a-ad9d-05fa963eb33a",
        "measures": [
          {
            "name": "Parameter Value 2",
            "expression": "SELECTEDVALUE('Parameter 2'[Parameter])",
            "formatString": "0",
            "lineageTag": "46860b94-ef8f-4576-80b0-0c0bb426bb5e"
          },
          {
            "name": "CQCTest",
            "expression": [
              "var a=SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk])",
              " ",
              " var b= IF(a =3,IF('Parameter 2'[Parameter Value 2] = 2,a-1),IF(a=4,IF('Parameter 2'[Parameter Value 2]=2,a-2),IF(a in {0,2},a)))",
              " ",
              " VAR C=IF(a=1,IF('Parameter 2'[Parameter Value 2]=3,a+2),IF(a<>1,a))",
              "",
              " VAR D=IF(a=2,IF('Parameter 2'[Parameter Value 2]=3,a+1),IF(a<>2,a))",
              " ",
              " return IF('Parameter 2'[Parameter Value 2]=2,b,IF('Parameter 2'[Parameter Value 2]=1,C,IF('Parameter 2'[Parameter Value 2]=3,D)))",
              " "
            ],
            "formatString": "0",
            "lineageTag": "f6debb0b-fd4b-4cef-9ee8-40ac340be4a0"
          },
          {
            "name": "Forecast RiskGroup",
            "expression": [
              "var a=CALCULATE(SUM(ServiceRiskAnalysisCombined[High Risk Grouping])-1)",
              "",
              "VAR B=CALCULATE(SUM(ServiceRiskAnalysisCombined[high Risk Grouping])+1)",
              "",
              "Var CQC=SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk])",
              "",
              "Var C= IF(cqc in {3,4},IF('Parameter 2'[Parameter Value 2]=2,IF(a>=5,\"Service with 5 or more\",IF(a in {3,4},\"Service with 3-4 High Risk\",IF(a in {1,2},\"Service with 1-2 High risk\",IF(a <1,\"No High risk\"))))))",
              "",
              "VAR D=IF(cqc=2,IF('Parameter 2'[Parameter Value 2]=3,IF(b>=5,\"Service with 5 or more\",IF(b in {3,4},\"Service with 3-4 High Risk\",IF(b in {1,2},\"Service with 1-2 High risk\",IF(b <1,\"No High risk\"))))))",
              "",
              "Var E=IF(cqc=0,IF('Parameter 2'[Parameter Value 2]=3,IF(b>=5,\"Service with 5 or more\",IF(b in {3,4},\"Service with 3-4 High Risk\",IF(b in {1,2},\"Service with 1-2 High risk\",IF(b <1,\"No High risk\"))))))",
              "",
              "",
              "Return IF('Parameter 2'[Parameter Value 2]=2,C,IF('Parameter 2'[Parameter Value 2]=3,D,IF('Parameter 2'[Parameter Value 2]=0,E)))"
            ],
            "lineageTag": "dd90be67-b37c-425c-b59e-081d6b9a694e"
          }
        ],
        "partitions": [
          {
            "name": "Parameter 2-71789229-388e-441a-b3a0-79b67e113879",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 4, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Parameter 3",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "acec50c84b874c1b9dfac410956020b8"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "811c7eee-5f8e-483a-8001-f6284e461058",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "83a4d479-a612-4720-a3aa-6e4f39d5bd2c",
        "measures": [
          {
            "name": "TurnOver",
            "expression": "SELECTEDVALUE('Parameter 3'[Parameter], 2)",
            "formatString": "0",
            "lineageTag": "6e01c63b-8b0c-40b5-9a1c-f8daaa8011d7"
          },
          {
            "name": "CQC-Turnover",
            "expression": [
              "VAR A= MAX(ServiceRiskAnalysisCombined[Date])",
              "",
              "VAR B=IF(ISBLANK(SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk])),3,BLANK())",
              "",
              "VAR C=IF([TurnOver]=2,IF(CALCULATE(SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[date]))=3,0,2))",
              "",
              "",
              "VAR D=IF([TurnOver]=3,IF(CALCULATE(SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[date])) in {0,1,2,3},0,3))",
              "",
              "VAR E=IF([TurnOver]=1,IF(CALCULATE(SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[date])) in {0,1,2,3},0,1))",
              "",
              "",
              "",
              "Return  IF(ISBLANK(SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk])),IF([TurnOver]=2,C,IF([TurnOver]=3,D,IF([TurnOver]=1,e))))",
              "",
              "/*IF([TurnOver]=2,(ISBLANK(SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk])),c,",
              "IF([TurnOver]=3,ISBLANK(SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk])*/",
              ""
            ],
            "formatString": "0",
            "lineageTag": "48c9079f-b5c6-42c1-b138-541ddc3d04fc"
          },
          {
            "name": "CQC-Turnover Forecast",
            "expression": [
              "var a= SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk])",
              "",
              "Var b= [CQC-Turnover]",
              "",
              "return a+b",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "56231451-582e-4b5e-a6e8-5c9de8711349"
          },
          {
            "name": "Measure 12",
            "expression": [
              "var a=SUM(ServiceRiskAnalysisCombined[CQCinspectionRisk])",
              "",
              "var b= [CQC-Turnover]",
              "",
              "return IF([CQC-Turnover Forecast]=a,\"#01B8AA\")"
            ],
            "lineageTag": "f7b84cd6-c965-4b67-ac74-87573547f0b5"
          },
          {
            "name": "Internal Audit-Turnover",
            "expression": [
              "VAR A= MAX(ServiceRiskAnalysisCombined[Date])",
              "",
              "VAR B=IF(ISBLANK(SUM(ServiceRiskAnalysisCombined[InternalAuditRisk])),3,BLANK())",
              "",
              "VAR C=IF([TurnOver]=2,IF(CALCULATE(SUM(ServiceRiskAnalysisCombined[InternalAuditRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[date]))=3,0,2))",
              "",
              "",
              "VAR D=IF([TurnOver]=3,IF(CALCULATE(SUM(ServiceRiskAnalysisCombined[InternalAuditRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[date])) in {0,1,2,3},0,3))",
              "",
              "VAR E=IF([TurnOver]=1,IF(CALCULATE(SUM(ServiceRiskAnalysisCombined[InternalAuditRisk]),ServiceRiskAnalysisCombined[Date]=MAX(ServiceRiskAnalysisCombined[date])) in {0,1,2,3},0,1))",
              "",
              "",
              "",
              "Return  IF(ISBLANK(SUM(ServiceRiskAnalysisCombined[InternalAuditRisk])),IF([TurnOver]=2,C,IF([TurnOver]=3,D,IF([TurnOver]=1,e))))",
              ""
            ],
            "formatString": "0",
            "lineageTag": "1428bbcc-9ea5-4c99-81f7-0dd03b4363a2"
          },
          {
            "name": "Internal-Turnover Forecast",
            "expression": [
              "var a= SUM(ServiceRiskAnalysisCombined[InternalAuditRisk])",
              "",
              "Var b= [Internal Audit-Turnover]",
              "",
              "return a+b",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "9ff7d0e3-ae0a-4c7b-9137-faa2db6f32b4"
          },
          {
            "name": "Overall Forecast",
            "expression": "[CQC-Turnover Forecast]+[Internal-Turnover Forecast]",
            "formatString": "0",
            "lineageTag": "229fc5ad-e2b0-464f-8925-921f102ba04f"
          }
        ],
        "partitions": [
          {
            "name": "Parameter 3",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(0, 3, 1)",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_9359371c-f6a8-4e93-a3c9-49bd5d0f4dd6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bd5b0ae7-b095-4e43-bcb7-e94bdafa7443",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "62bc9c63-b85d-48d2-a2b4-e80d17d40e66",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b110f8ef-b767-45e6-80c6-bd22ca72e4ac",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "892d4620-62a7-4412-8f6a-fb995c098a85",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7d3e1154-a055-4985-9d4d-a35fb4dbf72c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f1130146-db4c-4cd7-83ec-ac25e72cfc7e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "142cb2aa-54f7-405e-977d-a1f02e8265f2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "d0d87725-fa1d-4c9e-be12-afcabbb33e2d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "89ec7f4f-2b8a-49cc-9f40-121633697754",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d98e0a39-cb7b-4ae1-8d74-2332f1ce8e7f",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "76f3c4c6-28f9-4f97-b2b0-d5effd85af67",
                "ordinal": 3
              }
            ],
            "lineageTag": "be283a93-e395-484a-8452-50c93325d52f"
          }
        ],
        "isHidden": true,
        "lineageTag": "805596f0-514e-4f74-8106-733258e2eb58",
        "partitions": [
          {
            "name": "LocalDateTable_9359371c-f6a8-4e93-a3c9-49bd5d0f4dd6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('VW_Reporting_Calendar'[First_Date_of_Month])), 1, 1), Date(Year(MAX('VW_Reporting_Calendar'[First_Date_of_Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_0623f1e2-e5a3-4be3-84ed-f2d9bcdb69e7",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "eba76f97-0db5-4719-b52f-c29a31220bf1",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b464e442-52cb-4877-9b54-6eb62f88acae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "15e5268d-691f-4745-a9dc-b1b6a62cc3c5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2992360b-6966-446d-b027-67f8837b46bb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "00737480-cc4b-4646-8216-2bef1047f449",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "79e86b3d-b759-4c72-9e2f-27da045f051f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "88ac0941-706c-4828-9efc-78da0d5e5308",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "4f206395-a78b-4fe7-985b-33e959e84f37",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ba8cece5-aac7-4f82-b0a3-842901e65d19",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "33135d9d-66e1-47e0-b078-cac35730fd7c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f36c53b2-b006-4c65-8ca4-82be8c74820d",
                "ordinal": 3
              }
            ],
            "lineageTag": "060f50ad-5631-4c1b-b7b0-6c12aefbdbe5"
          }
        ],
        "isHidden": true,
        "lineageTag": "6bd3b733-93df-42f3-b0d8-e2e9d8362141",
        "partitions": [
          {
            "name": "LocalDateTable_0623f1e2-e5a3-4be3-84ed-f2d9bcdb69e7",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('VW_Reporting_Calendar'[Last_Date_of_Month])), 1, 1), Date(Year(MAX('VW_Reporting_Calendar'[Last_Date_of_Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}